### ISSUE TITLE
Specify the ModelBuilder.createModel and other ModelBuilder members

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#107]
In https://github.com/webmachinelearning/webnn-polyfill/pull/23#discussion_r508076945, @pyu10055 mentioned

> this is bit confusing, the builder creates models, but the topology is created before the model is created, and how made the topology immutable for the model?

Today's spec lacks the detailed steps of [ModelBuilder.createModel](https://webmachinelearning.github.io/webnn/#dom-modelbuilder-createmodel) that causes the confusion.

**Comment by pyu10055** [comment]
during the offline discussion with Ningxin, my confusion comes from the naming of the createModel API, it seems that the Model is the context and the topology I am planning to build needs to be done after the model is created.
I think it would be good to clarify, the `createModel` method from the builder is to create an immutable copy of the current topology in memory, and any modification to the topology would not reflected in the created model. 
I would suggest to rename the method to `toModel()` instead.

**Comment by anssiko** [comment]
Thanks @pyu10055! I'm generally supportive of coming up with better names for the API surface, and encourage feedback from folks as early as possible. Renaming things is cheap up until we ship, after which it becomes very costly.

Re naming things, we should strive for intelligibility, consistency, and symmetry. We should consider this API a little language that web developers and framework authors must learn to read and write. Feedback from that audience is hugely valuable.

**Comment by wchao1115** [comment]
Typically in naming, *"toSomething"* implies the act of conversion such as in the TypedArray's `toString` method e.g. `const uint8String = uint8.toString();` while *"createSomething"* implies the act of construction. 

Further, the Builder idiom signified by the naming `ModelBuilder` already implies decoupling between the creator and the created instances, so it is already understood by this pattern that the change in the creator's state beyond the point of creation will not affect the state of the created instance. Whether the created instance is also immutable is beyond the implication of this said idiom.

**Comment by pyu10055** [comment]
I agree toModel might not be the best name, typically it is called build() method. And the builder pattern is to create a builder instance and call multiple steps on the builder, and finally trigger build() method to return the instance you are building.

But here the builder API are all functions, there is no clear a scope that specifies the boundary of all operations that belong to the model you are building.

**Comment by huningxin** [comment]
> typically it is called build() method

+1 to rename `createModel()` to `build()`.

**Comment by gramalingam** [comment]
Another aspect is that a ModelBuilder is not building a single/unique model, right? It can be used to build multiple models, if I remember right. The name ```build``` seems to suggest a unique model, which is also slightly misleading. Another possibility is ```model()``` which is consistent with the naming of other builder methods.

**Comment by wchao1115** [comment]
@gramalingam I tend to prefer a verb for the method name. 'build' just reads better in my opinion. I also don't think the existing builder idiom is specific to a single outcome if I remember correctly.

**Comment by gramalingam** [comment]
Consider the builder's methods ```input```, ```constant```, ```add```, etc. All of these methods _build_ objects of different kinds. I think ```createModel``` is similar. They are all builder methods, differing only in what is built. If we describe them verbosely, they would be ```buildInput```, ```buildConstant```, ```buildAddExpression```, etc.

**Comment by wchao1115** [comment]
Good point @gramalingam. The current name `createModel` does make it sound more explicit. I'm fine with leaving it as is too.

**Comment by anssiko** [comment]
Beyond the renaming, I think the spec is still lacking the detailed steps of `ModelBuilder.createModel` as well prose for its other interface members `input` and `constant`.

We should use the familiar convention (Arguments, Returns, algorithmic prose) for defining https://webmachinelearning.github.io/webnn/#api-modelbuilder Basically, we should translate the existing `//` comments into normative prose.

**Comment by inexorabletash** [comment]
The names referenced in this issue have all changed, so it's unclear what work remains here.

Does this end up being the same as #457 ? If so can this be closed out?
