### ISSUE TITLE
TensorFlow conv2d expects channel_last filter layout regardless of input layout format

### ISSUE THREAD

**Issue by wchao1115** [webmachinelearning/webnn#125]
From the WebNN [`conv2d`](https://webmachinelearning.github.io/webnn/#api-modelbuilder-conv2d) spec, the same `layout` parameter controls both the input and filter layout (below). In TensorFlow (and presumably TFLite), regardless of the input layout, the filter layout remains in the "channel_last" format i.e. `[height, width, input_channels/groups, output_channels]`.

*"nchw":*
input tensor: `[batches, input_channels, height, width]`
filter tensor: `[output_channels, input_channels/groups, height, width]`
output tensor: `[batches, output_channels, height, width]`

*"nhwc":*
input tensor: `[batches, height, width, input_channels]`
filter tensor: `[height, width, input_channels/groups, output_channels]`
output tensor: `[batches, height, width, output_channels]`

**Comment by huningxin** [comment]
It looks like [TFLite](https://github.com/tensorflow/tensorflow/issues/22540#issuecomment-425141930) and [NNAPI](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a34a73b5eaf458b67db5eda71557d1d01) use "OHWI" layout, e.g. [depth_out, filter_height, filter_width, depth_in].

Probably, we could decouple the filter layout and input layout settings. We could rename the current `layout` member of [`Conv2dOptions `](https://webmachinelearning.github.io/webnn/#dictdef-conv2doptions) to `input_layout`. For filter layout setting, we could introduce the `filter_layout` with enum values, e.g. `oihw`, `hwio` and `ohwi`. 

CC+ @pyu10055

**Comment by wchao1115** [comment]
Thanks for the finding @huningxin. Super interesting. Yeah, a separate filter layout enum would allow for more flexibility although I'm not entirely clear from the link to the NNAPI which filter layouts are supported there.

**Comment by huningxin** [comment]
As I read the doc of [ANEURALNETWORKS_CONV_2D](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a34a73b5eaf458b67db5eda71557d1d01), the input 1 is the filter:

> 1: A 4-D tensor, of shape [depth_out, filter_height, filter_width, depth_in], specifying the filter.

**Comment by anssiko** [comment]
Any further work in flight for this issue in addition to #130 that landed?

**Comment by wchao1115** [comment]
I believe we can now close this issue.
