### ISSUE TITLE
WebNN should supports super-resolution models

### ISSUE THREAD

**Issue by wchao1115** [webmachinelearning/webnn#127]
Based on this stated [use case](https://webmachinelearning.github.io/webnn/#usecase-super-resolution) of WebNN, it needs to be able to support the various super-resolution models such as one compiled in this [literature](https://arxiv.org/abs/1902.06068).

**Comment by wchao1115** [comment]
Looks like the current spec should already handle the requirement of the version of the super-resolution model based on the [DirectML super-resolution sample](https://github.com/microsoft/DirectML/tree/master/Samples/DirectMLSuperResolution). The only tricky issue is the lack of ArrayBufferView support for half-precision float (FP16). A popular variant of the super-resolution model runs on FP16 tensors in order to leverage vectorized ML acceleration such as NVIDIA tensor core when available.

Although the lack of FP16 support in the ArrayBufferView could possibly be worked around by just using Uint16Array to appropriately offset the tensor data and deal with the float-casting inside the webnn implementation itself, it could still be confusing to some at the model builder level.

**Comment by huningxin** [comment]
> Although the lack of FP16 support in the ArrayBufferView could possibly be worked around by just using Uint16Array to appropriately offset the tensor data and deal with the float-casting inside the webnn implementation itself, it could still be confusing to some at the model builder level.

There is a related FP16 [discussion](https://github.com/w3c/machine-learning-workshop/issues/64) in the W3C ML workshop.

**Comment by wchao1115** [comment]
Compared with a know super-resolution models, the current webnn operator spec seems sufficient.

**Comment by anssiko** [comment]
@wchao1115 thanks for checking that the spec satisfied the requirements of known super-resolution models.

(I encourage the group participants to open new issues similarly to this if they feel there may be unaddressed requirements derived from model architectures targeting the [use cases](https://webmachinelearning.github.io/webnn/#usecases) documented in the spec. We did updates to the API spec https://github.com/webmachinelearning/webnn/pull/123 in response to a similar assessment for style transfer models. Also new use cases can be brought to the group's consideration by opening a new issue.)
