### ISSUE TITLE
WebNN should support int8 quantized models

### ISSUE THREAD

**Issue by wchao1115** [webmachinelearning/webnn#128]
Supporting int8 quantized models is essential for mobile scenarios and in many NPU architectures. TensorFlow (Lite) and ONNX, for instances, have int8 quantization support built-in, and WebNN should to. Related #93

**Comment by huningxin** [comment]
I think this is important one and support to label as "cr".

**Comment by anssiko** [comment]
We've discussed this feature on our recent meetings:
https://www.w3.org/2022/09/22-webmachinelearning-minutes.html#t05
https://www.w3.org/2022/09/08-webmachinelearning-minutes.html#t05
https://www.w3.org/2022/08/25-webmachinelearning-minutes.html#t06

I will label this issue as "v2" due to required implementation experience for the initial CR inclusion. There's a mechanism for us to publish a [Candidate Recommendation Draft](https://www.w3.org/2021/Process-20211102/#publishing-crud) subsequent to the initial CR that would give us adequate time to properly define, develop and test this feature.

Furthermore, we should soon start discussing WebNN "v2" plan as we look to extend our [current charter](https://www.w3.org/2021/04/web-machine-learning-charter.html) and this feature could be one concrete feature to highlight. We can continue discuss this feature on our bi-weekly calls when there's new information and revise our position as appropriate.

**Comment by inexorabletash** [comment]
It looks like this was added to the spec in 0970115398d82f01e7421057c47afdef9478543c and we may have some implementation experience at this point. Close, despite it being marked v2 ?

**Comment by huningxin** [comment]
The int8 quantized models may need some extra ops, for example `DynamicQuantizeLinear`, `DequantizeLinear`, `ConvInteger` and `MatMulInteger`, that are missed in current spec. 

[Transformer Models Analysis](https://docs.google.com/spreadsheets/d/1ELfHuv2UqP2LoXWLgqsC0L8T_qqfBx48KxzFighl8d8/edit#gid=86906292) spread sheet has more details of ops required by int8 quantized model (see columns marked with (int8)).

@fdwr @Honry

**Comment by fdwr** [comment]
> The int8 quantized models may need some extra ops, for example `DynamicQuantizeLinear`, `DequantizeLinear`, `ConvInteger` and `MatMulInteger`, that are missed in current spec.

Indeed, I have those 4 prototyped here (a minimal first four): https://github.com/fdwr/chromium-src-webnn-dml/pull/1/files#diff-e1b2517a6ae8f7c4494c75d17c8650b56e4f8d430f54f5e1f765475f00a5e1f3R427-R433

**Comment by wacky6** [comment]
Seems int4 quantization is also a thing (with negligible impact on output quality). int4 practically halfs the VRAM requirement of the model, and offers a speedup on devices that support them.

Example of a int4 quantization model: https://huggingface.co/01-ai/Yi-6B-Chat-4bits

Should this be considered for v2? Or is int4 too specific? (I'm not sure if 4bit is adequate for image or audio models)

// There's a more aggressive {-1,0,1} quantization. It's fairly new, and I believe it's application is limited to language models.

**Comment by inexorabletash** [comment]
The BitNet paper was really cool. https://arxiv.org/abs/2310.11453

**Comment by inexorabletash** [comment]
> > The int8 quantized models may need some extra ops, for example `DynamicQuantizeLinear`, `DequantizeLinear`, `ConvInteger` and `MatMulInteger`, that are missed in current spec.
> 
> Indeed, I have those 4 prototyped here (a minimal first four): https://github.com/fdwr/chromium-src-webnn-dml/pull/1/files#diff-e1b2517a6ae8f7c4494c75d17c8650b56e4f8d430f54f5e1f765475f00a5e1f3R427-R433

Hey @fdwr - how fresh is your prototype of these? And have you looked at how other backends (CoreML, TFLite) would implement these? Starting with the "minimum viable" quantization support as outlined in #623 is appealing!

**Comment by fdwr** [comment]
@inexorabletash It's stale moldy bread by now (but snippets could be reused). The [ORT WebNN EP implementation](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/webnn/builders/impl/dequantizeLinear_op_builder.cc) still exists (it was originally added during prototyping) and would light up again once the op is added into Chromium.

> And have you looked at how other backends (CoreML, TFLite) 

There are differences, but they should be expressible (🤞). For dequantization, most decompose to `output = mul(sub(input, zeroPoint), scale)` (except TF full, CoreML MIL's LUT mode, and CoreML's scale&bias form). They have differing broadcasting rules, which I'd like to iron out to be more consistent (consistent with unidirectional broadcasting of its decomposition and `expand`).

API Name | Equation | Types
------------|-----------|------------
TFLite [DequantizeOp](https://www.tensorflow.org/mlir/tfl_ops#tfldequantize_tfldequantizeop) | real = (quantized - zeroPoint) * scale  ([link](https://www.tensorflow.org/lite/performance/quantization_spec)) | **input**: uint8<br/>**zeroPoint**: uint8<br/>**scale**: float32<br/>**output**: float32
TF [tf.quantization.dequantize](https://www.tensorflow.org/api_docs/python/tf/quantization/dequantize) | output = minRange + (input * (maxRange - minRange) / dataTypeRange) | **input**: uint8<br/>**minRange**: float32<br/>**maxRange**: float32<br/>**dataTypeRange**: int<br/>**output**: float32
CoreML MIL [constexpr_affine_dequantize](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS16.constexpr_ops.constexpr_affine_dequantize) | real = (input - zeroPoint) * scale | **input**: uint8, int8<br/>**zeroPoint**: uint8, int8, float32<br/>**scale**: same as output<br/>**output**: float16, float32
CoreML MIL [constexpr_lut_to_dense](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS16.constexpr_ops.constexpr_lut_to_dense) | real = lut[input] | **input**: uint1, uint2, uint4, uint6, uint8<br/>**output**: uint8, int8, float16, float32
CoreML [LinearQuantizationParams](https://apple.github.io/coremltools/mlmodel/Format/NeuralNetwork.html#linearquantizationparams) | ? <i>input * scale + bias</i> ? | **input**: ?<br/>**scale**: float32<br/>**bias**: float32<br/>**output**: ?<br/>
ONNX [DequantizeLinear](https://onnx.ai/onnx/operators/onnx__DequantizeLinear.html) | real = (input - zeroPoint) * scale | **input**: uint4, int4, uint8, int8, uint16, int16, int32, float8e4m3fn, float8e4m3fnuz, float8e5m2, float8e5m2fnuz<br/>**zeroPoint**: same as input<br/>**scale**: same as output<br/>**output**: bfloat16, float16, float32
DML [DEQUANTIZE_LINEAR](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_element_wise_dequantize_linear_operator_desc) | real = (input - zeroPoint) * scale | **input**: uint4, int4, uint8, int8, uint16, int16, uint32, int32<br/>**zeroPoint**: same as input<br/>**scale**: same as output<br/>**output**: float16, float32

**Comment by reillyeon** [comment]
Discussed at the TPAC 2024 F2F. Group consensus was to implement QDQ operators for int8 and int4. Deduplicating with #93.

**Comment by reillyeon** [comment]
Closing this issue. Discussion of quantization operators should continue on #93.
