### ISSUE TITLE
Clarify which view/reshape like function are expected to copy

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#137]
> 6. I see quite a few view/reshape like functions, which of these are expected to copy and which are not? Probably good to note this in the spec.

via https://github.com/w3ctag/design-reviews/issues/570#issuecomment-768875996

To be clarified in the spec, possible implementation details.

**Comment by cynthia** [comment]
https://github.com/webmachinelearning/webnn/pull/144/files/44870dee0271e50ead69da93bf4ef0b9c206537e

Looking at this PR, wouldn't it make sense to define a common term for logical tensor changes (e.g. views?) somewhere early in the document so that concept can be re-used?
