### ISSUE TITLE
NamedOutput mechanism clarification

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#140]
> 10. I don't quite understand the NamedOutput mechanism. What if what is output just a feature?

via https://github.com/w3ctag/design-reviews/issues/570#issuecomment-768875996

@cynthia "What if what is output just a feature?" part needs a clarification?

**Comment by cynthia** [comment]
Yeah, sorry. "What if the output is just a feature?" is what I intended to write. (Not great at speaking and writing at the same time.)

**Comment by huningxin** [comment]
Thanks for the clarification @cynthia !

I agree the [`NamedOutputs`](https://webmachinelearning.github.io/webnn/#typedefdef-namedoutputs) needs more details in the spec. We'll fix that.

Basically, the `NamedOutputs` is just used to index an [`Output` ](https://webmachinelearning.github.io/webnn/#dictdef-output) by string-based name. 

For the case that the output is just a feature, I suppose the feature can be represented by an [`Operand`](https://webmachinelearning.github.io/webnn/#api-operand, then the developer might first need to bind a name to the operand when creating a model, e.g. the following sample code binds name "C" to operand `C`.
```js
// 1. Create a model of the computational graph 'C = 0.2 * A + B'.
const constant = builder.constant(0.2);
const A = builder.input('A', operandType);
const B = builder.input('B', operandType);
const C = builder.add(builder.mul(A, constant), B);
const model = builder.createModel({'C': C});
```

So after computing, the developer can use name "C" to index the output, e.g. by following code
```js
const outputs = await compilation.compute(inputs);
// The computed result of [[1, 1], [1, 1]] is in the buffer associated with
// the output operand.
console.log('Output shape: ' + outputs.C.dimensions);
console.log('Output value: ' + outputs.C.buffer);
```

You can try above code in [WebNN code editor](https://webmachinelearning.github.io/webnn-samples/code/?example=mul_add.js) with webn-polyfill.

Other usages of `NamedOutputs` include:
1. support the pre-allocated buffer for compute, this might be useful for Wasm integration, see [code example](https://webmachinelearning.github.io/webnn-samples/code/?example=preallocated_outputs.js)
2. support optional output by specifying the output name when invoking compute, see [code example](https://webmachinelearning.github.io/webnn-samples/code/?example=optional_outputs.js)

**Comment by huningxin** [comment]
As discussed in [18 Feb CG call](https://www.w3.org/2021/02/18-webmachinelearning-minutes.html#t03), I'll craft a PR to add specific text into the spec and ask for review.
