### ISSUE TITLE
Prefix generic interface names?

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#141]
> 11. A lot of the names are very generic (Operand, Compilation) - this feels like something we might want to prefix with something or synchronize with TC39 about.

via https://github.com/w3ctag/design-reviews/issues/570#issuecomment-768875996

(WebIDL namespaces https://heycam.github.io/webidl/#idl-namespaces for  regular operations and read only regular attributes only.)

**Comment by cynthia** [comment]
I thought a bit about this, and figured it would be worth to be on record stating that prefixing the names with anything that indicates this is only for neural networks is probably not a good idea. (It's a compute graph that can be used for other things too)

**Comment by wchao1115** [comment]
I made a proposal in PR #149 to prefix all WebNN types with "ML", taking a cue from the `ML` attribute off the `Navigator` interface.

**Comment by anssiko** [comment]
For spec archeology purposes, linking https://github.com/heycam/webidl/pull/425 here that added [`[LegacyNamespace]` extended attribute](https://heycam.github.io/webidl/#LegacyNamespace) to WebIDL to allow defining an interface in a namespace. As the "Legacy" in the name suggests, the use of this extended attribute is not encouraged at this time.
