### ISSUE TITLE
Isomorphic JS story, worker scope exposure?

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#142]
> 12. What's the isomorphic JS story for this? Also, given that this is attached to vanilla navigator, is this not expected to work in a worker scope?

via https://github.com/w3ctag/design-reviews/issues/570#issuecomment-768875996

RafaelCintron: 12 is a good issue, should not tie to navigator, good for worker scope as well
… as for the isomorphic part, the degree to which you can use this API, depends on how much Node exposes e.g. WebGL in node

**Comment by cynthia** [comment]
> depends on how much Node exposes e.g. WebGL in node

Alternatively, FFI bindings to an existing framework that already has a compute backend (e.g. CUDA) which is abstracted to expose the same API sounds totally feasible.

**Comment by huningxin** [comment]
Agree, it's possible. And the [webnn-polyfill](https://github.com/webmachinelearning/webnn-polyfill) CPU backend (depends on TF.js CPU backend) already works in Node.js for testing. Further, I believe a node.js binding for the native implementation of webnn ([webnn-native](https://github.com/webmachinelearning/webnn-native), code to be submitted) should also work. However, as the [node_setup.js](https://github.com/webmachinelearning/webnn-polyfill/blob/master/node_setup.js) code shows, we emulate a navigator object in node.js and get the webnn-polyfill and tests run. Probably, we need to bind [`ML`](https://webmachinelearning.github.io/webnn/#api-ml) object according to different JS execution environments. Any suggestions @cynthia ?

**Comment by anssiko** [comment]
Relevant to this issue, [Deno 1.8](https://deno.land/posts/v1.8) adds experimental support for WebGPU API. The project’s goal is to run Tensorflow.js on Deno, with GPU acceleration.

**Comment by anssiko** [comment]
>RESOLUTION: Expose ML interface to Worker scope similarly to WebGPU API

via https://www.w3.org/2021/04/15-webmachinelearning-minutes.html#r02

**Comment by anssiko** [comment]
Noting here #163 makes feasible introducing sync variants of `compile()` and `compute()` in the worker context without blocking the main thread.

@huningxin had some use cases in mind. I think this is worth exploring in a separate issue.
