### ISSUE TITLE
Make WebNN API a policy-controlled feature with default allowlist 'self'

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#145]
[PING review feedback]( https://github.com/webmachinelearning/webnn/issues/119#issuecomment-772565085):

>Is the API restricted to first-party contexts? Or do third-party frames have access? (The answer to 2.13 of the Self-Review: Security and Privacy Questionnaire (above) suggests they do, and that you are exploring the potential of a policy-controlled feature approach.) Is there any reason not to simply restrict to first party context? (i.e. what are the likely use cases you envision that would require third-party frames to have access to the API?)

Discussed on [WebML CG Teleconference – 18 February 2021](https://www.w3.org/2021/02/18-webmachinelearning-minutes.html#t09) with an initial agreement to make WebNN API a [policy controlled feature](https://w3c.github.io/webappsec-permissions-policy/#policy-controlled-feature).

We have additional knobs at our disposal with the [default allowlist](https://w3c.github.io/webappsec-permissions-policy/#default-allowlist) with two possible values:

>`*`
>The feature is allowed in documents in top-level browsing contexts by default, and when allowed, is allowed by default to documents in child browsing contexts.
>`self`
>The feature is allowed in documents in top-level browsing contexts by default, and when allowed, is allowed by default to same-origin domain documents in child browsing contexts, but is disallowed by default in cross-origin documents in child browsing contexts

Per PING feedback I infer we should set the default allowlist to `['self']` that allow same-origin domain iframe elements have access to this API, while disallow by default cross-origin iframe access to this API.

@rafaelcintron @sandandsnow

**Comment by sandandsnow** [comment]
Thank you Anssi for considering our feedback and for proposing solutions to mitigate the privacy vulnerabilities. Restricting access to same-origin domain iframe and disallowing by default cross-original iframe cross-origin access to the API is a good approach.

**Comment by anssiko** [comment]
@sandandsnow, FYI, we just landed your proposed privacy-hardening feature to the Web Neural Network API spec, see #159. Please let us know if you have any further feedback. Thank you for reviewing the WebNN API from privacy perspective.

**Comment by sandandsnow** [comment]
Thank you @anssiko and colleagues
