### ISSUE TITLE
Support `ihwo` filterLayout for `conv2d` op

### ISSUE THREAD

**Issue by Honry** [webmachinelearning/webnn#160]
In [Mobilenet V2 (TFlite)](http://download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224.tgz), its `DepthwiseConv2D` op's weights is of `ihwo` filterLayout, which is not supported in current WebNN spec.

Look at following example, the input of DepthwiseConv2D node is 1x112x112x32 with 'nhwc' layout, its weights is 1x3x3x32, after relu we got its output 1x112x112x32. That means the weights' layout should be 'ihwo'.
![Screenshot (42)](https://user-images.githubusercontent.com/3271201/114118492-7c174a80-991b-11eb-839e-48cd9ef39de3.png)

**Comment by BruceDai** [comment]
Hi @Honry, when I converted DEPTHWISE_CONV2D CTS tests of Android NNAPI, I [transposed filter data]( https://github.com/webmachinelearning/webnn-polyfill/blob/master/test/cts/from_nnapi/test_generator/src/cts_generator.py#L215) and [reshaped filter dimension](https://github.com/webmachinelearning/webnn-polyfill/blob/master/test/cts/from_nnapi/test_generator/src/cts_generator.py#L238).

**Comment by huningxin** [comment]
@Honry and @BruceDai, thanks for the info. It looks like WebNN needs to support `ihwo` filter layout of conv2d. Then it would not need to convert the filter layout when run Android NNAPI DEPTHWISE_CONV2D test case on WebNN.
