### ISSUE TITLE
[admin] Renaming the default branch from master to main

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#177]
To improve our use of inclusive language, and in-line with emerging best practices, W3C is renaming the main branch of its GitHub repositories from `master` to `main` [1][2].

GitHub will perform redirects for web access. Those with local copies and forks will need to update before making pull requests. I suggest we do this rename when our PR queue is empty to save some hassle.

I believe @dontcallmedom has experience in handling this transition smoothly, so I'll assign this to him.

[1] https://lists.w3.org/Archives/Public/spec-prod/2021JanMar/0017.html
[2] https://github.com/github/renaming

**Comment by dontcallmedom** [comment]
renaming now done
