### ISSUE TITLE
Request for HardSwish op

### ISSUE THREAD

**Issue by Honry** [webmachinelearning/webnn#181]
`HardSwish` is an important activation function in MobileNetV3. Both TensorFlow and ONNX have supported it.

**Comment by wchao1115** [comment]
FWIW, hardswish can already be implemented as a composite of existing operations as follow:

`y = x * max(0, min(1, alpha * x + beta)) = x * HardSigmoid<alpha, beta>(x), where alpha = 1/6 and beta = 0.5`

WebNN tries to define operations that are commonly optimized in the underlying OS/hardware layer for increased efficiency. If an operation can already be implemented as a generic composite, it is less compelling to put it in the spec.

**Comment by huningxin** [comment]
Thanks @wchao1115 for providing the composite equation. As we recently have supported [hardSigmoid](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-hard-sigmoid), the composition would be more convenient. 

I also investigated it a bit. As the original [paper](https://arxiv.org/pdf/1905.02244.pdf), it can also be composited by
```
y = x * relu6(x + 3) / 6 = x * clamp(x+3, 0, 6) / 6 = x * max(0, min(6, (x + 3))) / 6
```

According to usage, besides MobileNetV3, it is also be used by Yolov5. Both are the new versions of corresponding ones of the [first-wave models](https://github.com/webmachinelearning/webnn/blob/main/op_compatibility/first_wave_models.md).

From native ML API perspective, both [NNAPI](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0ac88e58ac12cdd6ef3e20d7204ec6f33e) and [OpenVINO](https://docs.openvinotoolkit.org/2021.2/openvino_docs_ops_activation_HSwish_4.html) support hard-swish.

So I suppose it is worth to support it in that spec. It would allow accessing the optimized version in native ML API as well as being composited by small ops that follows the design principal of WebNN spec.

What do you think?
