### ISSUE TITLE
Request for argMax op

### ISSUE THREAD

**Issue by Honry** [webmachinelearning/webnn#184]
`argMax` has been supported in both TensorFlow and ONNX, and which is an important op in [DeepLabV3](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) models, so it'd be great if WebNN could support this op as well.

**Comment by wchao1115** [comment]
and so should `argMin`.

**Comment by inexorabletash** [comment]
Can this be closed now that PR #478 has merged?

**Comment by fdwr** [comment]
Yep, should be closed now that argMin and argMax are in.
