### ISSUE TITLE
Define set of exceptions for WebNN API

### ISSUE THREAD

**Issue by jvenkatn** [webmachinelearning/webnn#19]
WebNN API would need exception handlers which report appropriate error status for an API (other than the default JavaScript runtime exceptions).
These exceptions would be used by developers to catch specific states of error in WebNN API.

**Comment by anssiko** [comment]
This issue has been addressed. The specification currently throws one of the following in applicable places:

"NotSupportedError" DOMException
"SecurityError" DOMException
"OperationError" DOMException
"DataError" DOMException

The WG believes this provides an appropriate level of detail without disclosing too much information to become a privacy issue.

Thanks for filing this issue!
