### ISSUE TITLE
There is a spelling error in "during the model training phrase"

### ISSUE THREAD

**Issue by fujunwei** [webmachinelearning/webnn#194]
Does it means "during the model training `phase`" describing in [instanceNormalization](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-instancenorm) and [batchNormalization](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-instancenorm)?

And is the "[=======](https://github.com/webmachinelearning/webnn/blob/main/index.bs#L474)" delimiter not required?
![Capture2](https://user-images.githubusercontent.com/7856909/125877914-3bbbd76b-07a4-4a98-95d3-74845ba48ff8.PNG)

**Comment by anssiko** [comment]
I believe this is fixed by #195 (thanks @huningxin!).
