### ISSUE TITLE
Support for configuring rounding type in pooling operations

### ISSUE THREAD

**Issue by MarkGHX** [webmachinelearning/webnn#198]
Hi all, 

I'm a student intern working on GSoC 2021 project "OpenCV.js: Accelerate OpenCV.js DNN via WebNN" (opencv/opencv#20406). [Here](https://docs.google.com/document/d/18PcYuRC2UCKUpustZn3t8beDF1UNfP29ikwPLPKXFuY/edit) is the proposal. In this project, I will improve the performance of OpenCV.js DNN Module using WebNN.

However, when I am implementing OpenCV pooling layer with WebNN backend, I found that OpenCV's pooling layer supports both ceil (with ```ceilMode``` flag) and floor rounding type in https://github.com/opencv/opencv/blob/e9db7fea5b793bbe30ebf730130db24cc29267ea/modules/dnn/include/opencv2/dnn/all_layers.hpp#L255 
and https://github.com/opencv/opencv/blob/e9db7fea5b793bbe30ebf730130db24cc29267ea/modules/dnn/src/layers/pooling_layer.cpp#L145. 

And through the preliminary investigation, ONNX pooling also supports both [ceilMode and floorMode](https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-2). 

However, in WebNN pooling spec, we do not support configuring the rounding type in pooling operations. We defaultly use floor rounding type. According to the investigation, both Alexnet and GoogleNet-v1 use ceil rounding type while in the ONNX layer tests, floor rounding type is used. In this case, it is useful to let WebNN pooling spec support configuring rounding type.

**Comment by huningxin** [comment]
@MarkGHX , thanks for integrating WebNN into OpenCV.js dnn framework and sharing with us this feedback.

According to my investigation, it looks like the pooling ops of DirectML (e.g. [DML_AVERAGE_POOLING_OPERATOR_DESC](https://docs.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_average_pooling_operator_desc)) and NNAPI (e.g. [ANEURALNETWORKS_AVERAGE_POOL_2D](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a12e6b53aadbd3736c38f1a159adea788)) don't support rounding mode. Given ONNX supports this feature, I am wondering how DirectML execution provider of ONNXRuntime support that? @wchao1115 , do you have any insights?

**Comment by wchao1115** [comment]
The `ceil_mode` param in ONNX is used as a way to explicitly control how to round the output size of the pooling operation. This is a policy that is typically implemented in the frameworks. DirectML API requires that an output tensor description is provided explicitly so the framework must first compute the output size according to its policy before passing the calculated output size to DirectML. This is why the DirectML API doesn't need this flag (and other high-level policy settings for that matter). 

As for webnn, I can see that the way we currently define our pooling operation is less clear on how to round the calculated output size. We could adopt the way `conv2d` solves this by adding an optional `outputSizes` param to pooling. This way if the output size is explicitly supplied, we'll use it and if not, it would define a default rounding mode to avoid ambiguity. 

As an example, [here](https://github.com/microsoft/onnxruntime/blob/127b1f0d01c4e255e5f1f076fd487ddca4fad220/onnxruntime/core/providers/dml/OperatorAuthorHelper/OperatorHelper.cpp) is how ONNX Runtime calculates the output size according to the specified ceil mode for DirectML. Search for `InitializeKernelOutputDimensions` within this source file.

**Comment by huningxin** [comment]
Thanks @wchao1115 for sharing. It is very helpful, especially for the details of `InitializeKernelOutputDimensions`.

> As for webnn, I can see that the way we currently define our pooling operation is less clear on how to round the calculated output size.

+1. We need to specify it.

> We could adopt the way `conv2d` solves this by adding an optional `outputSizes` param to pooling. This way if the output size is explicitly supplied, we'll use it and if not, it would define a default rounding mode to avoid ambiguity.

I would propose to support `RoundingType` with enum value "floor" and "ceil". In that way, the caller could map the framework configuration directly. The caller may not be able to know the input shape (if it is an intermediate value) and calculate the output shape with desired rounding type by itself, because WebNN doesn't allow query operand shape.

**Comment by wchao1115** [comment]
> According to my investigation, it looks like the pooling ops of DirectML (e.g. [DML_AVERAGE_POOLING_OPERATOR_DESC](https://docs.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_average_pooling_operator_desc)) and NNAPI (e.g. [ANEURALNETWORKS_AVERAGE_POOL_2D](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a12e6b53aadbd3736c38f1a159adea788)) don't support rounding mode. Given ONNX supports this feature, I am wondering how DirectML execution provider of ONNXRuntime support that? @wchao1115 , do you have any insights?

The caller of DirectML must specify the descriptions of the operator's input and output tensors, which include the tensor shapes. So, the ONNX `ceil_mode` treatment occurs in the ONNX runtime framework above DirectML.
