### ISSUE TITLE
Request input layout and resize only on height and width for Resample

### ISSUE THREAD

**Issue by fujunwei** [webmachinelearning/webnn#200]
OpenVINO only [support NHWC layout and resize on height and width for rank 4](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/mkldnn_plugin/nodes/mkldnn_interpolate_node.cpp#L2047).

And NNAPI support only height and width of the output tensor and has  [the optional of "NHWC" or "NCHW" data layout](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a42bd92518e273b6716ecd56b571fcd3e) .

**Comment by BruceDai** [comment]
I'm converting native Android NNAPI CTS for WebNN polyfill tests of resample op. 
In Android NNAPI Spec, there're two similar function ops [ANEURALNETWORKS_RESIZE_BILINEAR](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a42bd92518e273b6716ecd56b571fcd3e) and [ANEURALNETWORKS_RESIZE_NEAREST_NEIGHBOR](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a633997ea5224dc4063d35b9f2b2ab84b) which could resize input tensor both by shape and by scale, detail descriptions are as following:

```spec
Inputs (resizing by shape):
0: A 4-D tensor, of shape [batches, height, width, depth], specifying the input. Zero batches is supported for this tensor.
1: An ANEURALNETWORKS_INT32 scalar, specifying the output width of the output tensor.
2: An ANEURALNETWORKS_INT32 scalar, specifying the output height of the output tensor.
3: An ANEURALNETWORKS_BOOL scalar, default to false. Set to true to specify NCHW data layout for input0 and output0.
4: Align corners. An optional ANEURALNETWORKS_BOOL scalar, default to false. If True, the centers of the 4 corner pixels of the input and output tensors are aligned, preserving the values at the corner pixels.
5: Half pixel centers. An optional ANEURALNETWORKS_BOOL scalar, default to false. If True, the pixel centers are assumed to be at (0.5, 0.5).

Inputs (resizing by scale):
0: A 4-D tensor, of shape [batches, height, width, depth], specifying the input. Zero batches is supported for this tensor.
1: A scalar, specifying width_scale, the scaling factor of the width dimension from the input tensor to the output tensor. The output width is calculated as new_width = floor(width * width_scale). The scalar must be of ANEURALNETWORKS_FLOAT16 if input0 is of ANEURALNETWORKS_TENSOR_FLOAT16 and of ANEURALNETWORKS_FLOAT32 otherwise.
2: A scalar, specifying height_scale, the scaling factor of the height dimension from the input tensor to the output tensor. The output height is calculated as new_height = floor(height * height_scale). The scalar must be of ANEURALNETWORKS_FLOAT16 if input0 is of ANEURALNETWORKS_TENSOR_FLOAT16 and of ANEURALNETWORKS_FLOAT32 otherwise.
3: An ANEURALNETWORKS_BOOL scalar, default to false. Set to true to specify NCHW data layout for input0 and output0.
4: Align corners. An optional ANEURALNETWORKS_BOOL scalar, default to false. If True, the centers of the 4 corner pixels of the input and output tensors are aligned, preserving the values at the corner pixels. 
5: Half pixel centers. An optional ANEURALNETWORKS_BOOL scalar, default to false. If True, the pixel centers are assumed to be at (0.5, 0.5).

Outputs:
0: The output 4-D tensor, of shape [batches, new_height, new_width, depth]. 
``` 

Besides input layout and height and width of sizes/scales, resample spec maybe also need consider of ‘Align corners’ and 'Half pixel centers' options, thanks.

**Comment by huningxin** [comment]
@fujunwei and @BruceDai , thanks for the feedback from implementation and test perspectives. It looks like you are requesting the `Resample2d` op that takes a 4-D tensor with layout information (nchw or nhwc) and only supports interpolation on spatial dimensions (h and w). Given OpenVINO and NNAPI only support resampling on spatial dimension, it seems make sense to me.

I am not sure about how DML resample supports  ‘Align corners’ and 'Half pixel centers', @wchao1115 , any inputs?

**Comment by wchao1115** [comment]
> I am not sure about how DML resample supports ‘Align corners’ and 'Half pixel centers', @wchao1115 , any inputs?

@huningxin [`DML_RESAMPLE1_OPERATOR_DESC`](https://docs.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_resample1_operator_desc) supports the additional input and output pixel offsets so that the framework caller can have a fine-grained control over how the corner pixel and centering is implemented. Take a look at the DmlOperatorResize class on how these extra pixel offset controls are used in the ONNX Runtime [here](https://github.com/microsoft/onnxruntime/blob/93e93d085137aeee5035da6cd319ebc2c3427547/onnxruntime/core/providers/dml/DmlExecutionProvider/src/Operators/DmlOperatorResize.cpp).
