### ISSUE TITLE
Change the min and max value to attributes instead of operands

### ISSUE THREAD

**Issue by mingmingtasd** [webmachinelearning/webnn#203]
The Clamp's option in spec is as below:
```
dictionary MLClampOptions {
  MLOperand minValue;
  MLOperand maxValue;
}; 
```
This definition is not friendly for implementing Clamp in many backends, such as [OpenVINO](https://docs.openvinotoolkit.org/latest/openvino_docs_ops_activation_Clamp_1.html), [DML](https://docs.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_element_wise_clip_operator_desc) and [ONNX](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Clip). These backends all define Clamp's min/max as a float scalar rather than a node.

**Comment by huningxin** [comment]
Thanks for the implementation feedback, @mingmingtasd . I guess what you are proposing is to change the min and max value to attributes instead of operands. For example
```
dictionary MLClampOptions {
  float minValue;
  float maxValue;
}; 
```

Is my understanding correct?

**Comment by mingmingtasd** [comment]
> Thanks for the implementation feedback, @mingmingtasd . I guess what you are proposing is to change the min and max value to attributes instead of operands. For example
> 
> ```
> dictionary MLClampOptions {
>   float minValue;
>   float maxValue;
> }; 
> ```
> 
> Is my understanding correct?

Yes, that's right! Thanks!
