### ISSUE TITLE
reduceLogSum, reduceLogSumExp, reduceSumSquare are not supported on OV/NNAPI

### ISSUE THREAD

**Issue by mingmingtasd** [webmachinelearning/webnn#209]
I find that for these three reducution ops: 

**reduceLogSum, reduceLogSumExp, reduceSumSquare**

DMl/ONNX can support them while OV/NNAPI can't support them.

**Comment by wchao1115** [comment]
@mingmingtasd They can all be emulated though e.g. `reduceLogSum` would an element-wise log over a reduce-sum operation. Likewise `reduceSumSquare` would be a reduce-sum over an element-wise square operation. 

The design goal of webnn is not to build a one-to-one mapping to each and every popular framework or platform API, as that would be impossible to achieve. The goal is to define a core set of operations that can be accelerated by the platform API when that acceleration is available while at the same time allowing the frameworks to be built on top of it without translation discrepancy or overhead.

**Comment by mingmingtasd** [comment]
> @mingmingtasd They can all be emulated though e.g. `reduceLogSum` would be an element-wise log over a reduce-sum operation. Likewise `reduceSumSquare` would be a reduce-sum over an element-wise square operation.
> 
> The design goal of webnn is not to build a one-to-one mapping to each and every popular framework or platform API, as that would be impossible to achieve. The goal is to define a core set of operations that can be accelerated by the platform API when that acceleration is available while at the same time allowing the frameworks to be built on top of it without translation discrepancy or overhead.

Yes, good explanation for this issue which I raised here for disscusion, I agree with you, thanks a lot! @wchao1115

**Comment by anssiko** [comment]
@mingmingtasd thanks for raising this issue, and thanks @wchao1115 for explaining the design goal of the API.

We discussed this on our call https://www.w3.org/2021/09/30-webmachinelearning-minutes.html#t04 and agreed to add an informative section to the [reduction operations](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-reduce) with pseudo-code on how reduceLogSum, reduceLogSumExp and reduceSumSquare ops could be emulated. See "The behavior of this operation can be generically emulated" for other similar examples in the spec.

We hope that will addresses this issue and also helps other readers of the spec who might have similar questions.

**Comment by inexorabletash** [comment]
Flagging as https://github.com/webmachinelearning/webnn/labels/editorial per conversation in https://github.com/webmachinelearning/webnn/issues/209#issuecomment-931974186 which says that the planned resolution is to provide the decomposition for the ops in question.
