### ISSUE TITLE
Define algorithms for dictionaries with lists as default values

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#211]
Via @domenic https://github.com/webmachinelearning/webnn/pull/204/files#r703625252

> You need to have a normative algorithm which checks if input["scales"] exists, and if not, use the defaults. I.e. something like
> 
> Let scales be the [list](https://infra.spec.whatwg.org/#list) « 1.0, 1.0, 1.0, 1.0 ».
> If input["scales"] exists, then set scales to input["scales"].
> 
> (and maybe also validate that input["scales"] is of length 4, or whatever you need?)
> 
> This seems difficult since right now your spec has no algorithms (i.e. no [method steps](https://heycam.github.io/webidl/#method-steps)) for its operations, just a non-normative description of the inputs and return value.

We should make this a global update to all affected dictionaries. We probably want to define a reusable algorithm we reference from all these places.

Given this issue is specific to dictionaries with list defaults, for "method steps" convention in general, I opened https://github.com/webmachinelearning/webnn/issues/210

**Comment by inexorabletash** [comment]
This is mostly taken care of by 0fe9e5ca0891bc79a882a153c682be94ae63b580 and prior changes, albeit with slightly different wording than suggested by @domenic

Suggested:
> Let scales be the list « 1.0, 1.0, 1.0, 1.0 ».
> If input["scales"] exists, then set scales to input["scales"].

Current:
> If options.padding does not exist, set it to « 0, 0, 0, 0 ».

Differences:
* Literal list syntax « 0, 0, 0, 0 » is used without "the list" prefix (linked to the Infra definition) - I missed this!
* Dictionary member syntax - see https://github.com/webmachinelearning/webnn/issues/450#issuecomment-1681830276 for some discussion
* Unpacking to a local variable vs. mutating the dictionary. Either is fine; while the latter looks like it would modify the passed JS object but the WebIDL processing model means that doesn't happen. In most cases in the spec an  _options_ dict is passed verbatim to _"... an implementation-defined platform operator for the ..., given options."_  (see https://github.com/webmachinelearning/webnn/issues/462 for some thoughts)

I'll put up a PR for the "the list" wording change, after that perhaps this can be closed?

**Comment by zolkis** [comment]
> I'll put up a PR for the "the list" wording change, after that perhaps this can be closed? 

I like the most compact formulation, which simplifies reading of a long algorithm: 

> If options.padding does not exist, set it to the list « 0, 0, 0, 0 ».

But I get the logic in Domenic's suggestion, especially when used in a shorter algorithm. However, when there are repetitions, IMHO the more compact version is far more readable.

**Comment by inexorabletash** [comment]
`layerNormalization()` still has `axes` that have "assumed to be [1,2,3]" but nothing in the algorithm. I'll file a PR for that.

**Comment by inexorabletash** [comment]
Testing: @webmachinelearning/triage folks should review and consider closing this after the above PR merges

**Comment by inexorabletash** [comment]
I claim this can be closed now, so I'm gonna do it. New bugs if we missed any cleanup, please!
