### ISSUE TITLE
Consider dilation parameter for calculating conv2d output shape

### ISSUE THREAD

**Issue by mingmingtasd** [webmachinelearning/webnn#222]
According to the [conv2d definition](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-conv2d) in spec, output shape will be calculated by this formula:
`output size = 1 + (input size - filter size + beginning padding + ending padding) / stride`
But the paramter `dilations` will also has impact on the shape. The formula may need to be modified as:

`dilated filter size = dilations * (filter size - 1) + 1`
`output size = 1 + (input size - dilated filter size + beginning padding + ending padding) / stride`

**Comment by huningxin** [comment]
Thanks @mingmingtasd , you are right, the `dilations` should be considered when calculating the output shape. 

The implementations may vary, but here are usually `dilations - 1` spaces inserted between filter kernel elements. So the "effective filter size" would be

```
effective filter size = filter size + (filter size - 1) * (dilations - 1)
```

So when dilation = 1 (the default value), the effective filter size equals to filter size.

It actually equals your formula for "dilated filter size".

This would also impact the convTranspose2d, as we split it from conv2d recently. I'll fix them in one PR.

**Comment by mingmingtasd** [comment]
Should we consider dilation for pooling operations since outputSize has been added into the options? @huningxin
