### ISSUE TITLE
Use tensor type for the padding rather than MLOperand

### ISSUE THREAD

**Issue by mingmingtasd** [webmachinelearning/webnn#224]
The pad in the [spec](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-pad) uses the `MLOperand padding` as its sencond input. But I find that the pad in [DML](https://docs.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_padding_operator_desc) and in [IE](https://docs.openvino.ai./latest/openvino_docs_ops_movement_Pad_1.html), padding was defined with a tensor type. I think it's better to use tensor type to avoid the gap between spec and implementation.

**Comment by huningxin** [comment]
As feedback of [WebML WG Teleconference – 18 Nov 2021](https://www.w3.org/2021/11/18-webmachinelearning-minutes.html#t02), the static attribute is preferred, e.g. @wchao1115  mentioned

> <Chai> +1 on prefer static, dynamism breaks accelerator's pipelining

Another reference is TensorFlow.js, according to [tf.pad](https://js.tensorflow.org/api/latest/#pad), the `paddings` is also an array.

With that, I propose to change the `padding` input of WebNN's [pad](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-pad) to an array and move it into `MLPadOptions`.

@mingmingtasd , I am not sure whether it aligns with your proposal. What do you mean by using "tensor type"?

**Comment by mingmingtasd** [comment]
> As feedback of [WebML WG Teleconference – 18 Nov 2021](https://www.w3.org/2021/11/18-webmachinelearning-minutes.html#t02), the static attribute is preferred, e.g. @wchao1115 mentioned
> 
> > +1 on prefer static, dynamism breaks accelerator's pipelining
> 
> Another reference is TensorFlow.js, according to [tf.pad](https://js.tensorflow.org/api/latest/#pad), the `paddings` is also an array.
> 
> With that, I propose to change the `padding` input of WebNN's [pad](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-pad) to an array (sequence in WebIDL).
> 
> @mingmingtasd , I am not sure whether it aligns with your proposal. What do you mean by using "tensor type"?

Yes, that aligns with what I mean: using array. Thanks! @huningxin

**Comment by huningxin** [comment]
@mingmingtasd , as @wchao1115 's [feedback](https://github.com/webmachinelearning/webnn/pull/233#discussion_r789388657), DirectML is supporting dynamic padding data. And NNAPI [ANEURALNETWORKS_PAD_V2](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0afe2c4f9e541dcc278509921fd2c8a502) also supports padding data as an operand. So it looks like the current pad op definition of WebNN is more future-proof. 

With that, I would withdraw my proposal and keep the current version. WDYT?

**Comment by mingmingtasd** [comment]
> @mingmingtasd , as @wchao1115 's [feedback](https://github.com/webmachinelearning/webnn/pull/233#discussion_r789388657), DirectML is supporting dynamic padding data. And NNAPI [ANEURALNETWORKS_PAD_V2](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0afe2c4f9e541dcc278509921fd2c8a502) also supports padding data as an operand. So it looks like the current pad op definition of WebNN is more future-proof.
> 
> With that, I would withdraw my proposal and keep the current version. WDYT?

Yes, I agree, thanks for your explaination. @huningxin

**Comment by huningxin** [comment]
Thanks for the feedback @mingmingtasd ! I'll close PR #233 and this one.
