### ISSUE TITLE
How to handle backwards compatibility for operation definitions

### ISSUE THREAD

**Issue by gregwhitworth** [webmachinelearning/webnn#23]
In issue #17 the issue of how we'll be handling versioning was brought up. ONNX currently has a way in which to handle versioning but the web rarely has versioning of APIs (they normally are frozen forever), that doesn't mean it isn't possible but something we should investigate and come up with a solution for since we know there are reasons for these operations to evolve.

**Comment by anssiko** [comment]
I managed to duplicate this issue (sorry!) and sent out coordinates to the duplicate issue in the minutes, so I'll migrate your comment over to #24.
