### ISSUE TITLE
 Include content filtering as use case

### ISSUE THREAD

**Issue by humeranoor** [webmachinelearning/webnn#236]
Hi everyone,
This is Dr. Humera Noor Minhas, Machine Learning Engg. Lead at [eyeo](https://eyeo.com/), the company behind the browser extension Adblock Plus. 

We have been working on **machine learning-based content filtering**; and realise that there is a gap when it comes to web standards for supporting content blocking and filtering.

Content filtering is used by hundreds of millions of people all across the internet. They are important for applications like ad blocking (by web extensions using web technology), web accessibility and privacy etc. 

We presented [Eyeo’s initial proposal on Machine Learning on the Web for content filtering applications](https://www.w3.org/2020/06/machine-learning-workshop/talks/machine_learning_on_the_web_for_content_filtering_applications.html)  last year at the W3C Machine Learning Workshop, with solutions that we developed internally. However, for the overall benefit of the internet users in general and web machine learning community in particular,  we believe that there is a need to have content-filtering listed as one of the use cases in the WebNN spec.

With this message, we want to re-initiate the discussion and propose to include content filtering as one of the standard [WebNN use cases](https://webmachinelearning.github.io/webnn/#usecases-application). If you have no objections, I will create a Pull request to the [WebNN repository](https://github.com/webmachinelearning/webnn) as a next step.

Looking forward to your suggestions.

Best,
Humera

**Comment by anssiko** [comment]
Thank you for your continued contributions and for proposing this use case. We’re in particular welcoming use cases that demonstrate ethical use of ML and this use case could be one such example framed accordingly.

Please submit a PR and we’ll review and discuss your contribution on our upcoming bi-weekly calls. Thanks!

**Comment by dontcallmedom** [comment]
moved to https://github.com/webmachinelearning/proposals/issues/4
