### ISSUE TITLE
The baseline implementation of WebNN ops

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#245]
To establish the baseline of WebNN conformance test and answer the requirements raised in [WebML WG Teleconference – 2 Dec 2021](https://www.w3.org/2021/12/02-webmachinelearning-minutes.html#t03), including

by @wchao1115 
> all computation is done in double precision
> we don't want any intermediate casting
> an open source ref, anyone can look at the code and be confident

by @dontcallmedom 
> the codebase should be easy to review, not too many layers of abstraction

I would propose to create a baseline implementation of WebNN ops that:
- Uses JavaScript double precision calculation
- Uses plain algorithm without depending on third-party library
- Hosts on group repo, such as https://github.com/webmachinelearning/webnn-baseline

I have been working with @BruceDai on a staging repo: https://github.com/huningxin/webnn-baseline, with some initial ops, like [conv2d](https://github.com/huningxin/webnn-baseline/blob/main/src/conv2d.js). If it looks like a right approach, we are happy to contribute it to the group repo for wider review.

/cc @anssiko @wchao1115 @dontcallmedom

**Comment by huningxin** [comment]
As this is for w-p-t, mark it with 'cr'.

**Comment by anssiko** [comment]
Initial implementation: https://github.com/webmachinelearning/webnn-baseline/pull/1
