### ISSUE TITLE
Privacy considerations for cached/persisted data

### ISSUE THREAD

**Issue by krgovind** [webmachinelearning/webnn#254]
[Leaving feedback on behalf of Chrome privacy reviewers]

Does the API result in any data bring cached/persisted in the browser, or by the hardware accelerators? For example, do you have any compilation caches similarly to [WebGL/WebGPU shaders](https://gpuweb.github.io/gpuweb/#privacy-user-agent-state)?

- Any new cache/storage should be partitioned as per [storage partitioning](https://github.com/privacycg/storage-partitioning) work that is currently underway in browsers.
- Deletion operations (e.g. when a user clears site data in the browser) should be defined for such data.

**Comment by anssiko** [comment]
@krgovind thanks for bringing this privacy issue to our attention. We're tracking this issues as part of the wide review https://github.com/webmachinelearning/webnn/issues/239.

**Comment by RafaelCintron** [comment]
@krgovind , the WebNN spec does not support custom shaders authoring by web developers like WebGL and WebGPU do. Instead, you assemble pre-existing shaders and lower level primitives that come with the browser or the underlying OS.  It behaves more like features such as CSS filters, 2D canvas, SVG path drawing, gradients, font rendering, etc. Unless I am missing something, I don't see these features in the lists you linked.  If there are efforts to partition these, I'd like to learn more about that.

**Comment by krgovind** [comment]
@RafaelCintron - We are not aware of cross-site caches for CSS filters, 2D canvas, SVG path drawing, gradients, font rendering, etc.; but please let us know if you are aware of global caches that need to be considered for partitioning.

Thank you for confirming that WebNN does not support custom shaders. In that case, I'd recommend documenting under the Privacy Considerations section that no associated caches, or persisted data is associated with the API; and close this issue.
