### ISSUE TITLE
Attempt to use single words in enums if possible

### ISSUE THREAD

**Issue by kenchris** [webmachinelearning/webnn#267]
``` 
enum MLPowerPreference {
  "default",
  "high-performance",
  "low-power"
};
```

Like the above could very well use "performance" and "efficiency" instead. Also, I think it is more common to use "auto" (up to the platform) that "default". "auto" also better reflects that it might change depending on system settings instead of "default" that sounds like a fixed value

**Comment by anssiko** [comment]
Thanks for your comment. This topic is discussed in https://github.com/webmachinelearning/webnn/issues/169. Please migrate this comment to that issue as appropriate.

**Comment by anssiko** [comment]
@kenchris thanks for migrating your comment to #169. I'll close this issue and we'll continue in there.
