### ISSUE TITLE
RfC: drop WebGL interoperability requirements

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#268]
We discussed [WebGPU and WebGL interop expectations](https://www.w3.org/2022/05/19-webmachinelearning-minutes.html#t07) on our call today and it was proposed we should consider dropping WebGL interoperability requirements from the specification.

Currently, the spec takes a normative dependency on WebGL spec through:
- [`WebGLBuffer`](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.4)
- [`WebGLRenderingContext`](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.14)
- [`WebGLTexture`](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.9)

The rationale for including WebGL interop is historical. When the WebNN API spec work started, there was little to no WebGPU implementation experience and many aspects of the spec unspecified. Back then, WebGL was the only API shipping to interface with GPUs.

Please provide your feedback in this issue. Hearing no concerns, I'll ask the editors to start the process to remove this dependency from the specification. I'll also label this as "cr" because it is important to get a decision on this by the time we release a CR (preferably sooner).

**Comment by wchao1115** [comment]
Unless there is a use case that still depends on WebGL interop, I'm inclined to agree that not carrying legacy requirement greatly simplifies the implementation and tends to lower the adoption barrier for the Web standard.

**Comment by anssiko** [comment]
@wchao1115 @huningxin feel free to proceed with the required specification changes per our resolution made [2022-06-02](https://www.w3.org/2022/06/02-webmachinelearning-minutes.html#r01).
