### ISSUE TITLE
Reshape doesn't support full range of operand dimension size

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#289]
According to #281 , now the [`MLOperandDescriptor.dimensions`](https://www.w3.org/TR/webnn/#api-mloperanddescriptor) is of type `sequence<unsigned long>` with supported dimension size range `[1, 4294967295]`. However, the [`reshape`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-reshape) op still supports the `newShape` of type `sequence<long>`. Except the special value `-1` for shape inference, the supported dimension size range is `[1, 2147483647]`. The user code is not able to reshape a tensor to a new shape with dimension size in the range `(2147483647, 4294967295]`. 

Thanks @wacky6 for raising this issue in [Chromium CL review](https://chromium-review.googlesource.com/c/chromium/src/+/3866751/comments/a02835ac_0fc1ae53).

**Comment by wacky6** [comment]
Looks like `-1` really means caller "don't know / don't care".

Perhaps using `null` instead of -1 is a better choice (since JS Array isn't typed and can include mixed types).

FYI, Torch / TF uses `None` to indicate such a dimension.

**Comment by huningxin** [comment]
> Perhaps using `null` instead of -1 is a better choice (since JS Array isn't typed and can include mixed types).

Great idea, thanks @wacky6 . 

Based on your idea, I would propose to define the type of `newShape` to `sequence<unsigned long?>`. So the new dimension value could be either `unsigned long` without loss the range or `null` for "don't know / don't care / please infer". 

I'll make a PR based on that.

**Comment by wacky6** [comment]
Conceptually `null` SGTM. But Blink's IDL generator might not do what you want, there can be edge-cases.

`sequence<unsigned long>` and/or `sequence<unsigned long?>` coerces arguments into a uint32. Unsure if this is a bug in IDL generator.

Some examples (non-exhaustive):

| Input | Blink C++ `sequence<unsigned long>` | Blink C++ `sequence<unsigned long?>` | 
|-|-|-|
`[1,null,3]` | `[1,0,3]` | `[1,absl::nullopt,3]`
`[1,undefined,3]` | `[1,0,3]` | `[1,absl::nullopt,3]`
`[1,false,3]` | `[1,0,3]` | `[1,0,3]`
`[1,"123",3]` | `[1,123,3]` | `[1,0,3]`
`[1,"x",3]` | `[1,0,3]` | `[1,0,3]`
`[1,{"a":"b"},3]` | `[1,0,3]` | `[1,0,3]`

If we want strict type checking, we probably need to use `sequence<any>`, then check types of each element in C++.

But, this being JavaScript, perhaps the coercion is fine considering null/undefined are passed correctly using `unsigned long?` and 0 is an invalid option.

**Comment by huningxin** [comment]
Thanks much @wacky6  for the great details!

It's great to see Blink C++ would get `absl::nullopt` for null/undefined. That would be very helpful for implementers. 

> But, this being JavaScript, perhaps the coercion is fine considering null/undefined are passed correctly using unsigned long? and 0 is an invalid option.

+1. The JavaScript value coercion to IDL `unsigned long` is [defined](https://webidl.spec.whatwg.org/#es-unsigned-long) by WebIDL spec where [`ToNumber`](https://tc39.es/ecma262/#sec-tonumber) is used to coerce different argument types to `Number`.

One minor clarification question, would the input `[1,"123",3]` coerces to Blink C++ as `[1, 0, 3]` or `[1, 123, 3]` if the type is defined as `sequence<unsigned long?>`? It coerces to `[1, 123, 3]` for `sequence<unsigned long>`.

**Comment by wacky6** [comment]
Ooops. Should be `[1, 123, 3]`. Fixed my typo in comment :)
