### ISSUE TITLE
MLOperandDataType naming recommendation

### ISSUE THREAD

**Issue by fdwr** [webmachinelearning/webnn#299]
"operand type" as a name is ambiguous (it means many potential things, like whether the operand is an input, output, map, tensor, sequence...) and inconsistent with other existing frameworks:

- TensorFlow Data Types https://www.tensorflow.org/api_docs/python/tf/dtypes
- TensorFlow.js Data Types - https://js.tensorflow.org/api/latest/#tensor
- NumPy Data Types https://numpy.org/doc/stable/user/basics.types.html
- PyTorch Data Types https://pytorch.org/docs/stable/tensor_attributes.html#torch-dtype
- ONNX Tensor Element Types https://github.com/onnx/onnx/blob/main/docs/IR.md#tensor-element-types

For example, in ONNX, the *type of an operand* can be:

- dense tensors
- sparse tensors
- sequence
- map
- optional

But these operand types can have subtypes, including (for tensors dense/sparse) element data type. So the name `MLOperandDataType` would make it consistent with precedent.

**Comment by huningxin** [comment]
Thanks @fdwr .

+1 to `MLOperandDataType` which is more accurate and consistent for its meaning.

BTW, we may use operand type (or operand kind) to indicate operand created by different methods, like `input()`, `constant()` or output of an operation build method, such as `conv2d()`. The operand kind is implemented as internal slot of `MLOperand` in the [Chromium prototype](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/ml/webnn/ml_operand.h;l=26?q=ml_operand.h&ss=chromium).

**Comment by inexorabletash** [comment]
This can be closed since c6ed2ca961c7f21390bf0d9c45fc69bfe4ea0732 has landed.
