### ISSUE TITLE
The type of sizes defined in MLResample2dOptions should be unsigned long

### ISSUE THREAD

**Issue by lisa0314** [webmachinelearning/webnn#300]
As the sizes defined in MLResample2dOptions represent target sizes for each spatial dimensions of input, [size_height, size_width].  The type of sizes should align with the type of input dimensions.

**Comment by huningxin** [comment]
Thanks @lisa0314 . This issue was raised in the [Chromium CL review](https://chromium-review.googlesource.com/c/chromium/src/+/4062420). I'll make a PR to fix it.

/cc @wacky6
