### ISSUE TITLE
Review sync vs async compute differences

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#316]
@huningxin @wchao1115  please check these, I have some questions.
I am working on a PR to improve the steps for async and sync execution.

I noticed the following opportunities/differences:
- Inputs and their validation is the same in both, so it can be factored out and referred from both (done).
- The async steps currently are not really asynchronous. Also, they throw from a parallel job, so I assume that needs (minor) fixing (done).
- There is only one difference between the sync and async steps (excluding promise-related): the async version compares the byte length of |outputTensor| with the length of the output descriptor corresponding to |key|, whereas the sync version compares the same with the byte length of |value|. If that is deliberate, we need an editor's note on why so - please point me to relevant background there.

**Comment by zolkis** [comment]
Looks like in the implementations, [MLGraphXnnpack::InvokeRuntime()](third_party/blink/renderer/modules/ml/webnn/ml_graph_xnnpack.cc) and [MLGraph::ComputeRequest::ComputeRequest](third_party/blink/renderer/modules/ml/webnn/ml_graph.cc) is used for both sync and async execution, so the algorithm can be the same for sync vs async, but the steps might need to be revisited.

**Comment by huningxin** [comment]
For the current implementation, [`MLGraph::ComputeAsync()`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/ml/webnn/ml_graph.cc;l=84) and [`MLGraph::ComputeSync()`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/ml/webnn/ml_graph.cc;l=109) shares the validation steps of [`ValidateNamedArrayBufferViews()`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/ml/webnn/ml_graph.cc;l=20).

The XNNPACK backend implementation, e.g., [`MLGraphXnnpack::InvokeXnnRuntime()`](https://chromium-review.googlesource.com/c/chromium/src/+/4027501/12/third_party/blink/renderer/modules/ml/webnn/ml_graph_xnnpack.cc#826), is under review.

**Comment by zolkis** [comment]
After reading the implementation code, I made a best effort catch-up of the principles in #319, which needs your help for improving.
The implementations need to be finished as well.

**Comment by anssiko** [comment]
(The most current PR that proposes to fix this issue is #329.)
