### ISSUE TITLE
MLNamedArrayBufferViews record, or array of records?

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#320]
Currently defined as a record of DOMString and ArrayBufferView:

> typedef [record](https://webidl.spec.whatwg.org/#idl-record)<[DOMString](https://webidl.spec.whatwg.org/#idl-DOMString), [ArrayBufferView](https://webidl.spec.whatwg.org/#ArrayBufferView)> MLNamedArrayBufferViews;

The [implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/ml/webnn/ml_graph.h;drc=727666becab9ab1b26080180df45f043cac5f0aa;l=24) shows it's supposed to be a vector of records.

Also the graph execution algorithms imply it should be a sequence of records.

**Comment by huningxin** [comment]
According to WebIDL spec, the [record<K, V>](https://webidl.spec.whatwg.org/#idl-record) is a [ordered map](https://infra.spec.whatwg.org/#ordered-map). For record<DOMString, ArrayBufferView>, the map key is name in the type of DOMString and value is ArrayBufferView.

And according to [Blink IDL binding](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/bindings/core/v8/native_value_traits_impl.h;l=1167), an IDL record<K, V> is represented as a C++ Vector<std::pair<k, v>>.

**Comment by zolkis** [comment]
Right, thanks for the pointers, I misunderstood the intent in the spec about records. Closing.
