### ISSUE TITLE
Clarify the usage of 32 bit floating point type and consider using double

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#325]
This issue was raised during Chromium [CL](https://chromium-review.googlesource.com/c/chromium/src/+/4031876/comment/b5589f90_a4e15806/) review. Thanks Jiewei @wacky6 for the valuable feedback!

The WebIDL 32 bit floating point type [`float`](https://webidl.spec.whatwg.org/#idl-float) is widely used by WebNN spec, such as for setting min and max value of [clamp](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-clamp) operator:

```js
dictionary MLClampOptions {
  float minValue;
  float maxValue;
};
```

However, WebIDL spec has a [warning](https://webidl.spec.whatwg.org/#idl-float) of using `float` and the recommendation is to use `double`. 

> Unless there are specific reasons to use a 32 bit floating point type, specifications should use double rather than float, since the set of values that a double can represent more closely matches an ECMAScript Number.

According to that, Jiewei suggested that the spec should mention reason of using `float` (at least an informative note) and propose  using `double` instead. The reasons include (pasted from the CL thread):

* Don't see particular reasons for limiting this to fp32
* What if (in the future) we have backends that can work with fp64? In this case fp32 becomes a limitation.
* Would it be worthwhile specifying float point casting behavior in the spec? Say, if caller passes in a fp64 number (that is too large to represent in fp32/fp16), how should backend interpret this (cast to infinity, error, find closest value non-infinity, something else)?

**Comment by wchao1115** [comment]
Just an additional note that extending `float` attributes e.g. `minValue`, `maxValue` attributes in the options dictionary should not be non-controversial. If it makes the spec more inline with the rest of WebIDL specs, I think it's reasonable. However, I have some reservations about adding support for float64 type as an operand type. I don't think it's not needed. For instance, on the GPU, float64 tensor type is not widely supported. New models only tend to become smaller with lower precision and the need for a double-precision trained parameter is unheard of.

**Comment by inexorabletash** [comment]
Discussion here and elsewhere hasn't explicitly mentioned the [resample2d()](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-resample2d-method) [`scales`](https://webmachinelearning.github.io/webnn/#dom-mlresample2doptions-scales) option, which is defined as `sequence<float>`. This isn't part of graph execution, but a convenience for calculating the integer target sizes. #474 proposes remove the option as a simplification, but if kept it should probably be changed to `double`.
