### ISSUE TITLE
WPT tests tracker / 2 for remaining ops

### ISSUE THREAD

**Issue by BruceDai** [webmachinelearning/webnn#338]
Here's process of WPT tests for remaining **20** ops with @fdwr‘s great efforts on these operations tolerances, thanks much @fdwr!
 
_Note: Set **l2Pool2d** being **P3** is due to issue #278._

I synced with @fdwr about tolerance definitions for **gru**/**gruCell** and  **lstm**/**lstmCell**，since they're not operators but more like entire miniature graphs themselves, **we need community for some help of defining them**, thanks.

| Operations |  WebNN-Baseline implementation | WebNN-Polyfill implementation  | WPT tests (PR link) | Priority | Note |
| -- | -- | -- | -- | -- | -- |
| hardSwish | [√](https://github.com/webmachinelearning/webnn-baseline/pull/32) | √ | [√](https://github.com/web-platform-tests/wpt/pull/38712) | P1 | It's easy to implement |
| resample2d | [√](https://github.com/webmachinelearning/webnn-baseline/pull/33) | √ |[√](https://github.com/web-platform-tests/wpt/pull/41811) | P1 | Required by Semantic Segmentation - DeepLabv3 | 
| pRelu| [√](https://github.com/webmachinelearning/webnn-baseline/pull/35) | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/212) |[√](https://github.com/web-platform-tests/wpt/pull/39048)| P1 | It's easy to implement |
| pad | [√](https://github.com/webmachinelearning/webnn-baseline/pull/47) | √[(updated)](https://github.com/webmachinelearning/webnn-polyfill/pull/213) |  [√](https://github.com/web-platform-tests/wpt/pull/39246)| P1 | | 
| elu | [√](https://github.com/webmachinelearning/webnn-baseline/pull/39) | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/218) | [√](https://github.com/web-platform-tests/wpt/pull/39428)  | P1 | It's easy to implement |
| instanceNormalization | [√](https://github.com/webmachinelearning/webnn-baseline/pull/45) | √ | [√](https://github.com/web-platform-tests/wpt/pull/43891) | P1 | Required by Fast Style Transfer |
| hardSigmoid| [√](https://github.com/webmachinelearning/webnn-baseline/pull/40) | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/219)| [√](https://github.com/web-platform-tests/wpt/pull/39430) | P1 | It's easy to implement |
| linear | [√](https://github.com/webmachinelearning/webnn-baseline/pull/41)  | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/220) | [√](https://github.com/web-platform-tests/wpt/pull/39429)  | P1 | It's easy to implement |
| softplus | [pr](https://github.com/webmachinelearning/webnn-baseline/pull/42)  | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/221) | [√](https://github.com/web-platform-tests/wpt/pull/39431)  | P1 | It's easy to implement |
| softsign | [√](https://github.com/webmachinelearning/webnn-baseline/pull/43)  | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/222) | [√](https://github.com/web-platform-tests/wpt/pull/39432)  | P1 | It's easy to implement |
| reduceL1 | [√](https://github.com/webmachinelearning/webnn-baseline/pull/44)  | √ | [√](https://github.com/web-platform-tests/wpt/pull/39467) | P2 | | 
| reduceL2 | [√](https://github.com/webmachinelearning/webnn-baseline/pull/44)  | √ | [√](https://github.com/web-platform-tests/wpt/pull/39467)| P2 | | 
| reduceLogSum | [√](https://github.com/webmachinelearning/webnn-baseline/pull/44)  | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/223) | [√](https://github.com/web-platform-tests/wpt/pull/39467)| P2 | | 
| reduceLogSumExp | [√](https://github.com/webmachinelearning/webnn-baseline/pull/44)  | √ | [√](https://github.com/web-platform-tests/wpt/pull/39467)| P2 | | 
| reduceSumSquare | [√](https://github.com/webmachinelearning/webnn-baseline/pull/44)  | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/223) | [√](https://github.com/web-platform-tests/wpt/pull/39467)| P2 | | 
| gru | √ | √ | [√]((https://chromium-review.googlesource.com/c/chromium/src/+/5764428))| P2 | Required by RNNoise, NSNet |
| gruCell | √ | √ | [√]((https://chromium-review.googlesource.com/c/chromium/src/+/5764428))|  P2 | Required by Recurrent network |
| lstm | [√](https://github.com/webmachinelearning/webnn-baseline/pull/71) | [√](https://github.com/webmachinelearning/webnn-baseline/pull/71) | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/227) | P2 | Required by Recurrent network |
| lstmCell | [√](https://github.com/webmachinelearning/webnn-baseline/pull/70) | [√](https://github.com/webmachinelearning/webnn-polyfill/pull/227) | [√]((https://chromium-review.googlesource.com/c/chromium/src/+/5763402) )| P2 | Required by Recurrent network |
| l2Pool2d | [√](https://github.com/webmachinelearning/webnn-baseline/pull/68) | √ | [√](https://github.com/web-platform-tests/wpt/pull/44314)| **P3** | There's an issue #278 |

**Comment by BruceDai** [comment]
Link to #265

**Comment by fdwr** [comment]
Operator tolerances:

Op | float16 | float32 | notes
-- | -- | -- | --
pad | 0 ULP | 0 ULP |
linear | 2 ULP | 2 ULP | x * scale + bias
hardSwish | 3 ULP | 3 ULP | if x <= -threshold then 0 elif x >= threshold else x * (x + threshold) / (2 * threshold)   // threshold = 3
reduceL1 | <=IEPOE ULP | <=IEPOE ULP | abs(a1) + abs(a2) + ... + abs(an)
remaining... | (pending) | (pending) | verifying spreadsheet...

**Comment by anssiko** [comment]
@BruceDai can you provide on update on these remaining tests, can we close this issue?

**Comment by BruceDai** [comment]
Hi @anssiko, I'm sorry for not updating this status timely.
 
Please see the above updated table of V1 remaining operations, now except tests for these complex gru/gruCell/lstm/lstmCell operations which are WIP by @fdwr and me , others are almost done (remaining prs were under reviewing or approved). 

Regarding to V2 transformers operations, they've been already tracked by https://github.com/webmachinelearning/webnn/issues/485, now there're two remaining prs for constant (fillSequence) and triangular which are discussed on #492 and #494.

Thanks a lot for great supports from @fdwr @huningxin @Honry and @mei1127 ! 👍

**Comment by BruceDai** [comment]
Since recent [gru/gruCell tests](https://chromium-review.googlesource.com/c/chromium/src/+/5764428) and [lstm/lstmCell tests](https://chromium-review.googlesource.com/c/chromium/src/+/5763402) landed into WPT, now we have all conformance tests to cover current 78 operators. So I'm going to close this issue.
