### ISSUE TITLE
Clarify where GPU related states are stored for WebGPU interop (MLContext, MLCommandEncoder and MLGraph)

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#342]
Split from https://github.com/webmachinelearning/webnn/issues/341, where @wacky6 mentioned 

> From the current spec, it's unclear where GPU related states are stored (are they on MLCommandEncoder, or MLGraph itself).

I'd agree the spec should improve in this area. 

AFAIK, for GPU context, `MLContext` should maintain a reference to GPU device, `MLGraphBuilder` created from GPU `MLContext` should also refer to GPU device to create and compile GPU operators, `MLGraph` should maintain the compiled GPU operators and persistent/constant GPU resources, `MLCommandEncoder` should  create the command list from GPU device and record operators initialization and compute commands.

@wchao1115  should know more details than me, please feel free to chime in.

**Comment by bbernhar** [comment]
@huningxin is the group still pursing this approach? If not, can we close in favor of https://github.com/webmachinelearning/webnn/issues/688?

**Comment by huningxin** [comment]
Yes, this one is obsoleted by #688. Closing it.
