### ISSUE TITLE
Need to define error handling of MLNamedArrayBufferViews transfer algorithm

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#351]
According to the steps of the [MLNamedArrayBufferViews transfer algorithm](https://www.w3.org/TR/webnn/#mlnamedarraybufferviews-transfer) in WebNN spec, for each `ArrayBufferView`, it [transfers the underlying `ArrayBuffer`](https://webidl.spec.whatwg.org/#arraybuffer-transfer) of the view. 

However, the `ArrayBuffer` transferring algorithm performs [`DetachArrayBuffer(arrayBuffer [, key])`](https://tc39.es/ecma262/#sec-detacharraybuffer), defined by ECMAScript spec, that would throw a "TypeError" exception if the `ArrayBuffer.[[ArrayBufferDetachKey]]` is not `key` (`key` is set to `undefined` if not present). Because WebNN doesn't set `key`, it means the `ArrayBuffer` whose [[ArrayBufferDetachKey]] is set to a value other than `undefined` would fail, such as the value of [WebAssembly.Memory](https://webassembly.github.io/spec/js-api/#memory)'s [buffer](https://webassembly.github.io/spec/js-api/#dom-memory-buffer) attribute. For another example, the `ArrayBuffer` returned by WebGPU [`GPUBuffer::getMappedRange()`](https://www.w3.org/TR/webgpu/#dom-gpubuffer-getmappedrange) who sets `[[ArrayBufferDetachKey]]` to "WebGPUBufferMapping".

WebNN spec should define how to handle this exception and what's the impact to the `MLNamedArrayBufferViews`. In particular, if the exception occurs when transferring the view in the middle of the loop, what should the implementation deal with the already transferred views, the failing view and the remaining views in the `MLNamedArrayBufferViews`.

This issue was raised by @wacky6 in WebNN [Chromium CL review](https://chromium-review.googlesource.com/c/chromium/src/+/4237384/comment/bd7b27ce_d03b98a9/). Thanks Jiewei!

**Comment by huningxin** [comment]
In [WebML WG Teleconference – 11 May 2023](https://www.w3.org/2023/05/11-webmachinelearning-minutes.html#t09), group discussed this issue, and @RafaelCintron proposed that

> RafaelCintron: we can loop through everything before detaching? to make sure everything can be detached?
… put a pointer to say "this cannot be detached" and only when we know everything can be detached we detach everything

This ideal sounds great. Thanks Rafael! 

This validation loop should ensure WebIDL [transfer an ArrayBuffer](https://webidl.spec.whatwg.org/#arraybuffer-transfer) algorithm would succeed for each array. As far as I can tell, there are three aspects need to be validated:
1. The buffer is not SharedArrayBuffer. This check can be done by [`IsSharedArrayBuffer(buffer)`](https://tc39.es/ecma262/multipage/structured-data.html#sec-issharedarraybuffer).  It is asserted by WebIDL [transfer an ArrayBuffer](https://webidl.spec.whatwg.org/#arraybuffer-transfer) algorithm.
1. The buffer is not detached. This check can be done by [`IsDetachedBuffer(buffer)`](https://tc39.es/ecma262/multipage/structured-data.html#sec-isdetachedbuffer).  It is also asserted by WebIDL [transfer an ArrayBuffer](https://webidl.spec.whatwg.org/#arraybuffer-transfer) algorithm.
1. The buffer's [[ArrayBufferDetachKey]] is undefined, otherwise the [DetachArrayBuffer(arrayBuffer [, key])](https://tc39.es/ecma262/#sec-detacharraybuffer) would throw exception.

For the last check, should it be done by comparing `ArrayBuffer.[[ArrayBufferDetachKey]]` directly? I didn't find this assertion in WebIDL [transfer an ArrayBuffer](https://webidl.spec.whatwg.org/#arraybuffer-transfer) algorithm.  @domenic , any insights? 

And Blink's [DOMArrayBuffer](https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:third_party/blink/renderer/core/typed_arrays/dom_array_buffer.h) class seems not to expose `detached_key_`, so the implementation may not check the detached key. Did I miss anything? @wacky6

**Comment by domenic** [comment]
> I didn't find this assertion in WebIDL [transfer an ArrayBuffer](https://webidl.spec.whatwg.org/#arraybuffer-transfer) algorithm. @domenic , any insights?

"transfer an ArrayBuffer" will throw if [[ArrayBufferDetachKey]] is not undefined, as explained in the note after it (which refers to the note after https://webidl.spec.whatwg.org/#dfn-detach ).

**Comment by huningxin** [comment]
@domenic 

> "transfer an ArrayBuffer" will throw if [[ArrayBufferDetachKey]] is not undefined, as explained in the note after it (which refers to the note after https://webidl.spec.whatwg.org/#dfn-detach ).

That's cool. Thanks! 

Because WebNN [MLNamedArrayBufferViews transfer algorithm](https://www.w3.org/TR/webnn/#mlnamedarraybufferviews-transfer) transfers an array of buffers by a loop, we want to avoid this exception when transferring a buffer in the middle of the array, that may leave the early transferred buffers detached. Should we check [[ArrayBufferDetachKey]] is undefined for each buffer in the validation loop? 

As there are three checks (if I didn't miss any others) for a successful buffer transferring, if there is a WebIDL algorithm for this check, e.g. an ArrayBuffer is `detachable`, that would be extremely helpful.

WDTY?

**Comment by domenic** [comment]
> Should we check [[ArrayBufferDetachKey]] is undefined for each buffer in the validation loop?

Yes, I think that would work.

> if there is a WebIDL algorithm for this check, e.g. an ArrayBuffer is `detachable`, that would be extremely helpful.

I'd be happy to review any work to add such an algorithm to Web IDL.
