### ISSUE TITLE
Use static padding values for `pad` operation

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#354]
The current WebNN [`pad`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-pad) operation declares `padding` parameter as an `MLOperand` whose values may be dynamic at runtime, e.g., the compute result of another operation.

```js
partial interface MLGraphBuilder {
  MLOperand pad(MLOperand input, MLOperand padding, optional MLPadOptions options = {});
};
```

Although this definition is close to framework, such as ONNX [`Pad`](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Pad) op, it is not widely available on native ML APIs. This may lead to complex implementation if the native ML APIs only support static padding values. 

For example, DirectML [`DML_PADDING1_OPERATOR_DESC`](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_padding1_operator_desc) defines `startPadding` and `endPadding` as two unsigned integer arrays.
```c++
struct DML_PADDING1_OPERATOR_DESC {
  const DML_TENSOR_DESC *InputTensor;
  const DML_TENSOR_DESC *OutputTensor;
  DML_PADDING_MODE      PaddingMode;
  DML_TENSOR_DATA_TYPE  PaddingValueDataType;
  DML_SCALAR_UNION      PaddingValue;
  UINT                  DimensionCount;
  const UINT            *StartPadding;
  const UINT            *EndPadding;
};
```

XNNPACK [`xnn_define_static_constant_pad()`](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#LL924C17-L924C47) defines `pre_paddings` and `post_paddings` as two `size_t` arrays.
```c++
enum xnn_status xnn_define_static_constant_pad(
  xnn_subgraph_t subgraph,
  const size_t* pre_paddings,
  const size_t* post_paddings,
  float padding_value,
  uint32_t input_id,
  uint32_t output_id,
  uint32_t flags);
```

MPSGraph [`padTensor`](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/3580502-padtensor?language=objc) also defines `lefPadding`NSArray<NSNumber *>`
```c++
(MPSGraphTensor *)padTensor:(MPSGraphTensor *)tensor 
              withPaddingMode:(MPSGraphPaddingMode)paddingMode 
                  leftPadding:(MPSShape *)leftPadding 
                 rightPadding:(MPSShape *)rightPadding 
                constantValue:(double)constantValue 
                         name:(NSString *)name;
```

The proposal is to use static padding values for WebNN `pad` operation that would simplify the implementation on native ML APIs, such as
```js
partial interface MLGraphBuilder {
  MLOperand pad(MLOperand input,
                sequence<unsigned long> beginningPadding,
                sequence<unsigned long> endingPadding,
                optional MLPadOptions options = {});
};
```

The ML framework could map to WebNN static padding values if the padding operand is a constant and still support dynamic padding values by its own kernels.

Any thoughts?

**Comment by wacky6** [comment]
Might be worth considering whether dynamically changing padding values requires to rebuild the whole graph for computation.

I have a slight preference for using static values (i.e. those can be known at graph building time) to avoid graph rebuild (re-trace in some TF2 terms) on each compute() call.

Note, such rebuilds can be costly. IMO, they shouldn't be hidden by API implementation.

**Comment by huningxin** [comment]
> Note, such rebuilds can be costly. IMO, they shouldn't be hidden by API implementation.

Great point, thanks @wacky6 !

**Comment by zolkis** [comment]
About the naming, I like pre- and postPadding, somewhat less the left- and rightPadding, and the the start- and endPadding, but beginningPadding doesn't sound good. Maybe use start- and endPadding instead? or pre- and postPadding?

**Comment by huningxin** [comment]
@zolkis , thanks for your comments.

> but beginningPadding doesn't sound good. Maybe use start- and endPadding instead? or pre- and postPadding?

I don't have strong preference on naming. I am just trying to be consistent within the spec, e.g., WebNN [conv2d](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-conv2d) padding uses "begining" and "ending"

> padding: a sequence of unsigned long of length 4. The additional rows and columns added to the beginning and ending of each spatial dimension of input, [beginning_height, ending_height, beginning_width, ending_width]. 

BTW, I updated my proposal to use `endingPadding`.

**Comment by zolkis** [comment]
In conv2d() we also use "upper" and "lower".

IMHO it doesn't sound like good English to say "beginningPadding" and "endingPadding", but I will let native speakers chime in on that.

**Comment by fdwr** [comment]
> In conv2d() we also use "upper" and "lower". ..., but I will let native speakers chime in on that.

@zolkis : 🤔 I'm comfortable with either `start`/`end` and `pre`/`post`, but I'd avoid "upper" and "lower" here, which are confusing terms when dealing with 2D images, because upper and lower often mean a vertical elevation. So specifying the "left" and "right" padding via "lower" and "upper" is weird (because a vertical adjective is used for a horizontal unit), but defining the "top" and "bottom" in terms of "lower" and "upper" is even weirder because typically matrices are drawn with the numerically *low* row indices on top, making the axially "lower" padding actually the visually "upper" padding 🙃.
