### ISSUE TITLE
Need to define the algorithm for the calculation of the output shape of Resample2d

### ISSUE THREAD

**Issue by lisa0314** [webmachinelearning/webnn#360]
As the [spec](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-resample2d) said,  when the target sizes are not specified,  the output sizes should be calculated from the options.scales argument.
However, the calculation formula of the output shape is missing currently. 
For example,
`output_shape[axes[i]] = floor(scales[i] * (input_shape[axes[i]])` for all i in axes
`output_shape[j] = input_shape[j]` for j not in axes, j in range(0, input_rank)

This issue was raised by @huningxin  in WebNN [Chromium CL review](https://chromium-review.googlesource.com/c/chromium/src/+/4314499/comment/995eace8_24816427/). Thanks Ningxin!

**Comment by fdwr** [comment]
`floor` sounds good to me, to avoid partial pixels. It's also compatible with ONNX's [pixel resampling operator](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Resize), and it's evidently also what the preliminary Chromium implementation is already doing in [resample](https://github.com/mingmingtasd/chromium-src/blob/545abe387ce92eb3797e401efba7c17dc4ef6eb2/third_party/blink/renderer/modules/ml/webnn/ml_graph_builder.cc#L1142-L1150).

**Comment by BruceDai** [comment]
Thanks @inexorabletash's reminder comment on #611.
> Also this is mentioned in #360 so I think after this lands we can close that issue?

Now I think we may close this one, thanks.
