### ISSUE TITLE
 The valid range of `output_padding` of MLConvTranspose2dOptions should be clarified

### ISSUE THREAD

**Issue by miaobin** [webmachinelearning/webnn#368]
The description of the `output_padding` parameter in our [spec](https://webmachinelearning.github.io/webnn/#dom-mlconvtranspose2doptions-outputpadding) now lacks clarity on its value.
This issue was raised by @huningxin in WebNN Chromium [CL review](https://chromium-review.googlesource.com/c/chromium/src/+/4115574/comment/e1e924d1_4376643c/) and we should verify its value during our implementation.

**Comment by inexorabletash** [comment]
I think this ended up being duplicated as #630 which now has PR #631 up.

Even though this came first I'm going to tentatively resolve it as a duplicate, but please push back if I misunderstood.
