### ISSUE TITLE
Make the `starts` and `sizes` definitions of `slice` op consistent and simplified

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#369]
Thanks @fdwr for pointing out the inconsistency of `starts` and `sizes` definitions of [`slice`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-slice) op when revisiting the PR https://github.com/webmachinelearning/webnn/pull/359#issuecomment-1484393520, where Dwayne mentioned: 

>  I just noticed slices parameter starts still has the negative number policy and accepts axis coordinates as long rather than unsigned long; and its sizes parameter has an unusual policy that -1 is special, whereas sizes in resample2D is sequence<unsigned long>. Do we want to rationalize these for consistency too, having higher level policy like this determined by the calling framework?

In a followed [comment](https://github.com/webmachinelearning/webnn/pull/359#issuecomment-1484636388), Dwayne also pointed out that 

> we see that every other sizes parameter is unsigned long (see below), leaving only slice as sequence<long> sizes.

From my point of view, using unsigned integer for `starts` and `sizes` makes sense. It not only would help ensure the consistency across the spec but also would simplify the implementation. The native ML APIs, such as DirectML's [`DML_SLICE1_OPERATOR_DESC`](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_slice1_operator_desc) and XNNPACK's [`xnn_define_static_slice`](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#L1417), usually use unsigned integer starts/offsets and sizes.

Another simplification idea is whether the `MLSliceOptions` should be removed. `MLSliceOptions.axes` is used to indicate the dimensions of the input shape to which starts and sizes apply. However, native ML APIs, e.g. DirectML's [`DML_SLICE1_OPERATOR_DESC`](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_slice1_operator_desc), XNNPACK's [`xnn_define_static_slice`](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#L1417) and MLCompute's [`MLCSliceLayer`](https://developer.apple.com/documentation/mlcompute/mlcslicelayer?language=objc), usually expect the `starts` and `offsets` for all dimensions to be provided. 

With that, a possible simplified `slice` op definition would be
```js
partial interface MLGraphBuilder {
  // The length of `starts` and `sizes` sequences should equal to the rank of input tensor.
  MLOperand slice(MLOperand input, sequence<unsigned long> starts, sequence<unsigned long> sizes);
};
```

Thoughts?

**Comment by fdwr** [comment]
> Another simplification ... remove ... axes ... and ... all dimensions to be provided.

Thanks for the [xnn_define_static_slice](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#L1417)  and [MLCSliceLayer](https://developer.apple.com/documentation/mlcompute/mlcslicelayer?language=objc) information. I feel comfortable removing the `axes` parameter now.

It *might* be useful to keep the options object itself, if we want to extend it later with window `strides`/`steps` (seeing that both MLCompute and DirectML support steps, albeit evidently not XNNPack). Though, just appending another `sequence` `steps` parameter later works too. I'm not clear what factors in WebNN determine whether parameters should be stuffed inside an options object vs passed directly?

**Comment by huningxin** [comment]
Thanks @fdwr for sharing the insightful thoughts. Very helpful!

Based on the option 3, I made a PR #367 that simplifies the current `slice` op without adding new `MLSliceOptions.steps` support as the first step. Please take a look.

Regarding to `steps`, I found both TensorFlow's [`strided_slice`](https://www.tensorflow.org/api_docs/python/tf/strided_slice) and DirectML's [`DML_SLICE1_OPERATOR_DESC`](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_slice1_operator_desc) support negative stride which causes a reverse slice. Should `MLSliceOptions.steps` be defined as a sequence of `long`?

**Comment by fdwr** [comment]
> I made a PR https://github.com/webmachinelearning/webnn/pull/367

376? Found it: https://github.com/webmachinelearning/webnn/pull/376

**Comment by huningxin** [comment]
> 376? Found it: #376

Yes, it is #376. Sorry, that was my typo.
