### ISSUE TITLE
heads up re: proposal to add Float16Array to JavaScript

### ISSUE THREAD

**Issue by bakkot** [webmachinelearning/webnn#373]
I'm on TC39, and I'm working on advancing [a proposal](https://github.com/tc39/proposal-float16array) for Float16Array in JavaScript, which would hold IEEE binary16 floats (also called float16, fp16, f16, half precision floats, etc). I note that this spec has support for float16 values, and there is [an outstanding issue in the spec](https://www.w3.org/TR/webnn/#appendices-mloperandtype-arraybufferview-compatibility) about using ArrayBuffers containing float16s, which is currently impractical due to the lack of Float16Array in JS (the issue links to a thread in which [this comment](https://github.com/webmachinelearning/webnn/issues/127#issuecomment-771326548) says "It would be good to have the Float16Array support").

The proposal is currently at stage 2, which means TC39 has not yet committed to add it to JS. But since it seems directly relevant here, I wanted to make participants here aware that it may be coming in the hopefully not-to-distant future.

**Comment by fdwr** [comment]
>since it seems directly relevant here, I wanted to make participants here aware

Thanks @bakkot - looking forward to `Float16Array` over passing raw bits via `Uint16Array`.

**Comment by wchao1115** [comment]
@bakkot Please also consider adding comparable typed arrays for float8 and bfloat16 at the same time. These two new data types have gained support from major GPU hardware vendors in recent years. More ML models will be taking advantage of these in the near future. If you are adding float16, these two types should probably be added also.

**Comment by anssiko** [comment]
I'll assign a v2 label to this issue to signal the WG is supportive of TC39's [`Float16Array` proposal](https://github.com/tc39/proposal-float16array). Once the proposal has matured adequately we should look into adding support in WebNN API.

This half-precision float is particularly useful and demonstrably improves inference performance of e.g. latent text-to-image diffusion models (Stable Diffusion et al.) and super-resolution models (discussed in #127). This is worth prototyping already, results to be shared in this issue to keep interested folks informed.

**Comment by bakkot** [comment]
Update: the proposal to add Float16Array to JavaScript today reached [stage 3](https://tc39.es/process-document/), meaning the design is finished, the committee is in favor, and engines can start implementing and shipping it.

**Comment by anssiko** [comment]
@bakkot thanks for letting us know and congrats! We're in process of updating the WebNN API spec accordingly in #386.

**Comment by anssiko** [comment]
@bakkot I'm happy to let you know [`Float16Array`](http://tc39.es/proposal-float16array/) just landed into the [WebNN API spec](https://www.w3.org/TR/webnn/) as an official reference. Much thanks for specifying this feature important to WebNN API! Please feel free to close this issue if you're satisfied with our resolution.

Also, please let us know if there are substantive developments for `Float16Array` or other new kinds of TypedArrays or ECMA features that may intersect with this WG's interests. We may get in touch with you in the near future for some proposals.

**Comment by anssiko** [comment]
(Recent float16 implementation experience via @phoddie in TC39 issue https://github.com/tc39/proposal-float16array/issues/13 and PR https://github.com/tc39/proposal-float16array/pull/14 Feedback welcome in the upstream issue/PR. Implementation status: https://github.com/tc39/proposal-float16array/issues/7)
