### ISSUE TITLE
MLOperand::dimensions() or MLGraphBuilder::shape() for debugging purposes and diagnostics

### ISSUE THREAD

**Issue by fdwr** [webmachinelearning/webnn#379]
While testing local implementations of WebNN operators, I found the need to display the shapes for verification, but my generic `LogTensorShapes` function had no way to actually *access* those shapes, either from the `MLOperands` or the final build/compute results. Other WebNN users *will* need a similar diagnostic functionality, even if for no other reason than sanity checking. e.g.

![image](https://user-images.githubusercontent.com/1809166/231944818-c5b3367a-525d-44a3-9c9c-89660d5492c0.png)

It would also be valuable for computing the necessary output buffer size when binding the outputs, instead of getting it wrong and patching the count later or duplicating shape inference logic along the way (which will be known to larger frameworks that already have this logic, but it will be tedious/error prone for lighter users). The `MLGraphBuilder` knows the shapes along the way, but it just doesn't expose it.

Now, there's dubious value to adding an actual `shape` *operator* which returns a tensor, since there's little point in uploading a tiny shape tensor for something that will just be consumed on the CPU side for a later reshape anyway, but a shape *getter* that returned `sequence<unsigned long>` rather than `MLOperand` would be useful. e.g.

```
interface MLOperand {
    sequence<unsigned long> dimensions();
};
```

or

```
interface MLGraphBuilder {
    ...
    sequence<unsigned long> shape(MLOperand input);
    ...
}
```

I've added a tiny implementation locally of the latter here:

- IDL: https://github.com/fdwr/chromium-src-webnn-dml/blob/a88e205c51edafb501ce4f7081e52605d1d518aa/third_party/blink/renderer/modules/ml/webnn/ml_graph_builder.idl#L238
- CPP: https://github.com/fdwr/chromium-src-webnn-dml/blob/aaa569fab061ee401a0e8897efa4cebd691a049e/third_party/blink/renderer/modules/ml/webnn/ml_graph_builder.cc#L2210-L2214

Which enables a general `LogTensorShapes` to work smoothly:

```
async function ComputeGather()
{
    await EnsureMlContextAndBuilder("ComputeGather");

    const inputTensorDesc = {type: 'float32', dimensions: [3, 2]};
    const indicesTensorDesc = {type: 'uint32', dimensions: [4]};
    const A = graphBuilder.input('A', inputTensorDesc);
    const B = graphBuilder.input('B', indicesTensorDesc);
    const C = graphBuilder.gather(A, B, {axis: 0});
    LogTensorShapes(graphBuilder, {"A": A, "B": B, "C": C}) // <=================================================

    const graph = await graphBuilder.build({'C': C});

    const bufferA = new Float32Array([1,2, 3,4, 5,6]);
    const bufferB = new Uint32Array([0,1,1,2]);
    let bufferC = new Float32Array(4*2).fill(99); // Fill with sentinel values.

    const inputs = {'A': bufferA, 'B': bufferB};
    const outputs = {'C': bufferC};
    await mlContext.compute(graph, inputs, outputs);

    UpdateInputOutputLabels(inputs, outputs);
}

function LogTensorShapes(/*MLGraphBuilder*/ graphBuilder, /*dictionary<MLOperand>*/ mlOperandDictionary)
{
    let element = document.getElementById("shapes");
    let message = "";
    for (const [tensorName, mlOperand] of Object.entries(mlOperandDictionary))
    {
        const line = tensorName + " shape: [" + graphBuilder.shape(mlOperand) + "]"; <===========================
        console.log(line);
        message += line + "<br/>";
    }
    element.innerHTML = message;
}
```

One caveat of adding a `shape` getter is that it becomes unclear what to return if WebNN later supports dynamic shapes dependent on the actual tensor *values* rather than just tensor shapes and attributes, since those are not known during build time and only after input binding? (e.g. a [NonZero operator](https://pytorch.org/docs/stable/generated/torch.nonzero.html)) Maybe `shape` in that case should return emptiness [] (or null), and early documentation should mention that possibility so apps are prepared for it.

**Comment by fdwr** [comment]
@huningxin: Indeed, that was the *other* idea I thought of 👍. Amending my top post. 📝

**Comment by inexorabletash** [comment]
Since #375 merged, [MLOperand](https://webmachinelearning.github.io/webnn/#api-mloperand) has the [shape()](https://webmachinelearning.github.io/webnn/#dom-mloperand-shape) method - can this be closed?
