### ISSUE TITLE
Why is ml a member of Navigator?

### ISSUE THREAD

**Issue by bathos** [webmachinelearning/webnn#382]
Is there a specific motivation for this? There could be a good reason for it that I’m not seeing, but on the surface it appears [misguided](https://github.com/w3ctag/design-principles/issues/426#issuecomment-1472928048) for it not to be a member of the global interface. Quoting @domenic from that thread:

> Guidance like this _[global “pollution” avoidance]_ often leads people to putting their functions under document or navigator, when they have nothing to do with Documents or with user agent data. I've personally had to advise several teams to move away from such designs in their proposals. (navigator is particularly polluted these days, unfortunately. A design principle discouraging such pollution, and encouraging using the global object instead, would be great!)

**Comment by anssiko** [comment]
Thanks for this question! The WG discussed this design consideration first when the work started and decided at that time to follow the convention set by other similar APIs being developed in parallel to this effort such as WebGPU. I think that was the key motivation. Furthermore. at that time there was no authoritative guidance on this so the WG had to look around to other similar APIs for inspiration.

Other WG participants are free to chime in if they have a different perspective or additional context.

That said, I'm pleased to see discussion on this design principle re-emerge in the issue you referred to. I believe future API authors would benefit from clearer guidance for this consideration. Should a principle have been in place for this when this API was first conceived the WG would have benefited from it.

@bathos, please let us know if you have any additional questions and feel free to close this issue if it addressed your question satisfactorily.

**Comment by zolkis** [comment]
@bathos what would be your preferred solution? Constructor for the [ML](https://www.w3.org/TR/webnn/#api-ml) object?
Its main function is to host the factory methods to create [MLContext](https://www.w3.org/TR/webnn/#mlcontext) objects, to which the rest of the API is anchored.

**Comment by zolkis** [comment]
@bathos: I agree, I've been using/preferring namespaces as well in other specs.

Thanks for the input. Feel free to comment the spec from the p.o.v. of modern idioms: the web platform is evolving, and it's good to keep in sync. It is up to the spec editors to consider the suggestions.
