### ISSUE TITLE
Need to restrict the value of alpha to be positive for elu operation

### ISSUE THREAD

**Issue by lisa0314** [webmachinelearning/webnn#383]
According to the elu definition of [wikipedia](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)#ELU) and the [paper](https://arxiv.org/pdf/1511.07289.pdf), the alpha should be positive.

This issue was raised by @huningxin in WebNN [Chromium CL review](https://chromium-review.googlesource.com/c/chromium/src/+/4458429/comment/c598ecdc_7b5e7a00/). Thanks Ningxin!

**Comment by huningxin** [comment]
Thanks for opening this issue, @lisa0314 !

The quick survey of the native ML APIs support:

- XNNPACK [`xnn_define_elu()`](https://github.com/google/XNNPACK/blob/master/src/subgraph/elu.c#L138) requires the `alpha` value to be positive. 
- DirectML [`DML_ACTIVATION_ELU_OPERATOR_DESC`](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_activation_elu_operator_desc) doc doesn't mention this restriction. 
- MPSGraph [`MPSCNNNeuronELUNode`](https://developer.apple.com/documentation/metalperformanceshaders/mpscnnneuronelunode/2866463-nodewithsource?language=objc) doc doesn't restrict the alpha value either. 

/cc @wacky6 @fdwr

**Comment by fdwr** [comment]
Hmm, ML API's typically don't restrict *floating point* inputs (more often they reject invalid *integer* quantities like axes/sizes), even if that float value would make the plot look weird (with a kink):

![image](https://user-images.githubusercontent.com/1809166/236422203-54baa2ad-228c-4ee1-9fef-e29faafc5516.png)

I don't feel strongly either way about it either way, but if someone did need a negative <del>alpha</del> *scale* parameter for whatever unusual compat reason, what would be the decomposition? WebNN v1 has no `elementwiseIf` or `greater` operators, and so you can't fall back to `elementwiseIf(greater(x, 0), x, scale * exp(x) - 1)`.

**Comment by huningxin** [comment]
@fdwr 

When `alpha` is -1, the calculation becomes `-1 * ( exp(x) - 1)`, and the plot would look like

<img src="https://user-images.githubusercontent.com/1005673/236593954-da087a57-e6c5-48cd-93a5-e872bdec2145.png" width="512" height="512">

> if someone did need a negative ~alpha~ _scale_ coefficient for negative inputs for whatever unusual compat reason, what would be the decomposition?

I think the [decomposition sample](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-elu) in current spec still works for negative `alpha`, e.g. -1:
```js
return builder.add(
          builder.max(builder.constant(0), x),
          builder.mul(
            builder.constant(-1), // alpha = -1
            builder.sub(
              builder.exp(builder.min(builder.constant(0), x)),
              builder.constant(1))));
```

(BTW, there is a typo in the elu sample code, I'll fix it.)

**Comment by fdwr** [comment]
@huningxin: Doh, fixed graph. 👍

**Comment by fdwr** [comment]
(thinking more) I think `elu` should just return a result equivalent to its decomposition `elementwiseIf(greater(x, 0), x, scale * (exp(x) - 1))`, whether the alpha scale is positive or negative. Similarly for NaN's, I'd just follow standard IEEE behavior and propagate it through. We don't have special checks for NaN's with the other floating-point activation/elementwise operators, and consider that if `scale` was actually a tensor instead of a single scalar, we wouldn't bother to scan every value inside it.

**Comment by huningxin** [comment]
A summary of Chromium prototyping:
* CoreML: [mil.ops.defs.iOS15.activation.elu](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.activation.elu) doesn't restrict alpha value
* DirectML: [DML_ACTIVATION_ELU_OPERATOR_DESC](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_activation_elu_operator_desc) doesn't restrict alpha value
* TFLite: [tfl.elu](https://www.tensorflow.org/mlir/tfl_ops#tflelu_tfleluop) doesn't support alpha parameter. It can be emulated by inserting elementwise multiply operator and constant operand with alpha value into the graph.

**Comment by fdwr** [comment]
IIRC, we agreed to close this one in TPAC2024?

**Comment by inexorabletash** [comment]
Yes, discussion at https://www.w3.org/2024/09/23-webmachinelearning-minutes.html#e89f
