### ISSUE TITLE
Remove the support of `null` value in `newShape` parameter of `reshape` build method

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#388]
WebNN [`reshape`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-reshape) op build method currently supports a special `null` value in `newShape` array that instructs the implementation to compute the size of the dimension with the value `null` so that the total size remains constant. 

In PR review https://github.com/webmachinelearning/webnn/pull/367#issuecomment-1498242058, @fwdr proposed WebNN should only support the concrete values in newShape because this can be easily handled by framework through shape inference. Thanks Dwyane!

> Though also, is this some behavior that could be easily resolved by the frameworks calling into WebNN, since presumably they already know the shapes along the way (shape inference) and could instead pass concrete values to WebNN?

I think this would also help simplify the implementation.

/cc @wacky6

**Comment by wacky6** [comment]
SGTM from implementer perspective :)

**Comment by fdwr** [comment]
Repeating @wacky6's statement, sounds good from an implementor perspective 😃.
