### ISSUE TITLE
Remove Compilation.finish and setPreference

### ISSUE THREAD

**Issue by wchao1115** [webmachinelearning/webnn#39]
As thoroughly discussed in this [PR](https://github.com/webmachinelearning/webnn/pull/35) as related to the failing state of `Compilation.createExecution`, both the `Compilation.finish` and `Compilation.setPreference` method are redundant to what `createExecution` can provide. The removal of `setPreference` can be remedied with a param passing to `createExecution` as @RafaelCintron pointed out in the thread.

**Comment by BenjaminPoulain** [comment]
+1.

I never liked `Compilation.finish()`. Folding the preferences in a dictionary passed to `createExecution()` makes sense to me.

Given that `Compilation` would be stripped down to the single function `createExecution()`, is there any reason to keep `Compilation`? Should `Model` have `createExecution()`?

**Comment by gramalingam** [comment]
I have not fully understood the distinctions in the existing spec. What scenarios are we trying to support (among those listed below)?

(a) Would we want to compile the same model multiple times (e.g., may be with different options)? This seems unlikely (but if someone thinks this is important, would be good to know).

(b) Would we want to run multiple inferences with a compiled model? This seems likely, so I assume the answer is yes.

(c) Would we want inference-options distinct from compilation-options? This also makes sense.

**Comment by huningxin** [comment]
Thanks @gramalingam, my comments are

> (a) Would we want to compile the same model multiple times (e.g., may be with different options)? This seems unlikely (but if someone thinks this is important, would be good to know).

A useful scenario might be an app compiles a model with `fast-answer` preference and gets `compilation_for_fast_answer`. And the app compiles the same model with `sustained-speed` preference and gets `compilation_for_sustained_speed`. Later when user inputs an image for instant query, the app can create an execution from `compilation_for_fast_answer` and execute it with low latency. When user launches the web camera for live queries, the app can create executions from `compilation_for_sustained_speed` and execute them continuously with good performance. In this way, the app can avoid the overhead of model re-compiling when user switches back and forth between instant query and sustained queries.

> (b) Would we want to run multiple inferences with a compiled model? This seems likely, so I assume the answer is yes.

+1

> (c) Would we want inference-options distinct from compilation-options? This also makes sense.

Could you share any examples of inference-options?

**Comment by huningxin** [comment]
Thanks @wchao1115 @BenjaminPoulain for feedback. 

> both the `Compilation.finish` and `Compilation.setPreference` method are redundant to what `createExecution` can provide. 

If removing `Compilation.finish`/`Compilation.setPreference` or even `Compilation` at all, the model compilation would happen in `createExecution` whenever apps request an inference. Given the model compilation is likely time consuming, this would lead to slow inferences (without caching compiled model) or slow first inference (with caching compiled model). Both could result in a poor user experience.

In current spec, the model compilation happens in `Compilation.finish` with respecting to the preferences set by `Compilation.setPreference`. After the compilation done, apps can call `createExecution` to create an `Execution` from the compiled model. `Execution` allows to bind inputs and outputs (`setInput` and `setOutput`) and schedule the computation on device (`startCompute`). Apps create new executions for new inference requests of the same compiled model.

**Comment by wchao1115** [comment]
I think the idea here is to keep `Model.createCompilation` but remove both the `Compilation.finish` and `Compilation.setPreference` from the interface, and instead passing the `CompilationPreference` enum value to the `Compilation.createExecution` method. This will accomplish the same thing without redundancy caused by the proposed removals. I agree there is a value in separating the model from the compiled model.

**Comment by gramalingam** [comment]
Agree with @wchao1115

**Comment by huningxin** [comment]
Agree. So the API sketch would be
```webidl
interface Model {
  Promise<Compilation> createCompilation(CompilationPreference preference);
};

interface Compilation {
  Promise<Execution> createExecution();
};
```
Does it look good?

**Comment by BenjaminPoulain** [comment]
Just to explain what I meant by getting rid of Compilation:

If we allow Execution to be reused, then the Model->createExecution() would be the compilation step. Alternatively, drop Execution and do Compilation.startCompute(inputs, outputs). The goal with either change is to simplify the API.

I am in favor of @huningxin proposal in any case. It is an improvement.

**Comment by gramalingam** [comment]
Yes, I think we could potentially drop Execution and just expose Compilation.startCompute(inputs, outputs). As I understood it from the call yesterday, there are two stages of waiting: one is waiting for the device-resources to become available (to perform an inference) and the second is waiting for the inference to be completed and the above API seems to separate these two stages. But is that important or useful? If there is no compelling reason, I prefer the simpler "startCompute(...)".

**Comment by huningxin** [comment]
Hi @BenjaminPoulain ,

> Alternatively, drop Execution and do Compilation.startCompute(inputs, outputs). 

As Execution represents an inference request that is bound with inputs and outputs, it may be more extensible, e.g. it can support querying output shape by adding `Execution.getOutputShape` or support querying hardware inference performance by adding `Execution.getPerformance`.

Hi @gramalingam ,

> As I understood it from the call yesterday, there are two stages of waiting

I agree with you that the two stanges of waiting are a bit complex. I think we can eliminate the 1st waiting that is for creation of Execution, say change `Promise<Execution> Compilation.createExecution()` to `Execution Compilation.createExecution()`.

You mentioned "inference-options" in above [comment](https://github.com/webmachinelearning/webnn/issues/39#issuecomment-584912177). If it is useful, we may support that in `Compilation.createExecution(ExecutionPreference preference)`.

**Comment by huningxin** [comment]
@gramalingam and @BenjaminPoulain , as PR #46 merged, it closes this specific issue for removing Compilation.finish and setPreference. 

Feel free to open new issues for Execution improvement, according to above discussion, the ideas seem:
 - proposal of drop Execution and add Compilation.startCompute
 - simplify "two stages of waitings" that change Compilation.createExecution to synchronous call
 - add "inference-options"

Did I miss anything?
