### ISSUE TITLE
Staging area: discuss issues for the zk-conventions-integration branch

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#404]
This is for tracking TODOs and problems to solve in the https://github.com/webmachinelearning/webnn/tree/zk-conventions-integration branch.

Issue #395 was spawned from #348 (which was moved to #399). This might be fixed later, perhaps in the _main_ branch.

Also from [there](https://github.com/webmachinelearning/webnn/pull/348#discussion_r1213195816) (the clamp() method discussion), improved platform related steps were specified that are to be applied to other methods as well.

**Comment by anssiko** [comment]
PR #446 was merged, closing this issue.
