### ISSUE TITLE
Support dedicated square root operator

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#438]
### Use case and sample models
This op was proposed by @fdwr (Thanks Dwyane!) as a WebNN v2 op in [WebML WG Teleconference – 29 June 2023](https://www.w3.org/2023/06/29-webmachinelearning-minutes.html#t02) to support transformer models, such as [segment anything model](https://github.com/facebookresearch/segment-anything).

### Cross-framework support
It is widely supported by ML frameworks, such as

- TensorFlow supports [`tf.math.sqrt`](https://www.tensorflow.org/api_docs/python/tf/math/sqrt). 
- Pytorch supports [`torch.sqrt`](https://pytorch.org/docs/stable/generated/torch.sqrt.html).
- ONNX supports [`Sqrt`](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Sqrt). 

### Cross-platform implementability

The dedicated square root operator is widely available in native ML APIs / libs, e.g., 

- XNNPACK [`xnn_define_square_root`](https://github.com/google/XNNPACK/blob/master/include/xnnpack.h#L1461C17-L1461C39)
- DirectML [`DML_ELEMENT_WISE_SQRT_OPERATOR_DESC`](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_element_wise_sqrt_operator_desc)
- MPSGraph [`squareRootWithTensor`](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/3564588-squarerootwithtensor?language=objc).

### Other references

Currently the Chromium [CL-4615724](https://chromium-review.googlesource.com/c/chromium/src/+/4615724) maps `pow(x, 0.5)` to `xnn_define_square_root` for WebNN XNNPACK backend. It could be exposed via the dedicated square root operator when WebNN spec supports it.

/cc @wacky6

**Comment by fdwr** [comment]
Motivations include:
- Backends often have a more optimized version of it available than via pow.
- It avoids needing to create and upload tiny temporary tensors (of 0.5).

Note any backend that lacks a dedicated square root can still trivially achieve it via the fallback `pow(x, 0.5)`.

**Comment by inexorabletash** [comment]
This can be closed off c/o PR #478, correct?
