### ISSUE TITLE
Fix description and formula in pooling operations

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#449]
_Originally posted by @shiyi9801 in https://github.com/webmachinelearning/webnn/pull/446#discussion_r1294339576_

> What is `filter size` in pooling operations, do you mean `window_size`?
Also this equation seems wrong. Referring to conv2d operation, I guess the correct equation looks like this?
output_size = ceil(1 + (input_size - (window_size - 1) * dilation - 1 + beginning_padding + ending_padding) / stride)
So as floor.
See the **Returns** section in  https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-pool2d

**Comment by zolkis** [comment]
This seems not specific to #446, it's a separate problem.
We need to check the formula in the **Returns** section.
Then we can update the algorithm. Right now the algorithm uses generic formulation, leaving to the implementation how to calculate the output size.

**Comment by anssiko** [comment]
This part of the Returns section:

>More specifically, if the options.roundingType is ["floor"](https://webmachinelearning.github.io/webnn/#dom-mlroundingtype-floor), the spatial dimensions of the output tensor can be calculated as follow:
>
>output size = floor(1 + (input size - filter size + beginning padding + ending padding) / stride)
>
>or if options.roundingType is ["ceil"](https://webmachinelearning.github.io/webnn/#dom-mlroundingtype-ceil):
>
>output size = ceil(1 + (input size - filter size + beginning padding + ending padding) / stride)

... reads like informative text. It should be marked as such and the two formulas corrected.

**Comment by zolkis** [comment]
Fixed by #478
