### ISSUE TITLE
Use web spec best practices

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#450]
_Originally posted by @inexorabletash in https://github.com/webmachinelearning/webnn/pull/446#discussion_r1294860601_
            
> Drive by comment: the first step here (_If a or b is not an instance of MLOperand, then throw a "TypeError"..._)  is unnecessary, and I see this repeated throughout the newly introduced algorithms for methods ("operations" in Web IDL). The Web IDL bindings already take care validating input types and throwing TypeError.

> Further, even in cases where an explicit error must be thrown, the intrinsic type TypeError should be thrown, not a DOMException of type "TypeError" (which is not present in https://webidl.spec.whatwg.org/#idl-DOMException-error-names)

(Issue created to document this change).

**Comment by inexorabletash** [comment]
Another example: 

in `constant()` - _If type is undefined, let type be "float32"._ - this is handled automatically by having the default in the Web IDL.

**Comment by inexorabletash** [comment]
Also (and this is not new), dictionary members are more normally references in prose using the infra ordered map syntax: _options_["`foo`"] 

By the time an algorithm "sees" the dictionary, it's gone through the bindings layer and is an ordered map - https://webidl.spec.whatwg.org/#idl-dictionaries

**Comment by inexorabletash** [comment]
> throw a "TypeError" simple exception 

Just write: throw a TypeError. 

In bikeshed markdown:
```
... [=exception/throw=] a {{TypeError}}.
```

**Comment by inexorabletash** [comment]
And (this new is in PR 446) the entire "check linear options" algorithm is unnecessary; the dictionary bindings for ECMAScript take care of all of that, including default values.

**Comment by inexorabletash** [comment]
(apologies for random feedback; I may have more time later this week to do a more thorough pass)

**Comment by inexorabletash** [comment]
Not new: In "create MLActivation" steps

> If name is undefined or null, throw a "TypeError" and abort these steps.

It looks like all call sites are internal to the spec and so this could just be an assert.

And this is more off topic, but: none of the call sites for "create MLActivation" actually pass _builder_ - that should be fixed at the call sites. I also don't see any of the call sites passing _init-steps_ but maybe I'm missing something.

**Comment by inexorabletash** [comment]
Not new: in input(name, descriptor):

> If name is undefined or an empty string, then throw a TypeError and stop.

`name` is defined as DOMString; passing literal `undefined` from script will yield the string `"undefined"`. So this can be reduced to just a test for an empty string.

(This is a gotcha for web developers since an error would be better, but that's how the Web IDL bindings work.)

**Comment by inexorabletash** [comment]
Not new: in conv2d(input, filter, options)

> If options is undefined, let options be an empty object.

The _options_ argument is defined as `optional MLConv2dOptions options = {}` so it will always be present.

> If options.padding is undefined, ...

It's more correct to write: 

> If options["padding"] exists, ...

in Bikeshed markdown:

```
If |options|[{{MLConv2dOptions/"padding"}}] [=map/exists=] ...
```

**Comment by inexorabletash** [comment]
Not new:

> Let ... be the first argument.
> Let ... be the second argument.

This is unnecessary, arguments are named. I see 5 uses of "first argument", and 2 of "second argument". Just drop these.

**Comment by inexorabletash** [comment]
Not new: Similar to a nitpick above, for "create MLOperand", the second step is:

> If desc is not an object that implements MLOperandDescriptor ...

Since this is called internally with _this_ everywhere, the validation is unnecessary. 

Also, total nitpick, I noticed that some of the call sites are phrased as:

> ... the result of invoking the create MLOperand steps given this ...

and some are:

> ... the result of invoking the create MLOperand steps with this  ...

This applies to other invocations as well ("with" vs. "given") - ideally the phrasing would be consistent, but there's not consistency in phrasing across specs so either is fine.

**Comment by inexorabletash** [comment]
Optional style suggestion: 

If you rename the algorithms from (for example) _"create MLOperand"_ to _"create an MLOperand"_ (which is better grammar anyway), then you can use simplified phrasing when invoking algorithms. 

Before:

> Let operand be the result of invoking the create MLOperand steps given this and descriptor.

After:

> Let operand be the result of creating an MLOperand given this and descriptor.

Note that Bikeshed is smart enough to link "_creating_ an MLOperand" to a definition named "_create_ an MLOperand". More and more specs are using the shorter form - less text is generally more readable.

**Comment by inexorabletash** [comment]
Not new: There are a couple checks for _"... is not an an object that implements MLOperandDescriptor ..."_ - in both cases, the value is supplied from an internal slot or explicitly passed via the algorithm, so this validation seems unnecessary.

**Comment by inexorabletash** [comment]
New (mostly) in 446: When initializing lists:

> ... set it to [0, 0, 0, 0].

Technically at this point the Web IDL [sequence](https://webidl.spec.whatwg.org/#sequence-type) has become a Infra [list](https://infra.spec.whatwg.org/#list) and should be initialized using this literal syntax:

> ... set it to « 0, 0, 0, 0  ».

Super nitpicky but it can make it clearer to implementers that by this point we're talking about abstract types, not a Javascript Array.

**Comment by inexorabletash** [comment]
Not new: There are a few places where a record is being iterated, with:

> For each key -> value of ...

This should use a proper right arrow (&rarr;) instead of the digraph, and can be written in markdown as:

```
[=map/For each=] |key| &rarr; |value| of ...
```

Or use a literal → in the source if you don't mind non-ASCII.

**Comment by inexorabletash** [comment]
Not new: Many places use _"... throw ... and stop."_ or _"... throw ... and abort these steps."_

Per https://infra.spec.whatwg.org/#algorithm-control-flow this isn't necessary - throwing terminates the algorithm.

I know it's tempting to be explicit, but shorter is usually better!

**Comment by zolkis** [comment]
Thanks a lot for all these suggestions, they are much appreciated!
Listing them in this issue makes sense, at least we have all suggestions in one place for future reference. Actually we should move the other similar suggestions here, too.

So far I applied all of these, except for 
- the dict members vs ordered map syntax (let's discuss than in a call, as IMHO it is easier to write and read the dict members syntax);
- and removing the "and stop" clauses, which I will do later (just too much and mostly manual work). Will need less busy time with lots of caffein motivators. :)

**Comment by zolkis** [comment]
_Originally posted by @inexorabletash in https://github.com/webmachinelearning/webnn/issues/446#issuecomment-1681076536_
           
> Regarding using TypeError vs. a DataError DOMException:
> 1. If you mix and match exception types, the order of the checks becomes important. From experience (e.g. with https://w3c.github.io/IndexedDB/#add-or-put) this has some benefit (e.g. developers can ask a more specific question on StackOverflow) but in practice it turns into an implementation burden - implementations must align on the sequence of input validation steps exactly. 
> 2. For modern specs where we expect non-web-browser implementations to exist (e.g. for Node.js) then the preference is to use JS-intrinsic types (TypeError, RangeError) everywhere, rather than DOMException. See https://fetch.spec.whatwg.org/ https://encoding.spec.whatwg.org/ etc.

> Either way, you'll want Web Platform Tests that exercise each failure path and validate the correct exception type is thrown.

**Comment by inexorabletash** [comment]
> the dict members vs ordered map syntax

Yeah, we can discuss. But queuing up thoughts, it helps to distinguish when you're referencing an interface member - usually only via named slots - vs. a dictionary member.  And when things get wordy like: _options["bias"].[[descriptor]]["dimensions"]_ it usually helps to use a temporary, e.g _"Let bias be options["bias"]"_

**Comment by inexorabletash** [comment]
Some more things that can be linkified to make the meaning clear:

* _... be the size of ..._ &rarr; `[=list/size=]`
  * And so far as I can tell, all of the places that use `.length` are referring to the size of a list (what a sequence<> turns into) and should use `[=list/size=]` instead. 
* link enum members when you can, e.g. "nchw" as `{{MLInputOperandLayout/"nchw"}}` if possible
* link _rank_ everywhere if you can, e.g. in _a number between 0 and the rank of input_

**Comment by inexorabletash** [comment]
reshape() is defined as:

```webidl
 MLOperand reshape(MLOperand input, sequence<unsigned long?> newShape);
```

The steps have:

> If newShape is a scalar number, set outputShape to « 1 ».
> Otherwise, if newShape is an array of unsigned long:

That won't apply - newShape will always be a list, where the items are unsigned long or null.

**Comment by inexorabletash** [comment]
In the "create an MLOperand", "copy an MLOperand", and "create an MLActivation" steps there are lines:

> Let thing be a new object.

This should reference the specific type, e.g. "new MLOperand"

Right now, the term "object" is linking to FileAPI, which is probably not desired. It's worth looking at the [Terms defined by reference](https://pr-preview.s3.amazonaws.com/zolkis/webnn/pull/446.html#index-defined-elsewhere) section Bikeshed generates for you, to ensure you're getting the dependencies you expect (e.g. you probably aren't meaning to use CSS4's definition for "number")

**Comment by inexorabletash** [comment]
> Store a reference to x in a.
> Store a reference of x in a.

It would be more common to just write:

Set a to x.

In the cases where this language is used, _a_ is an internal slot defined as being a reference, so I don't think the shorter form loses anything.

**Comment by inexorabletash** [comment]
Total nitpick: In several places the spec uses `true` and `false` in styled as code. Common spec formatting reserves code style for JS types, and generally in spec prose we're dealing with Infra types, and https://infra.spec.whatwg.org/#boolean and most specs just use true and false with no special styling.

**Comment by inexorabletash** [comment]
Potential refactor: This pattern repeats many times:

> 1. Make a request to the underlying platform to:
>     1. Let opImpl be an implementation-defined platform operator for the XYZ operation.
>     1.  Store a reference of opImpl in output.[[operator]].
>     1. Create an implementation-defined platform operand outputImpl to represent the output, given output and opImpl.
>     1. Store a reference to outputImpl in output.[[operand]].

Consider refactoring this into an algorithm. It looks like there are a handful of special cases that need specific handling (e.g. multiple outputs) but this might improve readability in the majority of cases where there's nothing unique going on.

**Comment by zolkis** [comment]
Thanks Joshua, I will mill on all of these.
I have been pondering the ordered map syntax: what to do with internal slots? 
Say `|object|'s [["slot-name"]]`, where  `slot-name` is e.g. `{{MLOperand/"descriptor"}}`?
I do have a preference for the current or `|object|.[[slot-name]]`, e.g. `|operand|.{{MLOperand/[[descriptor]]`, as I find it more intuitive and more concise than what I've also been using, e.g. `|object|'s [["slot-name"]]`. I don't see ambiguity in either formulation. I am open for the change, though, just let hear out the editors, too.

**Comment by inexorabletash** [comment]
Re: internal slots

There's actually a (very slow) debate about whether or not to use internal slots outside of ECMAScript at all. See https://github.com/whatwg/infra/issues/165 

The alternative is this syntax which you may have seen in other specs:

* Definition:  A `FooObject` has an associated **bar** which is a string.
* Usage: Set _foo_'s **bar** to "blah".

But if we continue using internal slots then the currently used syntax is indeed what is preferred, so no change needed:

* Definition: A `FooObject` has an internal slot \[\[bar]] which is a string.
* Usage: Set _foo_.\[\[bar\]\] to "blah".

**Comment by inexorabletash** [comment]
FYI, I'm working on a branch to improve the algorithm definitions, which will pull the declaration and variables into the algorithm. This will address the outstanding Bikeshed warnings. I'll link it here when ready.

**Comment by inexorabletash** [comment]
Note that the `WARNING: Multiple elements have the same ID` issues referencing the auto-generated "dom-interface-method" IDs seem to be due to a Bikeshed bug with overloads: https://github.com/speced/bikeshed/issues/2646

**Comment by inexorabletash** [comment]
https://github.com/inexorabletash/webnn/tree/definitions layers on top of https://github.com/zolkis/webnn/tree/zk-conventions-integration and cleans up most warnings, simplifies definition/IDL linking, and ensures you can click on arguments within a method to highlight them within the definition itself.

With that change, warnings are down to:

```
LINE ~842: The var 'options' (in algorithm 'createcontextsync') is only used once.
If this is not a typo, please add an ignore='' attribute to the <var>.
WARNING: The var 'graph' (in algorithm 'initializeGraph(graph)' for MLCommandEncoder) is only used once.
If this is not a typo, please add an ignore='' attribute to the <var>.
LINE ~2568: The var 'descriptor' (in algorithm 'element-wise-unary-op' for MLGraphBuilder) is only used once.
If this is not a typo, please add an ignore='' attribute to the <var>.
WARNING: The var 'b' (in global scope) is only used once.
If this is not a typo, please add an ignore='' attribute to the <var>.
LINE ~4927: The var 'inputs' (in algorithm 'reshape(input, newShape)' for MLGraphBuilder) is only used once.
If this is not a typo, please add an ignore='' attribute to the <var>.
LINE ~5283: The var 'options' (in algorithm 'softsign(input)' for MLGraphBuilder) is only used once.
If this is not a typo, please add an ignore='' attribute to the <var>.
WARNING: Multiple elements have the same ID 'dom-mlgraphbuilder-hardswish'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-mlgraphbuilder-relu'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-mlgraphbuilder-sigmoid'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-mlgraphbuilder-softmax'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-mlgraphbuilder-softsign'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'dom-mlgraphbuilder-tanh'.
Deduping, but this ID may not be stable across revisions.
```

* createcontextsync - mentioned above, the overloads need to be split up
* initializeGraph(graph) - this one doesn't have an algorithm, just prose!
* I'm not sure where the lone _b_ is yet.
* descriptor, inputs, and options called out in a review comment in 446
* the "multiple elements have the same ID" issue called out above.

**Comment by inexorabletash** [comment]
Pushed an update to https://github.com/inexorabletash/webnn/tree/definitions to split out createContext/createContextSync overloads. This could be done multiple ways, just wanted to burn down the warnings list.

**Comment by zolkis** [comment]
_Originally posted by @inexorabletash in https://github.com/webmachinelearning/webnn/pull/446#discussion_r1300710975_

>  "between" is ambiguous (here and elsewhere); it could mean inclusive or exclusive at either bound.
Consider using phrasing from https://infra.spec.whatwg.org/#the-range or https://infra.spec.whatwg.org/#the-exclusive-range and link appropriately.

**Comment by zolkis** [comment]
> Pushed an update to https://github.com/inexorabletash/webnn/tree/definitions to split out createContext/createContextSync overloads. This could be done multiple ways, just wanted to burn down the warnings list.

Thanks a lot! I pushed them into #446. Feel free to submit commits there.

**Comment by inexorabletash** [comment]
I tidied up https://github.com/inexorabletash/webnn/tree/definitions - it now has a single commit on top of your 446 that updates the linking and algorithm definitions. Feel free to merge that into 446 if you think it doesn't delay landing that further.

One pending change I'll make as a separate commit - there are a few places where there are multiple methods defined at once - the binary, unary, pooling, and reduction operations. For these, there is inconsistent usage of `class=algorithm-steps`

* binary operations - single algorithm-steps around all algorithms
* unary operations - single algorithm-steps around all algorithms
* pooling operations - each algorithm is also an algorithm-steps
* reduction operations - no algorithm-steps

We should be consistent among these at least. Technically, there should be a single algorithm-steps inside the algorithm container, just around the list, but that's a lot of extra markdown for limited benefit and probably more visual clutter. Any preference?

**Comment by inexorabletash** [comment]
Ugh... and I forgot to push the nicely squashed/cleaned up version. My bad. Let me rebase...

**Comment by inexorabletash** [comment]
Okay, sorry about that - rebased on top of your branch and one more cleanup. Sorry @zolkis and thanks for your patience and help!

**Comment by inexorabletash** [comment]
Ugh, I'm an idiot. Forgot one last commit that removes a bunch of unnecessary </div> elements. 

I swear https://github.com/inexorabletash/webnn/commit/13ae8f16bcba5dca31096ccae2d05d1e21155bae is it then I'll stop touching things.

**Comment by zolkis** [comment]
Thanks a lot... it's been a lot of work / help. If you attend the TPAC, don't forget to collect a beer from Anssi on my behalf :).

**Comment by inexorabletash** [comment]
Alas, no TPAC for me this year. But I appreciate the :beer: !

I'll be on the call later this week.

**Comment by inexorabletash** [comment]
Off topic, but... currently if you click on an algorithm definition it collapses/expands the `<details>`. We could prevent this with:
```
<script>
document.addEventListener('DOMContentLoaded', () => {
  [...document.querySelectorAll('summary dfn,summary var')].forEach(dfn => {
    dfn.addEventListener('click', e => { e.preventDefault(); });
  });
});
</script>
```
This is less useful for methods than it could be because of https://github.com/speced/bikeshed/issues/2647 though.

**Comment by zolkis** [comment]
> One pending change I'll make as a separate commit - there are a few places where there are multiple methods defined at once - the binary, unary, pooling, and reduction operations. For these, there is inconsistent usage of `class=algorithm-steps`
> 
> * binary operations - single algorithm-steps around all algorithms
> * unary operations - single algorithm-steps around all algorithms
> * pooling operations - each algorithm is also an algorithm-steps
> * reduction operations - no algorithm-steps
> 
> We should be consistent among these at least. Technically, there should be a single algorithm-steps inside the algorithm container, just around the list, but that's a lot of extra markdown for limited benefit and probably more visual clutter. Any preference?

Myself I have a slight estethic preference for having separate(ly collapsible/expandable) algorithms + helper algorithm, because even after collapsing, it leaves the method signatures visible. So that would be my choice.

But since those ops have been defined under a single subtitle ("container") by the editors, that can be taken as a clue to include all the algorithms in a container. Therefore, I leave the choice to @wchao1115 & @huningxin (please check e.g. https://zolkis.github.io/webnn/#api-mlgraphbuilder-unary ).

**Comment by anssiko** [comment]
I think this catch-all issue was prematurely auto-closed by GitHub because the commit message of https://github.com/webmachinelearning/webnn/commit/ad720c3f386f1450efc5c59dfe86cab339656fa7 contained the magic "Fix #NN" string. Re-opening.

**Comment by inexorabletash** [comment]
IMHO, the use of "partial interface" to break up interface definitions goes too far in the current spec, and detracts from understanding the intent of the interface types.

For `MLGraphBuilder` it helps since there are a _huge_ number of ops represented, many of which have options dictionaries.

But for `MLContext`, `MLCommandEncoder` and (following #478) `MLOperand` I think it'd be easier to understand if the interfaces were defined in one place. Developer-facing "domintro" sections closer to the prose definitions could help provide the needed context.

**Comment by inexorabletash** [comment]
FYI, I'm starting to pick away at some of these with my last few hours before going OOO for the holidays:

https://github.com/inexorabletash/webnn/tree/conventions

My plan is "one big PR" for several hopefully trivial changes to align with conventions, but I'll keep each thematically isolated change in a separate commit so we can cherry-pick etc. as desired. I won't be submitting a PR until January though.

**Comment by inexorabletash** [comment]
I lied - I put up a PR. But I'm about to go out-of-office so I'll let the editors make use of it or wait until January.

Happy Solstice, everyone!

**Comment by inexorabletash** [comment]
My skim of this issue - looking to see if we can close it yet - turns up these potentially unresolved issues:

* dict member syntax (dotted properties vs ordered map syntax) - IMHO not worth pursuing
* "register" used instead of "set" - covered in #549#issuecomment-1921901735 
* discussion of "underlying platform" simplification, covered in #462
* use of "partial interface" - worthy of discussion but as a new issue (coming soon)
* multiple methods defined with a single algorithm-steps (trivial; I have a local change I'll put up for review soon)
 
Otherwise I think @zolkis and I have tackled it all, and so we can close this out now or soon.

**Comment by inexorabletash** [comment]
Closing out now that outstanding issues are tracked elsewhere.
