### ISSUE TITLE
The default values of |options|.{{MLReduceOptions/axes}} should be {0, ...., N-1} rather than null.

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#451]
_Originally posted by @lisa0314 in https://github.com/webmachinelearning/webnn/pull/446#discussion_r1295571175_

> The default values of |options|.{{MLReduceOptions/axes}} should be {0, ...., N-1} rather than null.

**Comment by zolkis** [comment]
The description in the spec says:

> The values in the sequence must be in the range [0, N-1] where N is the [=rank=] of the input tensor. 
If not present, all dimensions are reduced.

So in the algorithm, we should check that when `axes` are given, the values are in the correct range.

**Comment by lisa0314** [comment]
> So in the algorithm, we should check that when axes are given, the values are in the correct range.
Yes, we should add check whether the values are in the correct range.
