### ISSUE TITLE
(bikeshed naming) MLOperandDataType

### ISSUE THREAD

**Issue by fdwr** [webmachinelearning/webnn#454]
Various ML libraries accept different kinds of operands to their operators (e.g. TensorFlow might accept [tensors](https://www.tensorflow.org/api_docs/python/tf/Tensor) or [variables](https://www.tensorflow.org/api_docs/python/tf/Variable); ONNX accepts the operand types [dense tensors](https://onnx.ai/onnx/repo-docs/IR.html), sparse tensors, maps, sequences, optionals; ...).

*Inside* that operand type (e.g. tensor), there may be a subtype for the element data (e.g. float32, bfloat16, int8, int32...), or `dtype` for short, as found in [NumPy data type `numpy.dtype`](https://numpy.org/doc/stable/reference/arrays.dtypes.html), [TensorFlow `tf.dtype`](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType), and [PyTorch `torch.dtype`](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype); or "data type" as found in [XNNPack xnn_datatype](https://github.com/google/XNNPACK/blob/ae2875cb2538b00f11564c5cbf649249caf510f1/include/xnnpack.h#L211) and [DirectML DML_TENSOR_DATA_TYPE](https://learn.microsoft.com/en-us/windows/win32/api/directml/ne-directml-dml_tensor_data_type).

Sometimes it makes sense in a standard to name something different from general precedent when it is more informative/clearer, but the current naming [`MLOperandType`](https://www.w3.org/TR/webnn/#enumdef-mloperandtype) actually means the data type (float32, int8...), which is both inconsistent with the community (harder to map this term to everything else) *and* adds no clarity. Additionally, if future WebNN ever supports other kinds of operands besides dense tensors (e.g. sparse tensors), it will be rather awkward to speak of this new type because there will be no vocabulary left for it, since the term `MLOperandType` was already consumed to mean the *subtype* within the operand type. Renaming `MLOperandType` -> `MLOperandDataType` will enable future expansion (if needed) where `MLOperandType` can be reintroduced to mean the actual operand type. I liken the current situation to having an enum named `Animal` which contains dog breeds {`Poodle`, `Bulldog`, `Boxer`}, which makes it harder to speak of actual animal types if later we want to introduce cats.

**Comment by zolkis** [comment]
Valid and well explained. We should have been spotted this earlier, in the spirit of https://www.w3.org/TR/design-principles/#naming-is-hard
A quite easy change: should it be part of #446, or do we prefer a separate PR after that one is merged?

**Comment by fdwr** [comment]
> should it be part of https://github.com/webmachinelearning/webnn/pull/446, or do we prefer a separate PR after that one is merged?

I defer to you and the editors ✏ there, depending on how much process overhead is involved, but I see that change is already sizeable and appears to be more about style than name changes. There are advantages to smaller changes for history following...

**Comment by anssiko** [comment]
Suggest handle this separately from #446 even if a change in an enum identifier name will not affect web compatibility, is not web-exposed. (A change in an enum _value_ name would be a normative change, needs more care.)

This will be a minor PR on top of the big PR. Thanks for your attention to detail and forward-looking thinking.

**Comment by fdwr** [comment]
> do we prefer a separate PR after that one is merged?

@zolkis I see 446 is merged. Shall I create it now?

**Comment by zolkis** [comment]
> @zolkis I see 446 is merged. Shall I create it now?

Yes, it's a good time for it now.

**Comment by fdwr** [comment]
> Yes, it's a good time for it now.

👍 https://github.com/webmachinelearning/webnn/pull/464

**Comment by inexorabletash** [comment]
Can this be closed out now?
