### ISSUE TITLE
Reserve asserts only for non-obvious things

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#455]
_Originally posted by @inexorabletash in https://github.com/webmachinelearning/webnn/pull/446#discussion_r1298735835_
            
> FWIW, I'd reserve asserts only for non-obvious things, e.g. where a much earlier step in an algorithm has ensured that a number is non-zero, so a division by it is safe.
> Asserts like these that repeat the concise Web IDL definition in longer prose are just noise and IMHO not useful for implementers.

**Comment by zolkis** [comment]
The difficulty is that e.g. the "create..." and "validate..." type of internal steps have no WebIDL, so asserts make sense there IMHO, but indeed in the algorithms with WebIDL definitions they can be removed.
@anssiko suggested we do this after #446 is merged.

**Comment by inexorabletash** [comment]
FYI I have a branch ready for this, but #514 needs to merge first.

**Comment by anssiko** [comment]
#514 is now merged.

**Comment by inexorabletash** [comment]
The remaining asserts are either:

- Asserting that the _op_ parameter to an internal algorithm is from a set. They seem fine, pending a better suggestion.
- [concat()](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-concat) args, tracked in #503 
- [broadcast-shapes](https://webmachinelearning.github.io/webnn/#mlgraphbuilder-broadcast-shapes), tackled in #534
- [input()](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-input) args, tracked in #502 

... so I'm going to go ahead and close this.
