### ISSUE TITLE
[Split] Validate the output shape of each output

### ISSUE THREAD

**Issue by mingmingtasd** [webmachinelearning/webnn#458]
https://github.com/webmachinelearning/webnn/pull/446#discussion_r1305149598

**Comment by zolkis** [comment]
_Originally posted by @mingmingtasd in https://github.com/webmachinelearning/webnn/pull/446#discussion_r1305149598_
            
 > You may want to validate the output shape for the splitted output tensors. 
`If *splits* is an {{unsigned long}}, the [=list/size=] of the output sequence equals to *splits*. The shape of each output tensor is the same as *input* except the dimension size of *axis* equals to the quotient of dividing the dimension size of *input* along *axis* by *splits*. If *splits* is a sequence of {{unsigned long}}, the [=list/size=] of the output sequence equals to the [=list/size=] of *splits*. The shape of the i-th output tensor is the same as as *input* except along *axis* where the dimension size is *splits[i]*.`

**Comment by zolkis** [comment]
Usually the inputs are validated to algorithms. 
Implementations may validate the results when the operation is executed, and if there are issues, signal an error. 
The algorithms needs to have steps to handle errors from the platform.

**Comment by mingmingtasd** [comment]
> Usually the inputs are validated in the algorithms. Implementations may validate the results when the operation is executed, and if there are issues, signal an error. The algorithms needs to have steps to handle errors from the platform.

As discussed,  that for split may be unnecessary, close it.
