### ISSUE TITLE
Add "Die On: warning" to spec metadata

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#468]
Although not yet documented, [Bikeshed now supports setting the default `--die-on` in the spec metadata](https://github.com/speced/bikeshed/issues/2623). We should make warnings fatal so contributors don't need to remember to specify `--die-on=warning` manually.

This should just require adding this to the `<pre class='metadata'>` block at the top of the spec:

```
Die On: warning
```

Also, I'm explicitly suggesting "warning" rather than "link-error" because the spec is currently clean for warnings and most Bikeshed warnings really do flag that something is wrong, so we don't want to regress.

**Comment by dontcallmedom** [comment]
`BUILD_FAIL_ON: warning` should work according to https://github.com/w3c/spec-prod/blob/958b6d59f51720a7b0f2d402f87ba193e39bc080/docs/options.md#build_fail_on

**Comment by anssiko** [comment]
@inexorabletash, maybe we should also fail the CI build similarly as in #469? The in-spec metadata directive will catch local build experiments.
