### ISSUE TITLE
Empty tensors are valid for new shape

### ISSUE THREAD

**Issue by zolkis** [webmachinelearning/webnn#472]
_Originally posted by @fdwr in https://github.com/webmachinelearning/webnn/pull/446#discussion_r1366335321_              

> If any value in newShape is 0, then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a "[DataError](https://webidl.spec.whatwg.org/#dataerror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException).

Empty tensors are valid in ML. If the `input` tensor shape contains zeros, then it's correct for `newShape` to contain zeros. Indeed, if the `input` shape contains zeros, then `newShape` *must* have at least one zero, because otherwise that would be an error. It's only an error if the number of total input element count differs from the total output element count, and so it's good to remove this redundant clause because the element count check is both necessary and sufficient.

| oldShape | newShape | validity |
|------------|------------|----------|
| [1,2,3]       | [1,2,3]       | ✅        |
| [2,3,1]       | [3,2,1]       | ✅        |
| [1,2,3]       | [6]             | ✅        |
| [0,0,0]       | [0,0,0]        | ✅        |
| [1,2,0]       | [0,0,0]        | ✅        |
| [1,2,0]       | [0,2,1]        | ✅        |
| [1,2,3]       | [1,0,3]        | ❌        |
| [1,0,3]       | [1,2,3]        | ❌        |

**Comment by fdwr** [comment]
Thanks @zolkis. My comment was specific to the wording in the `reshape` operator, but the more general related issue is here: https://github.com/webmachinelearning/webnn/issues/391

**Comment by zolkis** [comment]
Closing since #476 addresses this.
