### ISSUE TITLE
Simplify `resample2d` op

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#474]
(This was raised by @wacky6 at Chromium [CL-4963373](https://chromium-review.googlesource.com/c/chromium/src/+/4963373/comment/1b4b4268_93e2605c/) review)

The current [`resample2d`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-resample2d-method) of WebNN spec supports specifying spatial dimensions scaling factor by `scales` or target size by `sizes`, the `scales` would be ignored if `sizes` is present.

Jiewei's feedback include
> My read at the current spec is that:
> 1. "scale" and "size" are mutually exclusive.
> 2. "size" can infer "scale" unambiguously
> 3. inferring "size" from "scale" can cause problem (e.g. the two unresolved comment in this CL)
>
> My intuitive thought is to remove "scale" from API surface and leave it to "user-space", given "size" already captures the information necessary to use the API (given WebNN doesn't support dynamic shape).

For bullet 3, there is an open issue of defining the algorithm of the output shape of resample2d https://github.com/webmachinelearning/webnn/issues/360.

/cc @fdwr @wchao1115

**Comment by inexorabletash** [comment]
For posterity: if we do end up keeping `scales`, the type should probably change to `double` (see #325 for more context)

**Comment by inexorabletash** [comment]
Discussion in WebML WG meeting at TPAC: https://www.w3.org/2024/09/23-webmachinelearning-minutes.html#t05 - consensus to keep `scales` and close this issue.
