### ISSUE TITLE
Consistency for dictionary member definitions

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#483]
Most dictionary members are given explicit definitions, e.g. for
```webidl
dictionary MLBufferResourceView {
  required GPUBuffer resource;
  unsigned long long offset = 0;
  unsigned long long size;
};
```
... there's a normative prose block:

> MLBufferResourceView has the following members:
> **resource**, of type GPUBuffer
> A GPUBuffer object. Specifies the GPU buffer source.
> **offset**, of type unsigned long long, defaulting to 0
> Specifies an unsigned long long offset in the buffer source.
> **size**, of type unsigned long long
> Specifies the unsigned long long size of the buffer view.

This is not necessary and IMHO is basically a redundant definition that will make spec maintenance more difficult and risks introducing inconsistencies. The types are captured in the dictionary definition, and the behavior needs to be captured in the algorithms where the members are used. But... since these definitions are provided mostly consistently in the spec, it's worth ensuring _all_ such dictionaries get definitions.

This can be audited in the developer console with:
```js
[...document.querySelectorAll('.idl dfn[data-dfn-type=dict-member]')].map(d => d.innerText).sort()
```
...which in the current ED lists 10 examples, but after PR #478 (which should merge soon) lists only 8. That shorter list is:

- "alpha"
- "dataType"
- "deviceType"
- "dimensions"
- "inputs"
- "maxValue"
- "minValue"
- "outputs"
- "powerPreference"

**Comment by zolkis** [comment]
Right. It was aligned with the earlier practice in the spec (and not only this spec), but after we merge the current big PR, we can consistently update the spec along these suggestions. Thanks.

**Comment by inexorabletash** [comment]
Recent audit:

* [MLContextOptions](https://webmachinelearning.github.io/webnn/#dictdef-mlcontextoptions)
  * `deviceType` - could turn https://webmachinelearning.github.io/webnn/#device-type into a dfn for it
  * `powerPreference` - could turn https://webmachinelearning.github.io/webnn/#power-preference into a dfn for it
* [MLComputeResult](https://webmachinelearning.github.io/webnn/#dictdef-mlcomputeresult)
  * `inputs`, `outputs` - seems worth detailing
* [MLOperandDescriptor](https://webmachinelearning.github.io/webnn/#dictdef-mloperanddescriptor)
  * `dataType`, `dimensions` - seems worth detailing
* [MLEluOptions](https://webmachinelearning.github.io/webnn/#dictdef-mleluoptions)
  * `alpha`  - the specific `elu()` calls give definitions (duplicated!) which could be hoisted
* [MLClampOptions](https://webmachinelearning.github.io/webnn/#dictdef-mlclampoptions)
  * `minValue`, `maxValue` - the specific `clamp()` calls give definitions (duplicated!) which could be hoisted
