### ISSUE TITLE
Implement webnn-baseline and WPT for operations needed for well-known transformers

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#485]
Opening this issue to track the implementation status of webnn-baseline and WPT for [operations needed for well-known transformers](https://github.com/webmachinelearning/webnn/pull/478).

|Ops| Baseline | WPT tests|
|----|----|----|
|equal, lesser, greater, greaterOrEqual, lesserOrEqual, not|[√](https://github.com/webmachinelearning/webnn-baseline/pull/55)|[pr](https://github.com/web-platform-tests/wpt/pull/43304)
|where|[pr](https://github.com/webmachinelearning/webnn-baseline/pull/56)|WIP
|copy|[√](https://github.com/webmachinelearning/webnn-baseline/pull/52)|[pr](https://github.com/web-platform-tests/wpt/pull/43177)
|reciprocal|[√](https://github.com/webmachinelearning/webnn-baseline/pull/53)|[pr](https://github.com/web-platform-tests/wpt/pull/43178)
|sqrt|[√](https://github.com/webmachinelearning/webnn-baseline/pull/54)|[pr](https://github.com/web-platform-tests/wpt/pull/43179)
|erf||
|expand|[pr](https://github.com/webmachinelearning/webnn-baseline/pull/57)|WIP
|gather||
|layerNormalization||
|reduceArgMin, reduceArgMax||
|cast||
|triangular||

/cc @inexorabletash @BruceDai @wchao1115 @fdwr @anssiko

**Comment by BruceDai** [comment]
Updated

|Ops| Baseline | WPT tests|
|----|----|----|
|equal, lesser, greater, greaterOrEqual, lesserOrEqual, not(logicalNot)|[√](https://github.com/webmachinelearning/webnn-baseline/pull/55)|[√](https://github.com/web-platform-tests/wpt/pull/43304)
|where|[√](https://github.com/webmachinelearning/webnn-baseline/pull/56)|[pr](https://github.com/web-platform-tests/wpt/pull/43558)
|copy(identity)|[√](https://github.com/webmachinelearning/webnn-baseline/pull/52)|[√](https://github.com/web-platform-tests/wpt/pull/43177)
|reciprocal|[√](https://github.com/webmachinelearning/webnn-baseline/pull/53)|[√](https://github.com/web-platform-tests/wpt/pull/43178)
|sqrt|[√](https://github.com/webmachinelearning/webnn-baseline/pull/54)|[√](https://github.com/web-platform-tests/wpt/pull/43179)
|erf|[pr](https://github.com/webmachinelearning/webnn-baseline/pull/59)|[pr](https://github.com/web-platform-tests/wpt/pull/43560)
|expand|[√](https://github.com/webmachinelearning/webnn-baseline/pull/57)|[pr](https://github.com/web-platform-tests/wpt/pull/43559)
|gather|WIP|
|layerNormalization|[pr](https://github.com/webmachinelearning/webnn-baseline/pull/60)|
|argMin, argMax||
|cast||
|triangular||
|constant(fillSequence)||
|reshape(squeeze,unsqueeze,flatten)||

**Comment by anssiko** [comment]
WPT for constant fillSequence https://github.com/web-platform-tests/wpt/pull/43801 and triangular https://github.com/web-platform-tests/wpt/pull/43794 merged.
