### ISSUE TITLE
The input of `triangular` should be at least 2D tensor

### ISSUE THREAD

**Issue by BruceDai** [webmachinelearning/webnn#494]
This is raised by @fdwr on reviewing implementation for `triangular` op on https://github.com/webmachinelearning/webnn-baseline/pull/64. (Thanks Dwayne!)

> it should say the input is at least 2D. You can see other ML libraries just treat each 2D subsection as a separate batch:
> 
> https://numpy.org/doc/stable/reference/generated/numpy.triu.html
> https://pytorch.org/docs/stable/generated/torch.tril.html
> https://onnx.ai/onnx/operators/onnx__Trilu.html
> 
> So shape [4,3,5,7] would apply the triangular masking to the last two dimensions.

**Comment by fdwr** [comment]
```diff
...

  Arguments:
- input: an [MLOperand](https://www.w3.org/TR/webnn/#mloperand). The input 2-D tensor.
+ input: an [MLOperand](https://www.w3.org/TR/webnn/#mloperand). The input tensor which is at least 2D.

   options: an optional [MLTriangularOptions](https://www.w3.org/TR/webnn/#dictdef-mltriangularoptions). The optional parameters of the operation.

- Returns: an [MLOperand](https://www.w3.org/TR/webnn/#mloperand). The output 2-D tensor representing a triangular matrix.
+ Returns: an [MLOperand](https://www.w3.org/TR/webnn/#mloperand). The output tensor representing a masked triangular matrix which is the same shape as the input.

...

+ // lower triangular matrix with two batches:
+ //   [[[7, 0, 0],
+ //     [9, 4, 0],
+ //     [2, 6, 3]],
+ //    [[1, 0, 0],
+ //     [4, 5, 0],
+ //     [7, 8, 9]]]
+ const lower = builder.triangular(input, { upper: false });
```

**Comment by BruceDai** [comment]
Thanks @fdwr !
I think you can create a PR for this!
