### ISSUE TITLE
Streamline context creation and validation algorithm definitions

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#498]
A handful of observations:

* The [validate MLContext](https://www.w3.org/TR/webnn/#validate-mlcontext) algorithm has 3 steps that confirm that the internal slots are valid. This could only fail if the spec was internally inconsistent or an implementation was non-compliant, so these don't add value to the spec. See also #455 So there's really only a single useful sentence in the algorithm: _If the user agent cannot support context.[[contextType]], context.[[deviceType]] and context.[[powerPreference]], return false._ 
* The [validate MLContext](https://www.w3.org/TR/webnn/#validate-mlcontext) algorithm is invoked in the [MLGraphBuilder constructor](https://www.w3.org/TR/webnn/#dom-mlgraphbuilder-mlgraphbuilder) where an MLContext is passed. This should not be necessary as the MLContext is already created, so there's no way for a non-valid context to be passed in.
* All other invocations of [validate MLContext](https://www.w3.org/TR/webnn/#validate-mlcontext) immediately follow an invocation of [create a context](https://www.w3.org/TR/webnn/#create-a-context). 

Synthesizing the above, we could eliminate [validate MLContext](https://www.w3.org/TR/webnn/#validate-mlcontext) and instead have [create a context](https://www.w3.org/TR/webnn/#create-a-context) include:

> If the user agent cannot support context.[[contextType]], context.[[deviceType]] and context.[[powerPreference]], return failure.

And then the four call sites could simplify to:

> Let context be the result of creating a context given options. If that returns failure, then reject promise with a "NotSupportedError" DOMException.

(All four are slightly different, given sync/async failure and options vs. gpuDevice arguments, but would simplify similarly.)

I'm happy to put up a PR for this. On the other hand, if I'm making a bad assumption somewhere above (e.g. construction of a non-valid context is possible), then we should add some explanatory notes into the spec!

**Comment by zolkis** [comment]
Good observations. In addition, we are carrying the [[context]] internal slot on various objects, and use it only in the compute() algorithms. 

> The [validate MLContext](https://www.w3.org/TR/webnn/#validate-mlcontext) algorithm is invoked in the [MLGraphBuilder constructor](https://www.w3.org/TR/webnn/#dom-mlgraphbuilder-mlgraphbuilder) where an MLContext is passed.

An object is passed - should we let implementations decide whether to check it's a valid MLContext?

**Comment by inexorabletash** [comment]
> An object is passed - should we let implementations decide whether to check it's a valid MLContext?

How would a non-valid MLContext be created? Or what can turn a valid MLContext into a non-valid MLContext?
