### ISSUE TITLE
Define "calculating output dimensions"

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#500]
Various graph builder methods (7 of them?) contain this or similar phrasing:

> Let outputShape be the result of invoking the underlying implementation for calculating output dimensions, given options.

Is this truly expected to be implementation dependent, or can it be rigorously specified on a per-op basis?

**Comment by huningxin** [comment]
I think the output shape inference should be implementation independent and be specified per-op. The spec mentions the output shape calculation for some ops. For example, 

for [Element-wise unary operations](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-unary)

> The shape of the output tensor is the same as the shape of input tensor.

for [conv2d](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-conv2d), 

> More specifically, the spatial dimensions or the sizes of the last two dimensions of the output tensor for the nchw input layout can be calculated as follow:

> outputSize = 1 + (inputSize - (filterSize - 1) * dilation - 1 + beginningPadding + endingPadding) / stride

They should be reflected in algorithm steps.
