### ISSUE TITLE
Drop  "The permissions and context validity have been checked..." notes

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#501]
A smattering of methods on MLGraphBuilder (build, buildSync, concat, constant, expand, and input) include this note at the start of their method steps:

> The permissions and context validity have been checked by [§ 7.7.1 MLGraphBuilder constructor](http://localhost:8000/#api-mlgraphbuilder-constructor) steps.

Presumably this applies to all methods of MLGraphBuilder, and it's unclear that it adds value. It's non-normative, so it's harmless, but... is it particularly meaningful for these methods -- and if so, why?

**Comment by zolkis** [comment]
For conciseness, we should indeed remove that.
