### ISSUE TITLE
Implement web platform tests for input validation steps

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#545]
The current WebNN web platform tests mainly focus on operator compute result (https://github.com/web-platform-tests/wpt/tree/master/webnn). There is a lack of test cases for input validation steps.

As @reillyeon mentioned in Chromium [CL-5231640 for lstm](https://chromium-review.googlesource.com/c/chromium/src/+/5231640/comment/b8ac1841_02d5974b/),

> it's important that we have a comprehensive test suite for the WebNN API which can be shared between backends in Chromium and with other browser vendors.

> For these tests in particular, they are exercising input validation steps that are part of the specification and I feel that they are more appropriately expressed as web platform tests.

/cc @BruceDai

**Comment by a-sully** [comment]
Does this require changes to the spec, or should this be a Chromium bug?

**Comment by huningxin** [comment]
@a-sully , I don't think this requires the spec change. I understand w-p-t is one deliverable of this WG. @anssiko , please correct me if I am wrong.

**Comment by anssiko** [comment]
That's correct. While test contributions go to the https://github.com/web-platform-tests/wpt repo we have used this WebNN spec repo to discuss non-trivial issues related to testing this API to guide test authors. These issues should be triaged with a  https://github.com/webmachinelearning/webnn/labels/testing label. The wpt repo is huge so any issues opened against it will get lost easily.

The relevant section in this WG's charter is [Other Deliverables](https://www.w3.org/2023/04/web-machine-learning-charter.html#ig-other-deliverables) that says:

>Test suite and implementation report for the specification;

**Comment by BruceDai** [comment]
I'm working to add validation tests on https://github.com/web-platform-tests/wpt/pull/44416.

**Comment by inexorabletash** [comment]
That PR landed - is there more work needed or can this be closed out?

**Comment by inexorabletash** [comment]
Tentatively closing, but please re-open (or file more scoped bugs) if there's specific work for any ops where we still need tests.

**Comment by inexorabletash** [comment]
While not perfect, these code coverage reports hint at some possible gaps:

- https://analysis.chromium.org/coverage/p/chromium/file?host=chromium.googlesource.com&project=chromium/src&ref=refs/heads/main&path=//services/webnn/public/cpp/graph_validation_utils.cc&platform=linux&test_suite_type=any&modifier_id=0
- https://analysis.chromium.org/coverage/p/chromium/file?host=chromium.googlesource.com&project=chromium/src&ref=refs/heads/main&path=//third_party/blink/renderer/modules/ml/webnn/ml_graph_builder.cc&platform=linux&test_suite_type=any&modifier_id=0 

Still, going ahead and closing.
