### ISSUE TITLE
Update the programming model section

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#549]
Review and update the [programming model](https://www.w3.org/TR/webnn/#programming-model) section to ensure it still reads well and is up to date with the rest of the specification. This section can be used as a place to define concepts that apply globally.

**Comment by inexorabletash** [comment]
Some terms that would be good to define:

* "tensor" and "shape"
* "connect", "input" and "output" (referenced in operand creation steps)

**Comment by inexorabletash** [comment]
If you're following this issue, please review: https://github.com/webmachinelearning/webnn/issues/572#issuecomment-1962198054

**Comment by anssiko** [comment]
Programming Model changes in https://github.com/webmachinelearning/webnn/issues/572#issuecomment-1962198054 LGTM.

**Comment by inexorabletash** [comment]
> Edit: Should we also say the nodes of the graph are connected by edges, represented by MLOperands? This is complementary to "MLOperands representing the data flow" but using graph theory language.

Updated to read: 

> An operator's input is one or more MLOperands representing the data flow for the computation, and are the edges of the graph. Operands include input values...

**Comment by inexorabletash** [comment]
@anssiko - now that #591 is merged, do you think we can close this out and have more specific issues if needed?
