### ISSUE TITLE
WebIDL definition for constant(start, end, step, type) is missing

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#571]
The range-based [constant(start, end, step, type)](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-constant-range) is defined with an [algorithm](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-constant-start-end-step-type), but there's no corresponding [WebIDL](https://webmachinelearning.github.io/webnn/#index) declaration for it.

**Comment by inexorabletash** [comment]
The prose implies it would be:

```webidl
    // Create an operand for a constant 1-D tensor of the specified type and range.
    MLOperand constant(float start, float end, float step, optional MLOperandDataType type = "float32");
```

... But I notice that constant(value, type) defines value as [double in the IDL](https://webmachinelearning.github.io/webnn/#ref-for-dom-mlgraphbuilder-constant-value-type) but [float in the prose](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-constant-value-type) (which, as an aside, is a good reason to NOT duplicate definitions manually). I assume it is double so that `int32`/`uint32` can be passed with full fidelity, so maybe this should be:

```webidl
    // Create an operand for a constant 1-D tensor of the specified type and range.
    MLOperand constant(double start, double end, double step, optional MLOperandDataType type = "float32");
```

... and then update the prose for this and the other constant() to say double.

**Comment by zolkis** [comment]
SGTM. @huningxin WDYT?

**Comment by huningxin** [comment]
We may also need to consider the int64 (bigint), as being discussed in https://github.com/webmachinelearning/webnn/issues/492#issuecomment-1926419539.

**Comment by inexorabletash** [comment]
Yeah... we could merge this with #492 (i.e. defer spec changes until the issues over there are sorted) or put in IDL for now and revisit as the API shape and int64 handling is resolved. Whatever the editors want!

**Comment by inexorabletash** [comment]
Marking this as a duplicate of #492 

(I had simply missed that other issue when filing this one, and it seems like we have traction there so a "quick fix" of just writing down the current IDL isn't needed.)
