### ISSUE TITLE
Synchronously validate input operands/activations

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#572]
When calling a builder method on [MLGraphBuilder](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder) that takes an [MLOperand](https://webmachinelearning.github.io/webnn/#api-mloperand) or [MLActivation](https://webmachinelearning.github.io/webnn/#api-mlactivation) as an input (i.e. anything but [input()](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-input) and [constant()](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-constant)), there is no check that the input is from the same builder. 

The only place in the spec that does this is [validate MLOperand](https://webmachinelearning.github.io/webnn/#mloperand-validate-mloperand) steps that take an operand and builder.

This algorithm is only called in:
* [concat()](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-concat) with _"If validating MLOperand given input and this returns false, then throw a "DataError" DOMException."_ which is bogus - it should pass input and this.[[builder]].
* [build()](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-build) asynchronously validates that the output operands are from the same builder, with _"If validating MLOperand given operand and this returns false, then reject promise with a TypeError, and abort these steps."_

@a-sully raised this in #552 and it was previously mentioned (but without specifics) in #234

Should failure here be synchronous? This is implied by the behavior of concat() and the open ended _"If any of the following sub-steps fail, ..."_ text in the builder methods. I don't see a reason for async failure (except in build itself, since you can't synchronously fail a method that returns a promise) so I'd strongly prefer synchronous failure. (If async, the build() should be augmented to traverse the whole graph.)

Assuming we want synchronous failure we could spec this in a few ways:

* Add explicit steps like concat() to all builder methods, e.g.: _If validating MLOperand given input and this.[[builder]] returns false, then throw a "DataError" DOMException._ - repeated for every input (required and optional if given). 
* Define steps for [connect](https://github.com/webmachinelearning/webnn/issues/549#issuecomment-1921901735) which validate and return failure; currently the builder method steps all already include _If any of the following sub-steps fail, throw an "OperationError" DOMException._

Either way, concat() needs to be aligned with the other methods (fix to pass this.[[builder]] or remove redundant steps)

This also raises the question of what exception type it should be:
* "DataError" DOMException, like concat(), or
* "OperationError" DOMException, like the substeps which include "connect", or
* TypeError, like build()

Additionally... is there anything other than "same builder" that's not currently validated, but that should be?

**Comment by inexorabletash** [comment]
If we wanted to go the "define connect" route, it might be something like:

> To connect an MLOperand _input_ as an input to MLOperand _target_:
> 1. If _input_.[[builder]] is not the same as _target_.[[builder]], return failure.
> 1. (any other validation?)
> 1. Add _input_.[[operand]] to _target_.[[operand]]'s inputs.
>
> To connect an MLOperand _output_ as an output to MLOperand _target_:
> 1. If _output_.[[builder]] is not the same as _target_.[[builder]], return failure.
> 1. (any other validation?)
> 1. Add _output_.[[operand]] to _target_.[[operand]]'s outputs.

Some "connect" phrases currently reference the _MLOperand_, and some reference the _platform operand_ instead; referencing the MLOperands consistently would simplify things.

**Comment by huningxin** [comment]
> Some "connect" phrases currently reference the MLOperand, and some reference the platform operand instead

When "connect" references the platform operand, such as [`relu(input)`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-relu-input) "3. Connect input.[[operand]] as input to opImpl.".

I suppose here it means a process of calling the native platform API to "connect" the platform operand to platform operator as input (or output). Actually, I think it should be a sub-step of "2. Make a request to the underlying platform to:".

> referencing the MLOperands consistently would simplify things.

Agreed. If we go this route, I think we should also define the "operator" concept within the spec. For a WebNN graph, MLOperands are edges, they need to be connected to nodes (operators), to construct a graph.

**Comment by a-sully** [comment]
I think it might be useful to think of these validation steps in tiers:

1. Platform-agnostic, op-agnostic checks

Currently this is specified as [validate MLOperand](https://webmachinelearning.github.io/webnn/#mloperand-validate-mloperand) and includes checks like that `MLOperand`s must be created from the same `MLGraphBuilder` to be connected; though as @inexorabletash hinted at, there may be more steps we want to throw into this bucket

2. Platform-agnostic, op-specific checks

These steps should _also_ be run (synchronously) for each `MLGraphBuilder` method. This includes checks like ensuring that constraints such as broadcasting requirements are met and the passed-in `MLActivation` is valid for the given op, as well as that the shapes expected by the `MLOperand`s being connected are valid.

3. Platform-specific, op-specific checks

This is where we finally talk to the platform API:

> I suppose here it means a process of calling the native platform API to "connect" the platform operand to platform operator as input (or output)

I propose that (1) and (2) should be run (synchronously) for each `MLGraphBuilder` method (and should throw a `TypeError`), while (3) should be deferred until (asynchronously) on `build()`. If we agree on this, then we should update each `MLGraphBuilder` method to follow this (very rough) patten:

___
The `foo(input, options)` method steps are:

1. Validate an `MLOperand` with a builder + `input` + this (else reject with `TypeError`)
2. Validate `foo` given `options`:
    1. Check `options` are valid (else reject with `TypeError`)
    2. etc... 
3. Connect with `input`
    1. Check shapes are valid (else reject with `TypeError`)
    2. etc...
    3. Add to `input`'s outputs
___
Or maybe:
___
The `foo(input, options)` method steps are:

1. Validate an `MLOperand` with a builder + `input` + this (else reject with `TypeError`)
2. Validate `foo` given `input` and `options`:
    1. Check `options` are valid (else reject with `TypeError`)
    2. Check shapes are valid (else reject with `TypeError`) 
    3. etc... 
5. Connect with `input`
    1. etc...
    2. Add to `input`'s outputs
___

Ideally (though there might be some quirks which make this not feasible) none of the `MLGraphBuilder` methods would require implementation-defined behavior, and all the "underlying platform" steps are pushed to `build()` (which currently also contains "connect" steps)

Thoughts?

**Comment by huningxin** [comment]
@a-sully , your proposal sounds good to me.

We may also consider validating the input' data type synchronously at build method, that should be op-specific check, as being captured by https://github.com/webmachinelearning/webnn/issues/283.

**Comment by inexorabletash** [comment]
FYI, we asked around for precedent for labeling blocks of substeps. https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering has some examples (italics before a clause), and our handy spec experts are not opposed to doing so if it improves readability. I like the idea of the "validate" and "connect" blocks, maybe "calculate output shape" as a block as well.

**Comment by huningxin** [comment]
> maybe "calculate output shape" as a block as well.

+1

**Comment by inexorabletash** [comment]
Building on the conversation above, here's a sketch of something concrete. If this looks like a decent starting point I can put up a PR for detailed nitpicks. 

- These define **operator** as internal concept
- MLOperand and MLActivation now hold operator, not platform operator
- MLOperand does not need to define/hold platform operand - that's deferred to build - #457
- new structure for MLOperand-vending methods that separates out validation, output shape, and connection
- "connect" goes away as a term.
- "register" goes away as a term for activations

## Programming Model / Overview

Replace bits about operands with the following:

> The `MLGraph` interface represents a compiled computational graph that is immutable (that is, a model).
> 
> The `MLGraphBuilder` interface serves as a builder (factory) to construct the computation graph that is then compiled to create an `MLGraph`. 
> 
> In WebNN, the computational graph is composed of **operators** which act on data, and are the nodes of the graph. An operator's **input** is one or more `MLOperand`s representing the data flow for the computation, which include input values, constants (including trained weights), and intermediate values (often referred to as activations). An operator's **output** is one or more `MLOperand`s, representing the output values of the computation. Operators have operator-specific parameters that control their behavior, which can include zero or more **activation functions**, which are `MLActivation`s. The operations have functional semantics, with no side effects. Each operation invocation conceptually returns a distinct new value, without changing the value of any other `MLOperand`.
> 
> A key part of the `MLGraphBuilder` interface are methods such as `gemm()` and `softmax()` which create an operator which represents actual operation to perform on the input data when the computation is run, and return a new `MLOperand` or `MLActivation` holding the operator. Methods that create an `MLOperand` connect any inputs and activations to the operator. 

Insert the following near the build() description:

> The `MLGraph` is composed of **platform operators** and **platform operands** which correspond to the operators and `MLOperand`s, but are not script-visible and MAY be compositions or decompositions of the graph as constructed by script.

## MLActivation interface
Update to slot description:

> [[operator]] of type **operator**
> Reference to MLActivation's corresponding operator.

## MLOperand interface
Update internal slot description:
> [[operator]] of type **operator**
> Reference to MLOperand's corresponding operator.

And delete [[operand]]

## Standard MLGraphBuilder Operand-vending Method Structure

**The whatever(input, options) method steps are:**

1. _Validate arguments:_
    1. If _input_.[[builder]] is not this, then throw a "DataError" `DOMException`.
    1. If _options_.scales does not exist, set it to the list « 1.0, 1.0 ».
    1. …
    1. If _options_.activation exists and _options_.activation.[[builder]] is not this, then throw a "DataError" `DOMException`.
    1. …
1. _Calculate the output shape:_
    1. Let _outputDescriptor_ be a new `MLOperandDescriptor`.
    1. Set _outputDescriptor_.dataType to _input_’s dataType.
    1. Set _outputDescriptor_.dimensions to the result of unidirectionally broadcasting the shapes _input_’s shape and _options_.newShape. If that returns failure, then throw a "DataError" `DOMException`.
    1. …
1. _Make graph connections:_ 
    1. Let _op_ be an operator for the "whatever" operation, given _options_.
    1. Let _output_ be the result of creating an MLOperand given this and _outputDescriptor_.
    1. If _options_.activation exists, then add it to _op_'s activation functions.
    1. Set _output_.[[operator]] to _op_.
    1. Set _op's_ input to _input_.
    1. Set _op's_ output to _output_.
1. Return _output_.

**Comment by a-sully** [comment]
This looks great to me!

There are a couple of things I notice about this framework which we should follow up on elsewhere:

- I think everything in steps 1 and 2 which may reject should do so with a `TypeError`, rather than a `DataError` (I can file a follow-up issue)
- This proposal removes all platform-specific behavior from all `MLGraphBuilder` operand-vending methods. All platform-specific checks are deferred until `build()`. This is related to #504, so discussions related to this topic should continue on that issue

**Comment by huningxin** [comment]
Thanks @inexorabletash ! The [proposal](https://github.com/webmachinelearning/webnn/issues/572#issuecomment-1962198054) looks great to me.

> * These define **operator** as internal concept

Could you please elaborate a bit how operator internal concept is defined? Is it an internal interface definition for a specific operation? For example, something like Chromium prototype's [`struct Conv2d`](https://source.chromium.org/chromium/chromium/src/+/main:services/webnn/public/mojom/webnn_graph.mojom;l=166) mojo definition?

**Comment by inexorabletash** [comment]
> Could you please elaborate a bit how operator internal concept is defined? Is it an internal interface definition for a specific operation? For example, something like Chromium prototype's [`struct Conv2d`](https://source.chromium.org/chromium/chromium/src/+/main:services/webnn/public/mojom/webnn_graph.mojom;l=166) mojo definition?

As sketched above, it's just describing the abstract concept of an operator. Like algorithms and internal slots, these spec concept objects are useful for defining behavior, but aren't script visible so only matching the observable behavior is required. But they very often do map 1:1 with implementations. That Conv2d example from the Chromium prototype impl is what this would map to.

**Comment by inexorabletash** [comment]
Remaining work following #591 

- [ ] Erroring if input's `[[builder]]` doesn't match `this`
- [ ] Introducing _"Validate arguments"_ section for each method.
- [ ] Introducing _"Calculate output shape"_ section for each method (maybe _"output descriptor"_ is better?)
- [ ] Rewording methods that vend MLActivations.
- [ ] Standard phrasing for "be an operator for ..." [details](https://github.com/webmachinelearning/webnn/pull/591#issuecomment-1970083381)

**Comment by inexorabletash** [comment]
For the "remaining work", namely:

*  Introducing "Validate arguments" section for each method.
*  Introducing "Calculate output shape" section for each method (maybe "output descriptor" is better?)

My suggestion is: add as needed, e.g. when a method's steps could be broken up to improve readability. But adding to all methods would just be clutter.
