### ISSUE TITLE
Revisiting use of partial interfaces

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#579]
Split off from #450

The spec currently uses "[partial interfaces](https://webidl.spec.whatwg.org/#dfn-partial-interface)" to keep IDL declarations of methods/attributes close to the definitions. From WebIDL:

> Partial interface definitions are intended for use as a specification editorial aide, allowing the definition of an interface to be separated over more than one section of the document, and sometimes multiple documents.

The WebNN spec takes this to a bit of an extreme - [MLContext](https://webmachinelearning.github.io/webnn/#mlcontext) and [MLOperand](https://webmachinelearning.github.io/webnn/#mloperand) are declared empty and only populated later by partials. [MLGraphBuilder](https://webmachinelearning.github.io/webnn/#mlgraphbuilder) is declared with a handful of methods but then primarily populated by partials. Like everything, this has benefits and disadvantages:

- Pro: keep IDL declarations of methods/attributes close to the definitions. 
- Pro: keep auxiliary IDL declarations (e.g. enums, dictionaries) close to the relevant methods
- Con: lots of extra noise in [IDL Index](https://webmachinelearning.github.io/webnn/#idl-index)
- Con: hard to see what's in types e.g. MLOperand and MLContext look like empty interfaces like MLActivation but aren't
- Con: MLGraphBuilder is inconsistent (has constructor(), input(), constant(), build() in main interface not partials)

I'd like to suggest some changes which I think maintain the primary benefits of the current approach but address some of the drawbacks:

**Suggestion 1:  Limit partial interface to MLGraphBuilder**

- Collapse MLOperand partials
- Collapse MLContext partials

We may also want to revisit the naming of [7.4.2. Asynchronous Execution](https://webmachinelearning.github.io/webnn/#api-mlcontext-async-execution) to include [compute()](url), which is otherwise missing from the TOC.

**Suggestion 2: Improve MLGraphBuilder consistency by either:**

- pull [input()](https://webmachinelearning.github.io/webnn/#ref-for-dom-mlgraphbuilder-input), [constant()](https://webmachinelearning.github.io/webnn/#ref-for-dom-mlgraphbuilder-constant) and [build()](https://webmachinelearning.github.io/webnn/#ref-for-dom-mlgraphbuilder-build%E2%91%A0) out, put in partial blocks near definitions; or
- move [input()](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-input) and [build()](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-build) definitions up near MLGraphBuilder, move [constant()](https://webmachinelearning.github.io/webnn/#ref-for-dom-mlgraphbuilder-constant) to partial; or
- move [input()](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-input) and [build()](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-build) and [constant()](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-constant) definitions up near MLGraphBuilder

Commentary:
- build() is the ultimate point and final step of using MLGraphBulder, so having it declared in the main interface definition seems important
- input() is usually the initial step of using MLGraphBuilder, so perhaps it should go into the main interface definition. But it vends an MLOperand so it could alternatively be grouped with the other methods.
- constant() could be seen as a static form of input(), or a special case MLOperand vendor. It could logically group either with input() or with other MLOperand vendors.

**Comment by anssiko** [comment]
@inexorabletash a PR would allow a side-by-side review to better assess pros and cons. If crafting a PR and possibly iterating on it is not too much work, it'd help a bunch here. Also, an almost empty PR queue would allow for a conflict-free operation.

Any changes that will unclutter IDL index are welcome. I suspect many new into this spec will go into that section first to get the big picture.
