### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by xfq** [webmachinelearning/webnn#604]
The [NSNet2](https://github.com/microsoft/DNS-Challenge/tree/master/NSNet2-baseline) link is 404 in https://github.com/webmachinelearning/webnn/blob/main/explainer.md#key-scenarios .

**Comment by anssiko** [comment]
It looks like NSNet2-baseline directory was removed in https://github.com/microsoft/DNS-Challenge/commit/d1bcd6927beed89774e50404d4da2fa46b0d8f47

@fdwr or @wchao1115 might know if that model lives somewhere else now or whether it would be appropriate to replace NSNet2 with some other model and update the explainer accordingly.

**Comment by fdwr** [comment]
🤔 The CR which removed them has no details (random spring cleaning?). I found a few other places that have a version of NSNet2, but they are Python or C-based, not ONNX models, and they point to the same URL too (now 404). Also, the Arxiv papers seem *related* but not specific to it (e.g. https://arxiv.org/abs/2008.06412). So, we could just fix the link point to https://github.com/microsoft/DNS-Challenge/tree/a052ad5a7714bcc6069b515666e837bf973099de/NSNet2-baseline .

**Comment by anssiko** [comment]
@fdwr thanks for checking, PTAL https://github.com/webmachinelearning/webnn/pull/617 and merge at will.
