### ISSUE TITLE
Need clarify the maximum limit of the hidden size of the Gru operator

### ISSUE THREAD

**Issue by miaobin** [webmachinelearning/webnn#625]
WebNN defines two parameters bias and recurrent bias for Gru operator. Their shapes are [numDirections, 3 * hiddenSize], but in some backends like [DirectML](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_gru_operator_desc) only defines one bias and the shape is [1, 1, numDirections, 6 * hiddenSize] ], 6*hiddenSize needs to be verified at this time.
We are currently validate it in backed side, but in order to avoid surprise build failures for web developers, we hope to validate and throw error in the verification layer. So should this limit be part of the spec and validated for all backends?
Link to chromium [CL discussion](https://chromium-review.googlesource.com/c/chromium/src/+/5339174/comment/d4ee35e1_89a13efe/).

**Comment by inexorabletash** [comment]
Somewhat related spec issue:

Currently, the spec validates that 3*hiddenSize is a valid dimension implicitly by comparing it against bias's and recurrentBias's second dimension. Implicitly, if bias is an MLOperand, then it's dimensions are valid, and so if 3*hiddenSize is equal to the second dimension then it's also a valid dimension. But if neither bias nor recurrentBias are passed, then no validation is done!

**Comment by inexorabletash** [comment]
This issue seems to apply to lstm as well ([chromium impl](https://source.chromium.org/chromium/chromium/src/+/main:services/webnn/dml/graph_impl.cc;l=3539)) - DML takes [1, 1, direction_count, 8 * hidden_size]

Also, the impl (and thus this issue) applies to gru + gruCell, and lstm + lstmCell
