### ISSUE TITLE
Need Gelu operation

### ISSUE THREAD

**Issue by mingmingtasd** [webmachinelearning/webnn#626]
**Use Case:**
`Gelu` performs the gaussian error linear unit (GELU) activation function: `f(x) = 0.5 * x * (1.0 + erf(x / sqrt(2)))`.
Some transformer models such as the [whisper base](https://huggingface.co/openai/whisper-base) contain decomposed small ops like `Add`, `Div`, `Erf`, `Mul` following the `MatMul` and `Conv` operations. These small ops can be composed as a higher level operation `Gelu`.
Furthermore, the `Gelu` can also be fused into the operations like  `MatMul` and `Conv` , it has been confirmed that the fusion can significantly improve the performance of a graph's execution at least on DirectML backend.

**Sample models:**
[whisper base](https://huggingface.co/openai/whisper-base)

**Cross-framework support:**
[ONNX](https://onnx.ai/onnx/operators/onnx__Gelu.html), [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/nn/gelu), [PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.GELU.html)

**Cross-platform implementability:**
[CoreML](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.activation.gelu), [DirectML](https://learn.microsoft.com/en-us/windows/ai/directml/api/ns-directml-dml_activation_gelu_operator_desc), [OpenVINO](https://docs.openvino.ai/2023.3/openvino_docs_ops_activation_GELU_7.html), 

So I propose this new operation to WebNN Spec, my PR is WIP. @huningxin @fdwr

**Comment by zolkis** [comment]
Paper: https://arxiv.org/abs/1606.08415v5

**Comment by huningxin** [comment]
Sample transformer models using `Gelu` also include [Stable Diffusion UNet](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/onnx/unet) and [Segment Everything decoder](https://github.com/fdwr/segment-anything/blob/main/demo/model/sam_onnx_example.onnx).

**Comment by fdwr** [comment]
This complements the existing `elu`, `relu`, `prelu`:

We'll need the decomposition for the spec...
```
return builder.mul(
    builder.mul(x, builder.constant(0.5)),
    builder.add(
        builder.constant(1.0),
        builder.erf(
            builder.div(
                x,
                builder.sqrt(builder.constant(2))
            )
        )
    )
```

...and a tolerance, at least 18 ULP depending on the erf implementation.

**Comment by mingmingtasd** [comment]
> This complements the existing `elu`, `relu`, `prelu`
> ...and a tolerance, at least 18 ULP depending on the erf implementation.

Yes! And also cc/ @BruceDai  for the tolerance information.
