### ISSUE TITLE
Need to add the value restriction of output padding in convTranspose2d

### ISSUE THREAD

**Issue by mei1127** [webmachinelearning/webnn#630]
(This was raised by @ningxin Chromium [CL-5398742](https://chromium-review.googlesource.com/c/chromium/src/+/5398742) review.)

WebNN's [convTranspose2d](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-convtranspose2d): The current spec doesn't mention the value restriction of output padding, the chromium implementation requires "The output padding must be smaller than the stride along the same dimension." [1](https://source.chromium.org/chromium/chromium/src/+/main:components/ml/webnn/graph_validation_utils.cc;l=122)

**Comment by inexorabletash** [comment]
In the Chromium implementation, it looks like the `outputPadding` validation is done only if `outputSizes` is not specified.
