### ISSUE TITLE
Consider changing output type of ArgMax/Argmin to int32, or allow passing output_type

### ISSUE THREAD

**Issue by philloooo** [webmachinelearning/webnn#653]
Currently WebNN specifies ArgMax/Min returns [int64](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-argminmax).
- [CoreML](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS17.reduction.reduce_argmin) supported return type is int32 or uint16. 
- [tflite](https://www.tensorflow.org/mlir/tfl_ops#tflarg_max_tflargmaxop) supports int32, int64.
- [dml](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_argmax_operator_desc) supports int32, int64, uint32, uint64.

Returning int64 can't be emulated on CoreML:
- the [cast](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.elementwise_unary.cast) operator only supports casting to fp16, fp32, i32, bool.
- None of the operations support int64 as input(so the output of argMax/argMin can't be connected to the next layer if it's int64)
- Graph output doesn't support i64. Only fp16, fp32, i32 is supported.

Given int32 is the intersection across these backends, I see two options to make it work:
a. Update argMin/Max to always output int32
b. On the spec level, allow passing a param of `output_type`. And allow probing the supported data types for this param.

**Comment by philloooo** [comment]
Following up from the [working group meeting](https://www.w3.org/2024/05/02-webmachinelearning-minutes.html), I am happy to explore option 2 if @fdwr  can provide examples on when int64 is useful. 

I didn't fully understand your `gather` example, because I actually don't understand why `indices` allow both int64 and uint32. The indices should point to valid indices that's within MLOperand's dimensions right? And the [dimensions](https://www.w3.org/TR/webnn/#dictdef-mloperanddescriptor) are uint32...

**Comment by fdwr** [comment]
Mirroring this table here too for historical reference:

API | uint32 | int32 | uint64 | int64 | Link
-|-|-|-|-|-
DML | uint32 | int32 | uint64 | int64 | [DML_ARGMIN_OPERATOR_DESC](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_argmin_operator_desc)
TF output_type | - | int32 | - | int64 | [tf.math.argmin](https://www.tensorflow.org/api_docs/python/tf/math/argmin)
CoreML | - | int32 | - | - | [reduction.reduce_argmin](https://apple.github.io/coremltools/source/coremltools.converters.mil.mil.ops.defs.html#coremltools.converters.mil.mil.ops.defs.iOS15.reduction.reduce_argmin)
MLIR TOSA | uint32 | - | - | - | [tosa.argmax](https://mlir.llvm.org/docs/Dialects/TOSA/#tosaargmax-mlirtosaargmaxop) "signless integer"
ONNX | - | - | - | int64 | [ArgMin](https://onnx.ai/onnx/operators/onnx__ArgMin.html)
PyTorch | - | - | - | int64 | [torch.argmin](https://pytorch.org/docs/stable/generated/torch.argmin.html)
NumPy | - | - | - | int64 | [numpy.argmin](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html)
