### ISSUE TITLE
"Unidirectionally broadcast the shapes" steps have issues

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#662]
The current [unidirectionally broadcasting the shapes](https://www.w3.org/TR/webnn/#unidirectionally-broadcasting-the-shapes) steps don't allow `sizeA` < `sizeB` according to the following step

> If sizeB > sizeA, then return failure.

And the steps should pad `shapeA`, the current steps pad `shapeB` instead

> Let paddedB be a [clone](https://infra.spec.whatwg.org/#list-clone) of shapeB.
> While paddedB’s [size](https://infra.spec.whatwg.org/#list-size) is less than sizeA, [prepend](https://infra.spec.whatwg.org/#list-prepend) 1 to paddedB.

This would cause the following examples to fail
1. ShapeA `[]`, ShapeB `[3, 4, 5]`
2. shapeA `[5]`, shapeB `[3, 4, 5]`

When creating the output shape, the steps should use `dimB`. The current step uses `dimA`:

> [Append](https://infra.spec.whatwg.org/#list-append) dimA to outputShape. 

This would produce incorrect output shape. For example, assume ShapeA `[3, 1, 5]`, ShapeB `[3, 4, 5]`, the output shape should be `[3, 4, 5]`, the current steps produce `[3, 1, 5]`.

**Comment by inexorabletash** [comment]
Did I just get the inputs inverted?

**Comment by huningxin** [comment]
@inexorabletash 

> Did I just get the inputs inverted?

It seems. But the following step is correct:

> If dimA is not equal to dimB and dimA is not equal to 1, then return failure.

I am making a PR to fix it, will upload soon.
