### ISSUE TITLE
Reconsider `MLOperand` methods

### ISSUE THREAD

**Issue by a-sully** [webmachinelearning/webnn#666]
The [`MLOperand`](https://webmachinelearning.github.io/webnn/#mloperand) interface looks like:

```diff
interface MLOperand {
  MLOperandDataType dataType();
  sequence<unsigned long> shape();
};
```

Each of these methods meets the criteria for being an attribute (https://w3ctag.github.io/design-principles/#attributes-vs-methods), and are [const](https://crsrc.org/c/third_party/blink/renderer/modules/ml/webnn/ml_operand.h;l=114-116;drc=53c1d06fee5a3e98e7f265419f6f84df2c2c2d62) once the `MLOperand` is constructed. Is we are to have an accessor on `MLOperand` for each key in the `MLOperandDescriptor` which created it, then these should be `readonly attribute`s.

That being said, once we open this can of worms, there are several options we could choose from:

### 1. Getter which returns an `MLOperandDescriptor`

```diff
interface MLOperand {
-  MLOperandDataType dataType();
-  sequence<unsigned long> shape();
+  MLOperandDescriptor descriptor();
};
```

This is my preferred option. Unfortunately, JavaScript dictionaries are not read-only so (unless we want to push to introduce `FrozenDictionary`) we should use a getter.

### 2. Naive conversion to `readonly attribute`

```diff
interface MLOperand {
-  MLOperandDataType dataType();
+  readonly attribute MLOperandDataType dataType;
-  sequence<unsigned long> shape();
+  readonly attribute sequence<unsigned long> shape;
};
```

Seems reasonable. But why have an attribute called `shape` which refers to the same thing as `MLOperandDescriptor.dimensions`?

### 3. Rename `shape` to `dimensions`, or vice versa

```diff
dictionary MLOperandDescriptor {
  required MLOperandDataType dataType;
-  sequence<[EnforceRange] unsigned long> dimensions = [];
+  sequence<[EnforceRange] unsigned long> shape = [];
};

interface MLOperand {
-  MLOperandDataType dataType();
+  readonly attribute MLOperandDataType dataType;
-  sequence<unsigned long> shape();
+  readonly attribute sequence<unsigned long> shape;
};
```

`MLOperandDescriptor` takes a `dimensions` field, while querying this field from an `MLOperand` is done with the `shape()` method. As per https://w3ctag.github.io/design-principles/#attribute-reuse, we should re-use terms rather than unnecessarily introducing new vocabulary.

A quick CTRL-F of the spec text shows:
- 139 instances of "dimensions", mostly due to `MLOperandDescriptor.dimensions`
- 483 instances of "shape", which seems to be used more commonly in prose (e.g. "the shape of the input tensor")

We should decide to use one or the other (and possibly continue this discussion on another issue regardless)

### 4. Make `MLOperandDescriptor` an `interface`

```diff
-dictionary MLOperandDescriptor {
+interface MLOperandDescriptor {
  required MLOperandDataType dataType;
  sequence<[EnforceRange] unsigned long> dimensions = [];
};

interface MLOperand {
-  MLOperandDataType dataType();
-  sequence<unsigned long> shape();
+  readonly attribute MLOperandDescriptor descriptor;
};
```

This is my least favorite, but I figured I'd list this here for completeness.

**Comment by zolkis** [comment]
m2c: 3(2|1) 
(3 applied to 2 or 1) :)

**Comment by a-sully** [comment]
I agree that we should do (3) regardless. Filed #669 to track that

Also filed #670 to track making `MLOperandDescriptor.dimensions` frozen. We should do this anyways, but especially if we're providing a getter that returns an `MLOperandDescriptor` then it would be nice if the array was frozen!

Given those expected improvements, my preference is (1)

**Comment by inexorabletash** [comment]
Re: (2) - sequences are disallowed as the type of an attribute: https://webidl.spec.whatwg.org/#idl-sequence

> This restriction exists so that it is clear to specification writers and API users that sequences are copied rather than having references to them passed around.

... which is a shame as a method does seem like overkill.

**Comment by fdwr** [comment]
> 3. Rename shape to dimensions

Doh, as a fan of internal consistency in API's, I should have originally proposed `dimensions()` [here](https://github.com/webmachinelearning/webnn/issues/375#issuecomment-1674224992) for consistency 🤦‍♂️.

```diff
interface MLOperand {
  MLOperandDataType dataType();
- sequence<unsigned long> shape();
+ sequence<unsigned long> dimensions();
}
```

🤔 Grammatically, `dimensions` are a nice fit ("a measurable extent of some kind, such as length, breadth, depth, or height ... the final dimensions of the pond were 14 ft. x 8 ft"), as that's exactly what they are. That list of dimensions can represent many different shapes, from a point to square to rectangular prism to tesseract... The word `shape` though is more ambiguous because it is both quite open ended (triangles and circles are valid shapes, but they are not valid shapes in an `MLOperand`) while also not being as precise (a triangle of any size is still a triangle, and so "shape" doesn't imply size, whereas dimensions literally are sizes).

From a compatibility impact perspective (thinking back to just how much change it was to rename "type" to "dataType" a half year ago), it would be much less impactful to rename `shape()` to `dimensions()` than to rename `dimensions` to `shape`, since the helper function isn't called anywhere nearly as often as `MLOperandDescriptor`'s are declared.

**Comment by fdwr** [comment]
p.s. Let's also be consistent in...

```
interface MLTensor {
  readonly attribute MLOperandDataType dataType;
  readonly attribute FrozenArray<unsigned long> dimensions;
}
```

**Comment by a-sully** [comment]
Hmm I'm still inclined to prefer `shape` over `dimensions` for the following reasons:

- "dimensions" is ambiguous, since it can mean "some number of dimensions" (e.g. "the last two dimensions") or "shape" (e.g. `[3, 4]`). Consider this paragraph from the description of [Broadcasting](https://www.w3.org/TR/webnn/#algorithms-broadcasting) (emphasis mine):
  > The simplest example is the application of a scalar constant to an N-dimension tensor with element-wise binary operations such as [add()](https://www.w3.org/TR/webnn/#dom-mlgraphbuilder-add) or [mul()](https://www.w3.org/TR/webnn/#dom-mlgraphbuilder-mul). Rather than needing to allocate and populate a matching N-dimensional tensor containing multiple copies of the scalar constant, these element-wise operations allow the scalar constant to be used directly, and broadcast the scalar value across the N-dimensional tensor. _**With the following considerations, the same logic applies to tensors of other dimensions.**_

  Which definition of "dimensions" is being used here? Should the more precise term "ranks" be used here (if it's the former definition)? Or is this referring to "tensors of other shapes" (the latter)?
- `shape` is widely used by other ML frameworks
  - numpy's [ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)
  - CoreML's [`MLMultiArray`](https://developer.apple.com/documentation/coreml/mlmultiarray/shape)
  - [TF uses "shape"](https://www.tensorflow.org/guide/tensor#about_shapes) and TFLite includes a [`shape()` operator](https://www.tensorflow.org/mlir/tfl_ops#tflshape_tflshapeop)
- > From a compatibility impact perspective... it would be much less impactful to rename `MLOperand::shape()` to `MLOperand::dimensions()` than to rename `MLOperandDescriptor::dimensions` to `MLOperandDescriptor::shape`

  I agree, which is why I think we should make this change while WebNN is still experimental :)

**Comment by a-sully** [comment]
> Hmm I'm still inclined to prefer `shape` over `dimensions`

I forgot I'd filed a separate issue about this! Please feel free to respond on #669 :) 

Regardless of what we name that field, at this point I'm quite convinced we should convert the getter methods on `MLOperand` to readonly attributes, in line with [the `MLTensor` interface currently implemented in Chromium ](https://chromium.googlesource.com/chromium/src/+/main/third_party/blink/renderer/modules/ml/webnn/ml_tensor.idl) and proposed in #754 

```diff
interface MLOperand {
-  MLOperandDataType dataType();
+  readonly attribute MLOperandDataType dataType;
-  sequence<unsigned long> shape();
+  readonly attribute FrozenArray<unsigned long> shape;
};
```

**Comment by fdwr** [comment]
> Regardless of what we name that field, at this point I'm quite convinced we should convert the getter methods on MLOperand to readonly attributes

@a-sully I'm not opposed to that (fewer parentheses to type), but what of Anssi's comment here? https://github.com/webmachinelearning/webnn/issues/670#issuecomment-2132861413

> The WebIDL spec is considering removing support for FrozenArray<T> as a dictionary member type: https://github.com/whatwg/webidl/issues/1399

**Comment by a-sully** [comment]
> @a-sully I'm not opposed to that (fewer parentheses to type), but what of Anssi's comment here? [#670 (comment)](https://github.com/webmachinelearning/webnn/issues/670#issuecomment-2132861413)
> 
> > The WebIDL spec is considering removing support for FrozenArray as a dictionary member type: [whatwg/webidl#1399](https://github.com/whatwg/webidl/issues/1399)

In this case we're using `FrozenArray` as a `readonly attribute`, so that's not relevant here. It would have potentially been relevant to this option:

> ### 1. Getter which returns an `MLOperandDescriptor`

**Comment by fdwr** [comment]
@a-sully: Do you consider this one complete, now that the struct looks like:

```
dictionary MLOperandDescriptor {
  required MLOperandDataType dataType;
  required sequence<[EnforceRange] unsigned long> shape;
};
```
https://www.w3.org/TR/webnn/#api-mloperanddescriptor

**Comment by a-sully** [comment]
I'm now happy with `MLOperandDescriptor` 👍 

As I mentioned in https://github.com/webmachinelearning/webnn/issues/666#issuecomment-2342019337, I still think the `MLOperand` interface needs to change:

> ... we should convert the getter methods on `MLOperand` to readonly attributes, in line with [the `MLTensor` interface currently implemented in Chromium ](https://chromium.googlesource.com/chromium/src/+/main/third_party/blink/renderer/modules/ml/webnn/ml_tensor.idl) and proposed in #754
> 
> ```diff
> interface MLOperand {
> -  MLOperandDataType dataType();
> +  readonly attribute MLOperandDataType dataType;
> -  sequence<unsigned long> shape();
> +  readonly attribute FrozenArray<unsigned long> shape;
> };
> ```
