### ISSUE TITLE
Remove use of `null` as parameter to `reshape` in code examples

### ISSUE THREAD

**Issue by a-sully** [webmachinelearning/webnn#667]
#388 proposed removing this capability and the corresponding PR merged in #601, but forgot to update the code examples!

What should the `null` value be in each of these examples?

- [`batchNormalization` example](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-batchnormalization): https://github.com/webmachinelearning/webnn/blob/9f0f45a80da91b5d10913d89be20707cef39cfc1/index.bs#L1563-L1572
- [`instanceNormalization` example](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-instancenormalization): https://github.com/webmachinelearning/webnn/blob/9f0f45a80da91b5d10913d89be20707cef39cfc1/index.bs#L3608-L3617
 - [`lstm` example](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-lstm) (3x): https://github.com/webmachinelearning/webnn/blob/9f0f45a80da91b5d10913d89be20707cef39cfc1/index.bs#L4107
 - [`gru` example](https://webmachinelearning.github.io/webnn/#dom-mlgraphbuilder-gru) (2x): https://github.com/webmachinelearning/webnn/blob/9f0f45a80da91b5d10913d89be20707cef39cfc1/index.bs#L3151-L3157

**Comment by inexorabletash** [comment]
With only medium confidence:

* For batchNormalization, null should be replaced with `input.shape()[options.axis]`
* For instanceNormalization, null should be replaced with `input.shape()[1]` (given that the example assumes "nchw")
* For lstm and gru, I believe all instances of null should be replaced with `batchSize` (i.e. `input.shape()[0]`)
