### ISSUE TITLE
Meta: Introduce "Interop" label?

### ISSUE THREAD

**Issue by inexorabletash** [webmachinelearning/webnn#673]
While doing triage, I noticed a cluster of issues that relate to inconsistencies between different underlying platforms/backends, e.g. DirectML, CoreML, TFLite, XNNPACK, etc.

- general:
  - #668
  - #658
  - #590
  - #489
  - #456
  - #391    
- op-specific:
  - #654
  - #653
  - #652
  - #629
  - #487
  - #481
  - #444
  - #396
  - #392
  - #383
  - #324
  - #180

Forward progress on resolving these requires considerations such as:

- Does WebNN support only the "lowest common denominator" behavior?
- Does WebNN require support, and implementations must work around backend limitations?
- Should behavior differences be allowed, and WebNN defines what is permitted (e.g. that options may just be a hint)
- #463

This was brought up in the [2024-05-02 WG telecon](https://github.com/webmachinelearning/meetings/blob/main/telcons/2024-05-02-wg-agenda.md), @anssiko suggested a meta-issue for follow-up

**Comment by anssiko** [comment]
Thanks @inexorabletash. I've put up a PR #682 and hearing no concerns I recommend we adopt this label to help contributors navigate the issue list.

It is rather easy to split/merge/rename labels if we find out later we want to e.g. further split these interop issues into specialized chunks such as https://github.com/webmachinelearning/webnn/labels/webgpu%20interop that coexists with this one.

**Comment by anssiko** [comment]
Reopened to be closed when my triage team friend @inexorabletash has assigned the labels :-)

**Comment by inexorabletash** [comment]
@anssiko - it might be easier for you to do it. If you go to https://github.com/webmachinelearning/webnn/issues?q=is%3Aissue+is%3Aopen+654+653+652+629+487+481+444+396+392+383+324+180+668+658+623+590+489+456+391 does your issue list have a checkbox column on the left, allowing you to apply labels to multiple issues at once? Apparently while I can apply labels to one issue at a time I can't bulk-assign labels.

I have that checkbox for repos I'm an Admin on (like https://github.com/w3c/IndexedDB) but not WebNN (where I have Triage)

**Comment by inexorabletash** [comment]
Never mind - I ended up doing it manually.  Closing this!
