### ISSUE TITLE
Failed to execute 'createContext' on 'ML': DirectML: Unable to find a capable adapter.

### ISSUE THREAD

**Issue by josefhernandez** [webmachinelearning/webnn#701]
Trying to execute the "Noise suppression (MSNet2)" in windows chrome Versión 125.0.6422.142 (Build oficial) (64 bits)

**Comment by huningxin** [comment]
@josefhernandez thanks for trying WebNN! 

> Trying to execute the "Noise suppression (MSNet2)" in windows chrome Versión 125.0.6422.142 (Build oficial) (64 bits)

Do you mean WebNN "Noise suppression (MSNet2)" sample: https://webmachinelearning.github.io/webnn-samples/nsnet2/index.html? It works for me on that Chrome version. Please note WebNN DirectML backend on Windows requires DirectML Feature Level 4.0+ which is available on Windows 11 21H2 or later. Check out more information at: https://learn.microsoft.com/en-us/windows/ai/directml/dml-version-history

This repo is for spec discussion. I am closing this issue. If you still meet issues, feel free to open an issue against webnn-samples repo: https://github.com/webmachinelearning/webnn-samples/issues/new.
