### ISSUE TITLE
Make `MLOperandDescriptor.shape` a `required` dictionary member

### ISSUE THREAD

**Issue by a-sully** [webmachinelearning/webnn#758]
Follow-up to #669. Proposed diff:

```diff
dictionary MLOperandDescriptor {
  required MLOperandDataType dataType;
-  sequence<[EnforceRange] unsigned long> shape = [];
+  required sequence<[EnforceRange] unsigned long> shape;
};
```

`MLOperandDescriptor.shape` is currently optional and defaults to a scalar. This may lead to hard-to-track-down bugs, which I've been personally bitten by!

From @reillyeon on [this comment](https://chromium-review.googlesource.com/c/chromium/src/+/5502631/comment/b7760f50_abb7c077/):

> [Requiring this member will] make declaring scalars more verbose but I think on the whole it seems like a good idea to help developers avoid mistakes.

**Comment by a-sully** [comment]
This is especially relevant in light of `MLOperandDescriptor.dimensions` being renamed to `MLOperandDescriptor.shape` (in #669). Callers who pass a `dimensions` field will see their code break, as the `dimensions` member will silently be ignored.

This alone is not sufficient reason for making `shape` required, though if we agree this is a good change then it would be nice to make it in tandem with #669!

**Comment by fdwr** [comment]
I wonder why it had an optional default to begin with? 🤔 Maybe it was for simple scalar constants, but with the `constant` overload that takes an `MLNumber`, this may default not be useful anymore.

**Comment by huningxin** [comment]
> I wonder why it had an optional default to begin with?

The optional default was for creating a scalar descriptor. I agreed making it required would be less error-prone.

**Comment by a-sully** [comment]
Put up #764. PTAL!

I'd like to merge the corresponding Chromium change in tandem with removing our grace-period-support for `dimensions` (so, about a milestone from now) so that anyone who hasn't migrated will break loudly rather than quietly. That shouldn't stop us from making the spec change now, though :)
