### ISSUE TITLE
Debug pr-preview issues

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#78]
From https://github.com/webmachinelearning/webnn/pull/76:

>@anssiko Is there anyone who can help us getting the pr-preview bot back in working state? It's more convenient for the reviewers to have the bot update the preview automatically when a new commit arrives.

@wchao1115 Markdown is not supported by pr-preview currently.

That said, I think I fixed pr-preview for bikeshed (.bs) by reinstalling the GitHub pr-preview integration (aka [GitHub App](https://developer.github.com/apps/)), here's an example of it working: https://github.com/webmachinelearning/webnn/pull/77

FTR: In an attempt to fix it, I first tried updating .pr-preview.json to its [latest version](https://github.com/webmachinelearning/webnn/commit/04792128cf789a058811b963eae4ba0200e7977d) in the webnn repo but that caused the whole webmachinelearning GH org to throw Internal Server Error 500 octocat so I quickly [reverted to the old config](https://github.com/webmachinelearning/webnn/commit/de52dae24234eba91e0190a0a65bfc76f01832b2), uninstalled, and reinstalled the integration and things _seem_ to be working now. Fingers crossed.

FYI @tobie just in case someone else sees similar behavior.

@wchao1115 @huningxin If the webmachinelearning repos start to misbehave and throw 500 errors and I'm not around, also @huningxin can uninstall the integration via https://github.com/organizations/webmachinelearning/settings/installations to fix the immediate issue.

Edit: Let's consolidate all webnn repo pr-preview issues here so we keep track, and when the root cause has been identified open an issue upstream.

**Comment by tobie** [comment]
> FTR: In an attempt to fix it, I first tried updating .pr-preview.json to its latest version in the webnn repo but that caused the whole webmachinelearning GH org to throw Internal Server Error 500 octocat so I quickly reverted to the old config, uninstalled, and reinstalled the integration and things seem to be working now. Fingers crossed.

The only difference between the two configs is an extra parameter added to the URL of the server responsible for building the bikeshed app that causes fatal errors to be swallowed. Unless the config file is used outside of PR Preview, I can’t explain the observed behavior.

**Comment by anssiko** [comment]
Thanks for chiming in @tobie. We'll observe the behavior and update this issue as we find more. If we can repro with documented steps in a controlled environment we open an issue for your upstream pr-preview repo.

**Comment by tobie** [comment]
The only possible explanation I could find would be if you main branches are failing. So filed https://github.com/tobie/pr-preview/issues/77 for that.

**Comment by huningxin** [comment]
Thanks @anssiko and @tobie , I'll follow up as your suggestions.

**Comment by anssiko** [comment]
My Server Error 500 octocat moments are correlated in time with https://www.githubstatus.com/incidents/d60fmldlvw48 so this leads me to believe the GitHub misbehavior yesterday was unrelated to pr-preview.

**Comment by anssiko** [comment]
I haven't heard of any pr-preview issues since June, so I'm happy to close this one.
