### ISSUE TITLE
`MLGraphBuilder.constant()` should take an `AllowSharedBufferSource`

### ISSUE THREAD

**Issue by a-sully** [webmachinelearning/webnn#788]
Currently, `constant()` takes an `ArrayBufferView` (https://www.w3.org/TR/webnn/#ref-for-dom-mlgraphbuilder-constant)

`AllowSharedBufferSource` is specified [here](https://webidl.spec.whatwg.org/#AllowSharedBufferSource) as the following:
```
typedef (ArrayBuffer or SharedArrayBuffer or [AllowShared] ArrayBufferView) AllowSharedBufferSource;
```

Since this buffer data is always immediately copied (https://www.w3.org/TR/webnn/#dom-mlgraphbuilder-constant) I see no reason why we shouldn't allow passing an `ArrayBuffer`, `SharedArrayBuffer` or shared `ArrayBufferView` to this method, as well.

**Comment by huningxin** [comment]
Yes, it should support `SharedArrayBuffer`. 

The current restriction prevents a multi-threaded build of Wasm framework, e.g. ONNXRuntime Web, from passing memory views ([emscripten::typed_memory_view](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#memory-views)) to `MLGraphBuilder.constant()`, that is unfortunate.
