### ISSUE TITLE
Uncaught (in promise) NotSupportedError: Failed to execute 'createContext' on 'ML': DirectML: WebNN is blocklisted for NPU.

### ISSUE THREAD

**Issue by sandeepks1** [webmachinelearning/webnn#798]
Can some one help me to fix this issue 
**Uncaught (in promise) NotSupportedError: Failed to execute 'createContext' on 'ML': DirectML: WebNN is blocklisted for NPU.**

Getting the above error when i try webnn code from intel based AI PC.

Thanks
Sandeep

**Comment by huningxin** [comment]
@sandeepks1 , you may need to install the latest NPU driver. Some old NPU drivers have issues and are blocklisted. Feel free to checkout [Running WebNN on NPU guide of webnn-samples](https://github.com/webmachinelearning/webnn-samples?tab=readme-ov-file#running-webnn-on-npu). 

This repo is for WebNN spec discussion. If you still have issues when running WebNN code in browsers, you may want to open issues against browser WebNN implementation, e.g. for Chromium: https://issues.chromium.org/issues/new?component=1456206&template=0. Thanks!
