### ISSUE TITLE
high level, low level - confusing naming

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [webmachinelearning/webnn#8]
As it is separate topic I've made this issue as a continuation to this post: https://github.com/webmachinelearning/webnn/issues/3#issuecomment-462452394

@anssiko wrote:

> Re low-level and high-level, I observe much of the confusion arises from the inconsistent use of these adjectives in different contexts. Low-level & high-level APIs and low-level & high-level use cases do not map and that causes us talking past each other. We need to add definitions of there terms to the spec, or come up with better names.

Totally agree, easy to mix these terms, this should be more self describing in my opinion, more-less like this:

Predefined ML models:
* predefined models (or as @anssiko mentioned "pre-canned models")
* predefined models API

Generic ML:
* ML API - top level ML api for NN preparing, modifying, running, training, data preparing
* ML operators API - operators specific api
* operators list
* graph format

And each of above will have naturally its own use cases.

**Comment by anssiko** [comment]
I submitted #10 as a partial fix. To me, _application-level_ and _API-level_ are more self-documenting than generic _low-level_ and _high-level_. Let the bikeshedding begin.

**Comment by anssiko** [comment]
It seems #10 addressed the immediate concern with naming, and the spec is now consistent with the charter language.
