### ISSUE TITLE
WebNN polyfill and samples

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn#81]
As we are iterating the API design and adding more examples, a polyfill with run-able sample code would be helpful. 

For example, in PR #80 review, the [running version](https://jsfiddle.net/ningxinhu/kd1wvjop/) of the [examples]() based on a simple polyfill got good feedbacks from reviewers. 

So I propose to create two repos that host the development of polyfill and sample code.
 * polyfill: https://github.com/webmachinelearning/webnn-polyfill
 * samples: https://github.com/webmachinelearning/webnn-samples

This practice is also adopted by other groups, for example [W3C Immersive Web](https://www.w3.org/immersive-web/) develops [webxr-polyfill](https://github.com/immersive-web/webxr-polyfill) and [webxr-samples](https://github.com/immersive-web/webxr-samples).

**Comment by wchao1115** [comment]
Yes, please do. All the [first-wave models](https://github.com/webmachinelearning/webnn/blob/master/op_compatibility/first_wave_models.md) should become working samples in the samples repo over the polyfill as proofs of the API's functional validity.

**Comment by anssiko** [comment]
From the group's charter's perspective:

- The group can work on [Non-normative Reports](https://webmachinelearning.github.io/charter/#non-normative-reports) and [Test Suites and Other Software](https://webmachinelearning.github.io/charter/#test-suites) ([explainer](https://w3c.github.io/cg-charter/CGCharter.html#test-suites)), and
- [Contribution Mechanics](https://webmachinelearning.github.io/charter/#contrib) permit the use of other than the [W3C Software and Document License](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) for other than Specification deliverables.

Given this, the proposal seems to be in scope of the current charter without any changes to it, so we can avoid the costly process of amending the charter if the group is in agreement.

All - I'd like to make sure no one in this group has concerns with this proposal to adopt the polyfill and samples in support of the WebNN spec work into this group as non-normative deliverables, licensed under the W3C Software and Document License, Apache License 2.0 (similarly to the mentioned webxr-polyfill), or other established permissive free software license. Hearing no concerns within 7 days, I'd approve the creation of the said repos for the development of the webnn-polyfill and samples.

**Comment by anssiko** [comment]
No concerns were raised for the proposed plan. @huningxin feel free to create the respective repos.

**Comment by huningxin** [comment]
Done.

https://github.com/webmachinelearning/webnn-polyfill
https://github.com/webmachinelearning/webnn-samples

I'll follow the pull-request process to add content into these two repos.

**Comment by anssiko** [comment]
Initial contributions to both https://github.com/webmachinelearning/webnn-polyfill and https://github.com/webmachinelearning/webnn-samples have landed, closing this issue.
