### ISSUE TITLE
TAG review

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/webnn#89]
We [agreed](https://www.w3.org/2020/09/03-webmachinelearning-minutes.html#r02) to request a [W3C TAG Spec Review](https://github.com/w3ctag/design-reviews) for the WebNN API.

Before opening the review request, I'll nudge @cynthia to make sure we meet the review readiness expectations. Notably, we do not yet have a comprehensive explainer for this spec.

**Comment by cynthia** [comment]
Generally, we spend more time with the explainer than the spec. It does look like the explainer is somewhat WIP; it would be great if that could be finished up before starting the review.

**Comment by anssiko** [comment]
The [explainer](https://github.com/webmachinelearning/webnn/blob/master/explainer.md) has been completed (thanks to all contributors!) and we're getting ready for the [TAG specification review](https://github.com/w3ctag/design-reviews/). Below is a draft review request for your review. The spec ticks all the boxes apart from the Security and Privacy self-review that is tracked in https://github.com/webmachinelearning/webnn/issues/119.

@wchao1115 @huningxin and all CG participants, please review and provide your feedback and suggestions.

@cynthia feel free to chime in if you think our request draft is lacking in some regard so we can improve before submitting to make sure the request is delightful to review.

[DRAFT] TAG Specification Review: Web Neural Network API
------------------------------------------------------------------------------------

Hi TAG!

I'm requesting a TAG review of the Web Neural Network API.

The Web Neural Netowork API (or WebNN API in short) is a specification for constructing and executing computational graphs of neural networks. It provides web applications with the ability to create, compile, and run machine learning networks on the web browsers. The WebNN API may be implemented in web browsers using the available native operating system machine learning APIs for the best performance and reliability of results.

  - Explainer: https://github.com/webmachinelearning/webnn/blob/master/explainer.md
  - Specification URL: https://webmachinelearning.github.io/webnn/
  - Tests: [mocha tests](https://webmachinelearning.github.io/webnn-polyfill/test/), plan to migrate to wpt testharness.js
  - Security and Privacy self-review: https://github.com/webmachinelearning/webnn/issues/119 (related: [it was suggested](https://www.w3.org/2020/06/machine-learning-workshop/report.html) the W3C TAG to drive coordination on the larger question of permission model for compute-heavy APIs (WebNN, WebGL, WebGPU, Wasm) from a platform-wide perspective)
  - GitHub repo: https://github.com/webmachinelearning/webnn
  - Primary contacts:
      - Ningxin Hu (@huningxin), Intel, Editor
      - Chai Chaoweeraprasit (@wchao1115), Microsoft, Editor
      - Anssi Kostiainen (@anssiko), Intel, Chair
  - Organization(s)/project(s) driving the specification: [Machine Learning for the Web Community Group](https://webmachinelearning.github.io/)
  - Key pieces of existing multi-stakeholder review or discussion of this specification: [Web and Machine Learning workshop report](https://www.w3.org/2020/06/machine-learning-workshop/report.html) and [spec GH issues](https://github.com/webmachinelearning/webnn/issues) 
  - External status/issue trackers for this specification:

Further details:

  - [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)
  - Relevant time constraints or deadlines: We appreciate feedback by the end of 2020.
  - The group where the work on this specification is currently being done: [Machine Learning for the Web Community Group](https://webmachinelearning.github.io/)
  - The group where standardization of this work is intended to be done: Web Machine Learning Working Group (see [advance notice](https://lists.w3.org/Archives/Public/public-new-work/2020Oct/0001.html)) 
  - Major unresolved issues with or opposition to this specification: Appropriate API abstraction level discussed in [WG Charter GH repo](https://github.com/w3c/machine-learning-charter/issues)
  - This work is being funded by: N/A

You should also know that...

[please tell us anything you think is relevant to this review]

We'd prefer the TAG provide feedback as:

  🐛 open issues in our GitHub repo for **each point of feedback**

**Comment by anssiko** [comment]
Per agreement on the [12 November 2020 call](https://github.com/webmachinelearning/meetings/blob/master/telcons/2020-11-12-agenda.md), the TAG review request for the Web Neural Network API has been submitted: https://github.com/w3ctag/design-reviews/issues/570

I'll keep this meta issue in this repo open for the time being for any related discussion.
